var searchData=
[
  ['packcomponents_8517',['PackComponents',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1PackComponents.html',1,'amrex::NonLocalBC']]],
  ['parconstiter_8518',['ParConstIter',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParConstIter.html',1,'amrex']]],
  ['parena_8519',['PArena',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PArena.html',1,'amrex']]],
  ['parforinfo_8520',['ParForInfo',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1ParForInfo.html',1,'amrex::FabArrayBase']]],
  ['pargdb_8521',['ParGDB',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParGDB.html',1,'amrex']]],
  ['pargdbbase_8522',['ParGDBBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParGDBBase.html',1,'amrex']]],
  ['pariter_8523',['ParIter',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIter.html',1,'amrex']]],
  ['pariterbase_8524',['ParIterBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIterBase.html',1,'amrex']]],
  ['pariterbase_3c_20false_2c_20nstructreal_2c_200_2c_200_2c_200_2c_20defaultallocator_20_3e_8525',['ParIterBase&lt; false, NStructReal, 0, 0, 0, DefaultAllocator &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIterBase.html',1,'']]],
  ['pariterbase_3c_20true_2c_20nstructreal_2c_200_2c_200_2c_200_2c_20defaultallocator_20_3e_8526',['ParIterBase&lt; true, NStructReal, 0, 0, 0, DefaultAllocator &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParIterBase.html',1,'']]],
  ['parmparse_8527',['ParmParse',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParmParse.html',1,'amrex']]],
  ['parser_8528',['Parser',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Parser.html',1,'amrex']]],
  ['parser_5fassign_8529',['parser_assign',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__assign.html',1,'amrex']]],
  ['parser_5ff1_8530',['parser_f1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f1.html',1,'amrex']]],
  ['parser_5ff2_8531',['parser_f2',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f2.html',1,'amrex']]],
  ['parser_5ff3_8532',['parser_f3',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__f3.html',1,'amrex']]],
  ['parser_5fnode_8533',['parser_node',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__node.html',1,'amrex']]],
  ['parser_5fnumber_8534',['parser_number',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__number.html',1,'amrex']]],
  ['parser_5fnvp_8535',['parser_nvp',['https://amrex-codes.github.io/amrex/doxygen/unionamrex_1_1parser__nvp.html',1,'amrex']]],
  ['parser_5fsymbol_8536',['parser_symbol',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1parser__symbol.html',1,'amrex']]],
  ['parserexeadd_8537',['ParserExeADD',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD.html',1,'amrex']]],
  ['parserexeadd_5fpn_8538',['ParserExeADD_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__PN.html',1,'amrex']]],
  ['parserexeadd_5fpp_8539',['ParserExeADD_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__PP.html',1,'amrex']]],
  ['parserexeadd_5fvn_8540',['ParserExeADD_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__VN.html',1,'amrex']]],
  ['parserexeadd_5fvp_8541',['ParserExeADD_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeADD__VP.html',1,'amrex']]],
  ['parserexecutor_8542',['ParserExecutor',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'amrex']]],
  ['parserexecutor_3c_203_20_3e_8543',['ParserExecutor&lt; 3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'ParserExecutor&lt; 3 &gt;'],['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExecutor.html',1,'amrex::ParserExecutor&lt; 3 &gt;']]],
  ['parserexediv_5fb_8544',['ParserExeDIV_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__B.html',1,'amrex']]],
  ['parserexediv_5ff_8545',['ParserExeDIV_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__F.html',1,'amrex']]],
  ['parserexediv_5fpn_8546',['ParserExeDIV_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__PN.html',1,'amrex']]],
  ['parserexediv_5fpp_8547',['ParserExeDIV_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__PP.html',1,'amrex']]],
  ['parserexediv_5fvn_8548',['ParserExeDIV_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__VN.html',1,'amrex']]],
  ['parserexediv_5fvp_8549',['ParserExeDIV_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeDIV__VP.html',1,'amrex']]],
  ['parserexef1_8550',['ParserExeF1',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF1.html',1,'amrex']]],
  ['parserexef2_5fb_8551',['ParserExeF2_B',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF2__B.html',1,'amrex']]],
  ['parserexef2_5ff_8552',['ParserExeF2_F',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeF2__F.html',1,'amrex']]],
  ['parserexeif_8553',['ParserExeIF',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeIF.html',1,'amrex']]],
  ['parserexejump_8554',['ParserExeJUMP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeJUMP.html',1,'amrex']]],
  ['parserexemul_8555',['ParserExeMUL',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL.html',1,'amrex']]],
  ['parserexemul_5fpn_8556',['ParserExeMUL_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__PN.html',1,'amrex']]],
  ['parserexemul_5fpp_8557',['ParserExeMUL_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__PP.html',1,'amrex']]],
  ['parserexemul_5fvn_8558',['ParserExeMUL_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__VN.html',1,'amrex']]],
  ['parserexemul_5fvp_8559',['ParserExeMUL_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeMUL__VP.html',1,'amrex']]],
  ['parserexeneg_8560',['ParserExeNEG',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNEG.html',1,'amrex']]],
  ['parserexeneg_5fp_8561',['ParserExeNEG_P',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNEG__P.html',1,'amrex']]],
  ['parserexenull_8562',['ParserExeNull',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNull.html',1,'amrex']]],
  ['parserexenumber_8563',['ParserExeNumber',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeNumber.html',1,'amrex']]],
  ['parserexesub_8564',['ParserExeSUB',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB.html',1,'amrex']]],
  ['parserexesub_5fpn_8565',['ParserExeSUB_PN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__PN.html',1,'amrex']]],
  ['parserexesub_5fpp_8566',['ParserExeSUB_PP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__PP.html',1,'amrex']]],
  ['parserexesub_5fvn_8567',['ParserExeSUB_VN',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__VN.html',1,'amrex']]],
  ['parserexesub_5fvp_8568',['ParserExeSUB_VP',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSUB__VP.html',1,'amrex']]],
  ['parserexesymbol_8569',['ParserExeSymbol',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserExeSymbol.html',1,'amrex']]],
  ['parserif_8570',['ParserIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1ParserIF.html',1,'amrex::EB2']]],
  ['parserstack_8571',['ParserStack',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParserStack.html',1,'amrex']]],
  ['particle_8572',['Particle',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Particle.html',1,'amrex']]],
  ['particlearray_8573',['ParticleArray',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleArray.html',1,'amrex']]],
  ['particlearrayaccessor_8574',['ParticleArrayAccessor',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleArrayAccessor.html',1,'amrex']]],
  ['particlebase_8575',['ParticleBase',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase.html',1,'amrex']]],
  ['particlebase_3c_20particlereal_2c_20t_5fnreal_2c_200_20_3e_8576',['ParticleBase&lt; ParticleReal, T_NReal, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase.html',1,'']]],
  ['particlebase_3c_20t_2c_200_2c_200_20_3e_8577',['ParticleBase&lt; T, 0, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_010_00_010_01_4.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_200_2c_20nint_20_3e_8578',['ParticleBase&lt; T, 0, NInt &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_010_00_01NInt_01_4.html',1,'amrex']]],
  ['particlebase_3c_20t_2c_20nreal_2c_200_20_3e_8579',['ParticleBase&lt; T, NReal, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleBase_3_01T_00_01NReal_00_010_01_4.html',1,'amrex']]],
  ['particlebuffermap_8580',['ParticleBufferMap',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleBufferMap.html',1,'amrex']]],
  ['particlecommdata_8581',['ParticleCommData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCommData.html',1,'amrex']]],
  ['particlecontainer_8582',['ParticleContainer',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainer.html',1,'amrex']]],
  ['particlecontainer_3c_20amrex_5fspacedim_20_3e_8583',['ParticleContainer&lt; AMREX_SPACEDIM &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainer.html',1,'']]],
  ['particlecontainer_3c_20nstructreal_2c_200_2c_200_2c_200_2c_20defaultallocator_20_3e_8584',['ParticleContainer&lt; NStructReal, 0, 0, 0, DefaultAllocator &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainer.html',1,'']]],
  ['particlecontainer_3c_20nstructreal_2c_20nstructint_2c_200_2c_200_20_3e_8585',['ParticleContainer&lt; NStructReal, NStructInt, 0, 0 &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainer.html',1,'']]],
  ['particlecontainerbase_8586',['ParticleContainerBase',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleContainerBase.html',1,'amrex']]],
  ['particlecopyop_8587',['ParticleCopyOp',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCopyOp.html',1,'amrex']]],
  ['particlecopyplan_8588',['ParticleCopyPlan',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCopyPlan.html',1,'amrex']]],
  ['particlecpuwrapper_8589',['ParticleCPUWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleCPUWrapper.html',1,'amrex']]],
  ['particleidwrapper_8590',['ParticleIDWrapper',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleIDWrapper.html',1,'amrex']]],
  ['particleinittype_8591',['ParticleInitType',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleInitType.html',1,'amrex']]],
  ['particlelocator_8592',['ParticleLocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleLocator.html',1,'amrex']]],
  ['particlelocator_3c_20amrex_3a_3adensebins_3c_20amrex_3a_3abox_20_3e_20_3e_8593',['ParticleLocator&lt; amrex::DenseBins&lt; amrex::Box &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParticleLocator.html',1,'']]],
  ['particlelocdata_8594',['ParticleLocData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleLocData.html',1,'amrex']]],
  ['particletile_8595',['ParticleTile',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTile.html',1,'amrex']]],
  ['particletiledata_8596',['ParticleTileData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParticleTileData.html',1,'amrex']]],
  ['pcdata_8597',['PCData',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'amrex']]],
  ['pcdata_3c_20amrex_3a_3abasefab_3c_20atomicint_20_3e_20_3e_8598',['PCData&lt; amrex::BaseFab&lt; AtomicInt &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcdata_3c_20amrex_3a_3abasefab_3c_20hypre_5fint_20_3e_20_3e_8599',['PCData&lt; amrex::BaseFab&lt; HYPRE_Int &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcdata_3c_20amrex_3a_3abasefab_3c_20petscint_20_3e_20_3e_8600',['PCData&lt; amrex::BaseFab&lt; PetscInt &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcdata_3c_20amrex_3a_3acutfab_20_3e_8601',['PCData&lt; amrex::CutFab &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcdata_3c_20amrex_3a_3aebcellflagfab_20_3e_8602',['PCData&lt; amrex::EBCellFlagFab &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcdata_3c_20amrex_3a_3amask_20_3e_8603',['PCData&lt; amrex::Mask &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcdata_3c_20fab_20_3e_8604',['PCData&lt; FAB &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'amrex']]],
  ['pcdata_3c_20farraybox_20_3e_8605',['PCData&lt; FArrayBox &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcdata_3c_20iarraybox_20_3e_8606',['PCData&lt; IArrayBox &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcdata_3c_20tagbox_20_3e_8607',['PCData&lt; TagBox &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PCData.html',1,'']]],
  ['pcinterp_8608',['PCInterp',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PCInterp.html',1,'amrex']]],
  ['periodicity_8609',['Periodicity',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Periodicity.html',1,'amrex']]],
  ['persistentifstream_8610',['PersistentIFStream',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1VisMF_1_1PersistentIFStream.html',1,'amrex::VisMF']]],
  ['petscabeclap_8611',['PETScABecLap',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PETScABecLap.html',1,'amrex']]],
  ['physbcfunct_8612',['PhysBCFunct',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunct.html',1,'amrex']]],
  ['physbcfunctnoop_8613',['PhysBCFunctNoOp',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PhysBCFunctNoOp.html',1,'amrex']]],
  ['pinned_8614',['Pinned',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1Pinned.html',1,'amrex::Gpu']]],
  ['pinnedarenaallocator_8615',['PinnedArenaAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PinnedArenaAllocator.html',1,'amrex']]],
  ['planeif_8616',['PlaneIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PlaneIF.html',1,'amrex::EB2']]],
  ['plotfiledata_8617',['PlotFileData',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PlotFileData.html',1,'amrex']]],
  ['plotfiledataimpl_8618',['PlotFileDataImpl',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PlotFileDataImpl.html',1,'amrex']]],
  ['plus_8619',['Plus',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Plus.html',1,'amrex']]],
  ['podvector_8620',['PODVector',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20amrex_3a_3aassigngrid_3c_20biniteratorfactory_20_3e_20_3e_8621',['PODVector&lt; amrex::AssignGrid&lt; BinIteratorFactory &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; amrex::AssignGrid&lt; BinIteratorFactory &gt; &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; amrex::AssignGrid&lt; BinIteratorFactory &gt; &gt;']]],
  ['podvector_3c_20amrex_3a_3abox_20_3e_8622',['PODVector&lt; amrex::Box &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; amrex::Box &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; amrex::Box &gt;']]],
  ['podvector_3c_20amrex_3a_3agpuarray_3c_20amrex_3a_3amlcelllinop_3a_3abctl_2c_202_20_2aamrex_5fspacedim_20_3e_20_3e_8623',['PODVector&lt; amrex::GpuArray&lt; amrex::MLCellLinOp::BCTL, 2 *AMREX_SPACEDIM &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; amrex::GpuArray&lt; amrex::MLCellLinOp::BCTL, 2 *AMREX_SPACEDIM &gt; &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; amrex::GpuArray&lt; amrex::MLCellLinOp::BCTL, 2 *AMREX_SPACEDIM &gt; &gt;']]],
  ['podvector_3c_20amrex_3a_3aintvect_20_3e_8624',['PODVector&lt; amrex::IntVect &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20amrex_3a_3aneighborcode_20_3e_8625',['PODVector&lt; amrex::NeighborCode &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; amrex::NeighborCode &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; amrex::NeighborCode &gt;']]],
  ['podvector_3c_20amrex_3a_3aopenbc_3a_3amomtag_20_3e_8626',['PODVector&lt; amrex::openbc::MomTag &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; amrex::openbc::MomTag &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; amrex::openbc::MomTag &gt;']]],
  ['podvector_3c_20amrex_3a_3astltools_3a_3atriangle_20_3e_8627',['PODVector&lt; amrex::STLtools::Triangle &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; amrex::STLtools::Triangle &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; amrex::STLtools::Triangle &gt;']]],
  ['podvector_3c_20amrex_3a_3axdim3_20_3e_8628',['PODVector&lt; amrex::XDim3 &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; amrex::XDim3 &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; amrex::XDim3 &gt;']]],
  ['podvector_3c_20char_20_3e_8629',['PODVector&lt; char &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; char &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; char &gt;']]],
  ['podvector_3c_20char_2c_20amrex_3a_3apolymorphicarenaallocator_3c_20char_20_3e_20_3e_8630',['PODVector&lt; char, amrex::PolymorphicArenaAllocator&lt; char &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; char, amrex::PolymorphicArenaAllocator&lt; char &gt; &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; char, amrex::PolymorphicArenaAllocator&lt; char &gt; &gt;']]],
  ['podvector_3c_20const_20int_20_2a_2c_20allocator_3c_20const_20int_20_2a_20_3e_20_3e_8631',['PODVector&lt; const int *, Allocator&lt; const int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20int_20_2a_2c_20defaultallocator_3c_20const_20int_20_2a_20_3e_20_3e_8632',['PODVector&lt; const int *, DefaultAllocator&lt; const int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20const_20particlereal_20_2a_2c_20allocator_3c_20const_20particlereal_20_2a_20_3e_20_3e_8633',['PODVector&lt; const ParticleReal *, Allocator&lt; const ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20const_20particlereal_20_2a_2c_20defaultallocator_3c_20const_20particlereal_20_2a_20_3e_20_3e_8634',['PODVector&lt; const ParticleReal *, DefaultAllocator&lt; const ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20index_5ftype_20_3e_8635',['PODVector&lt; index_type &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; index_type &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; index_type &gt;']]],
  ['podvector_3c_20int_20_2a_2c_20allocator_3c_20int_20_2a_20_3e_20_3e_8636',['PODVector&lt; int *, Allocator&lt; int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20int_20_2a_2c_20defaultallocator_3c_20int_20_2a_20_3e_20_3e_8637',['PODVector&lt; int *, DefaultAllocator&lt; int * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20int_20_3e_8638',['PODVector&lt; int &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; int &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; Int &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; int &gt;']]],
  ['podvector_3c_20particlereal_20_2a_2c_20allocator_3c_20particlereal_20_2a_20_3e_20_3e_8639',['PODVector&lt; ParticleReal *, Allocator&lt; ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particlereal_20_2a_2c_20defaultallocator_3c_20particlereal_20_2a_20_3e_20_3e_8640',['PODVector&lt; ParticleReal *, DefaultAllocator&lt; ParticleReal * &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'']]],
  ['podvector_3c_20particletype_2c_20allocator_3c_20particletype_20_3e_20_3e_8641',['PODVector&lt; ParticleType, Allocator&lt; ParticleType &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex']]],
  ['podvector_3c_20particletype_2c_20defaultallocator_3c_20particletype_20_3e_20_3e_8642',['PODVector&lt; ParticleType, DefaultAllocator&lt; ParticleType &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; ParticleType, DefaultAllocator&lt; ParticleType &gt; &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; ParticleType, DefaultAllocator&lt; ParticleType &gt; &gt;']]],
  ['podvector_3c_20std_3a_3asize_5ft_20_3e_8643',['PODVector&lt; std::size_t &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; std::size_t &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; std::size_t &gt;']]],
  ['podvector_3c_20unsigned_20int_20_3e_8644',['PODVector&lt; unsigned int &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'PODVector&lt; unsigned int &gt;'],['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PODVector.html',1,'amrex::PODVector&lt; unsigned int &gt;']]],
  ['polarb_8645',['PolarB',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1PolarB.html',1,'amrex::FabArrayBase']]],
  ['polarfn_8646',['PolarFn',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1PolarFn.html',1,'amrex::NonLocalBC']]],
  ['polarfn2_8647',['PolarFn2',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1PolarFn2.html',1,'amrex::NonLocalBC']]],
  ['poly_5feval_8648',['poly_eval',['https://amrex-codes.github.io/amrex/doxygen/interfacesdcquadrature__mod_1_1poly__eval.html',1,'sdcquadrature_mod']]],
  ['polyif_8649',['PolyIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolyIF.html',1,'amrex::EB2']]],
  ['polymorphicallocator_8650',['PolymorphicAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PolymorphicAllocator.html',1,'amrex']]],
  ['polymorphicarenaallocator_8651',['PolymorphicArenaAllocator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PolymorphicArenaAllocator.html',1,'amrex']]],
  ['polymorphicarenaallocator_3c_20char_20_3e_8652',['PolymorphicArenaAllocator&lt; char &gt;',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PolymorphicArenaAllocator.html',1,'']]],
  ['polymorphicarray4_8653',['PolymorphicArray4',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1PolymorphicArray4.html',1,'amrex']]],
  ['polynomialif_8654',['PolynomialIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolynomialIF.html',1,'amrex::EB2']]],
  ['polyterm_8655',['PolyTerm',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1PolyTerm.html',1,'amrex::EB2']]],
  ['pp_5fentry_8656',['PP_entry',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParmParse_1_1PP__entry.html',1,'amrex::ParmParse']]],
  ['print_8657',['Print',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1Print.html',1,'amrex']]],
  ['printtofile_8658',['PrintToFile',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1PrintToFile.html',1,'amrex']]],
  ['process_5ftopology_5ft_8659',['process_topology_t',['https://amrex-codes.github.io/amrex/doxygen/structprocess__topology__t.html',1,'']]],
  ['processteam_8660',['ProcessTeam',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ParallelDescriptor_1_1ProcessTeam.html',1,'amrex::ParallelDescriptor']]],
  ['procstats_8661',['ProcStats',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1TinyProfiler_1_1ProcStats.html',1,'amrex::TinyProfiler']]],
  ['psicode_8662',['PsiCode',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1algoim_1_1PsiCode.html',1,'amrex::algoim']]],
  ['psicode_3c_20n_20_3e_2c_201_3c_3c_28n_20_2d_201_29_3e_8663',['PsiCode&lt; N &gt;, 1&lt;&lt;(N - 1)&gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'amrex::PsiCode&lt; N &gt;, 1&lt;&lt;(N - 1)&gt;'],['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1GpuArray.html',1,'PsiCode&lt; N &gt;, 1&lt;&lt;(N - 1)&gt;']]]
];
