var searchData=
[
  ['randomengine_9249',['RandomEngine',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RandomEngine.html',1,'amrex']]],
  ['range_5fimpl_9250',['range_impl',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1range__detail_1_1range__impl.html',1,'amrex::Gpu::range_detail']]],
  ['rb180_9251',['RB180',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RB180.html',1,'amrex::FabArrayBase']]],
  ['rb90_9252',['RB90',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RB90.html',1,'amrex::FabArrayBase']]],
  ['realbox_9253',['RealBox',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealBox.html',1,'amrex']]],
  ['realdescriptor_9254',['RealDescriptor',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealDescriptor.html',1,'amrex']]],
  ['realvect_9255',['RealVect',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealVect.html',1,'amrex']]],
  ['rebind_9256',['rebind',['https://amrex-codes.github.io/amrex/doxygen/structhacc_1_1AlignedAllocator_1_1rebind.html',1,'hacc::AlignedAllocator']]],
  ['record_9257',['Record',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParmParse_1_1Record.html',1,'amrex::ParmParse']]],
  ['redistributeunpackpolicy_9258',['RedistributeUnpackPolicy',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RedistributeUnpackPolicy.html',1,'amrex']]],
  ['reducedata_9259',['ReduceData',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ReduceData.html',1,'amrex']]],
  ['reduceoplogicaland_9260',['ReduceOpLogicalAnd',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpLogicalAnd.html',1,'amrex']]],
  ['reduceoplogicalor_9261',['ReduceOpLogicalOr',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpLogicalOr.html',1,'amrex']]],
  ['reduceopmax_9262',['ReduceOpMax',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpMax.html',1,'amrex']]],
  ['reduceopmin_9263',['ReduceOpMin',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpMin.html',1,'amrex']]],
  ['reduceops_9264',['ReduceOps',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ReduceOps.html',1,'amrex']]],
  ['reduceopsum_9265',['ReduceOpSum',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpSum.html',1,'amrex']]],
  ['reductionentry_9266',['ReductionEntry',['https://amrex-codes.github.io/amrex/doxygen/structCommProfStats_1_1ReductionEntry.html',1,'CommProfStats']]],
  ['ref_9267',['Ref',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1DistributionMapping_1_1Ref.html',1,'amrex::DistributionMapping']]],
  ['ref_5fwrapper_9268',['ref_wrapper',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ref__wrapper.html',1,'amrex']]],
  ['refid_9269',['RefID',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1BoxArray_1_1RefID.html',1,'amrex::BoxArray::RefID'],['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1DistributionMapping_1_1RefID.html',1,'amrex::DistributionMapping::RefID']]],
  ['regionsprofstats_9270',['RegionsProfStats',['https://amrex-codes.github.io/amrex/doxygen/classRegionsProfStats.html',1,'']]],
  ['regiontag_9271',['RegionTag',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RegionTag.html',1,'amrex::FabArrayBase']]],
  ['retsum_9272',['RetSum',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Scan_1_1RetSum.html',1,'amrex::Scan']]],
  ['rkintegrator_9273',['RKIntegrator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RKIntegrator.html',1,'amrex']]],
  ['rotationif_9274',['RotationIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1RotationIF.html',1,'amrex::EB2']]],
  ['runongpu_9275',['RunOnGpu',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu.html',1,'amrex']]],
  ['runongpu_3c_20arenaallocator_3c_20t_20_3e_20_3e_9276',['RunOnGpu&lt; ArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01ArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20asyncarenaallocator_3c_20t_20_3e_20_3e_9277',['RunOnGpu&lt; AsyncArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01AsyncArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20devicearenaallocator_3c_20t_20_3e_20_3e_9278',['RunOnGpu&lt; DeviceArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01DeviceArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20managedarenaallocator_3c_20t_20_3e_20_3e_9279',['RunOnGpu&lt; ManagedArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01ManagedArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]]
];
