var searchData=
[
  ['randomengine_8459',['RandomEngine',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RandomEngine.html',1,'amrex']]],
  ['range_5fimpl_8460',['range_impl',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Gpu_1_1range__detail_1_1range__impl.html',1,'amrex::Gpu::range_detail']]],
  ['rb180_8461',['RB180',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RB180.html',1,'amrex::FabArrayBase']]],
  ['rb90_8462',['RB90',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RB90.html',1,'amrex::FabArrayBase']]],
  ['realbox_8463',['RealBox',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealBox.html',1,'amrex']]],
  ['realdescriptor_8464',['RealDescriptor',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealDescriptor.html',1,'amrex']]],
  ['realvect_8465',['RealVect',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RealVect.html',1,'amrex']]],
  ['rebind_8466',['rebind',['https://amrex-codes.github.io/amrex/doxygen/structhacc_1_1AlignedAllocator_1_1rebind.html',1,'hacc::AlignedAllocator']]],
  ['record_8467',['Record',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ParmParse_1_1Record.html',1,'amrex::ParmParse']]],
  ['redistributeunpackpolicy_8468',['RedistributeUnpackPolicy',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RedistributeUnpackPolicy.html',1,'amrex']]],
  ['reducedata_8469',['ReduceData',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ReduceData.html',1,'amrex']]],
  ['reduceoplogicaland_8470',['ReduceOpLogicalAnd',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpLogicalAnd.html',1,'amrex']]],
  ['reduceoplogicalor_8471',['ReduceOpLogicalOr',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpLogicalOr.html',1,'amrex']]],
  ['reduceopmax_8472',['ReduceOpMax',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpMax.html',1,'amrex']]],
  ['reduceopmin_8473',['ReduceOpMin',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpMin.html',1,'amrex']]],
  ['reduceops_8474',['ReduceOps',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ReduceOps.html',1,'amrex']]],
  ['reduceopsum_8475',['ReduceOpSum',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1ReduceOpSum.html',1,'amrex']]],
  ['reductionentry_8476',['ReductionEntry',['https://amrex-codes.github.io/amrex/doxygen/structCommProfStats_1_1ReductionEntry.html',1,'CommProfStats']]],
  ['ref_8477',['Ref',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1DistributionMapping_1_1Ref.html',1,'amrex::DistributionMapping']]],
  ['ref_5fwrapper_8478',['ref_wrapper',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1ref__wrapper.html',1,'amrex']]],
  ['refid_8479',['RefID',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1BoxArray_1_1RefID.html',1,'amrex::BoxArray::RefID'],['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1DistributionMapping_1_1RefID.html',1,'amrex::DistributionMapping::RefID']]],
  ['regionsprofstats_8480',['RegionsProfStats',['https://amrex-codes.github.io/amrex/doxygen/classRegionsProfStats.html',1,'']]],
  ['regiontag_8481',['RegionTag',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1FabArrayBase_1_1RegionTag.html',1,'amrex::FabArrayBase']]],
  ['retsum_8482',['RetSum',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1Scan_1_1RetSum.html',1,'amrex::Scan']]],
  ['rkintegrator_8483',['RKIntegrator',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1RKIntegrator.html',1,'amrex']]],
  ['rotate180fn_8484',['Rotate180Fn',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1Rotate180Fn.html',1,'amrex::NonLocalBC']]],
  ['rotate90clockwise_8485',['Rotate90ClockWise',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1Rotate90ClockWise.html',1,'amrex::NonLocalBC']]],
  ['rotate90counterclockwise_8486',['Rotate90CounterClockWise',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1Rotate90CounterClockWise.html',1,'amrex::NonLocalBC']]],
  ['rotate90dsttosrc_8487',['Rotate90DstToSrc',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1NonLocalBC_1_1Rotate90DstToSrc.html',1,'amrex::NonLocalBC']]],
  ['rotationif_8488',['RotationIF',['https://amrex-codes.github.io/amrex/doxygen/classamrex_1_1EB2_1_1RotationIF.html',1,'amrex::EB2']]],
  ['runongpu_8489',['RunOnGpu',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu.html',1,'amrex']]],
  ['runongpu_3c_20arenaallocator_3c_20t_20_3e_20_3e_8490',['RunOnGpu&lt; ArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01ArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20asyncarenaallocator_3c_20t_20_3e_20_3e_8491',['RunOnGpu&lt; AsyncArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01AsyncArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20devicearenaallocator_3c_20t_20_3e_20_3e_8492',['RunOnGpu&lt; DeviceArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01DeviceArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]],
  ['runongpu_3c_20managedarenaallocator_3c_20t_20_3e_20_3e_8493',['RunOnGpu&lt; ManagedArenaAllocator&lt; T &gt; &gt;',['https://amrex-codes.github.io/amrex/doxygen/structamrex_1_1RunOnGpu_3_01ManagedArenaAllocator_3_01T_01_4_01_4.html',1,'amrex']]]
];
