var annotated_dup =
[
    [ "amrex", "namespaceamrex.html", [
      [ "AsyncOut", "namespaceamrex_1_1AsyncOut.html", [
        [ "WriteInfo", "structamrex_1_1AsyncOut_1_1WriteInfo.html", "structamrex_1_1AsyncOut_1_1WriteInfo" ]
      ] ],
      [ "BinPolicy", "namespaceamrex_1_1BinPolicy.html", [
        [ "GPUBinPolicy", "structamrex_1_1BinPolicy_1_1GPUBinPolicy.html", null ],
        [ "OpenMPBinPolicy", "structamrex_1_1BinPolicy_1_1OpenMPBinPolicy.html", null ],
        [ "SerialBinPolicy", "structamrex_1_1BinPolicy_1_1SerialBinPolicy.html", null ]
      ] ],
      [ "EB2", "namespaceamrex_1_1EB2.html", [
        [ "AllRegularIF", "classamrex_1_1EB2_1_1AllRegularIF.html", "classamrex_1_1EB2_1_1AllRegularIF" ],
        [ "BoxIF", "classamrex_1_1EB2_1_1BoxIF.html", "classamrex_1_1EB2_1_1BoxIF" ],
        [ "Cell", "structamrex_1_1EB2_1_1Cell.html", "structamrex_1_1EB2_1_1Cell" ],
        [ "ChkptFile", "classamrex_1_1EB2_1_1ChkptFile.html", "classamrex_1_1EB2_1_1ChkptFile" ],
        [ "ChkptFileLevel", "classamrex_1_1EB2_1_1ChkptFileLevel.html", "classamrex_1_1EB2_1_1ChkptFileLevel" ],
        [ "ComplementIF", "classamrex_1_1EB2_1_1ComplementIF.html", "classamrex_1_1EB2_1_1ComplementIF" ],
        [ "CylinderIF", "classamrex_1_1EB2_1_1CylinderIF.html", "classamrex_1_1EB2_1_1CylinderIF" ],
        [ "DevicePtrIF", "classamrex_1_1EB2_1_1DevicePtrIF.html", "classamrex_1_1EB2_1_1DevicePtrIF" ],
        [ "DifferenceIF", "classamrex_1_1EB2_1_1DifferenceIF.html", "classamrex_1_1EB2_1_1DifferenceIF" ],
        [ "Edge", "structamrex_1_1EB2_1_1Edge.html", "structamrex_1_1EB2_1_1Edge" ],
        [ "EllipsoidIF", "classamrex_1_1EB2_1_1EllipsoidIF.html", "classamrex_1_1EB2_1_1EllipsoidIF" ],
        [ "ExtrusionIF", "classamrex_1_1EB2_1_1ExtrusionIF.html", "classamrex_1_1EB2_1_1ExtrusionIF" ],
        [ "Face", "structamrex_1_1EB2_1_1Face.html", "structamrex_1_1EB2_1_1Face" ],
        [ "GeometryShop", "classamrex_1_1EB2_1_1GeometryShop.html", "classamrex_1_1EB2_1_1GeometryShop" ],
        [ "GFab", "classamrex_1_1EB2_1_1GFab.html", "classamrex_1_1EB2_1_1GFab" ],
        [ "GShopLevel", "classamrex_1_1EB2_1_1GShopLevel.html", "classamrex_1_1EB2_1_1GShopLevel" ],
        [ "IndexSpace", "classamrex_1_1EB2_1_1IndexSpace.html", "classamrex_1_1EB2_1_1IndexSpace" ],
        [ "IndexSpaceChkptFile", "classamrex_1_1EB2_1_1IndexSpaceChkptFile.html", "classamrex_1_1EB2_1_1IndexSpaceChkptFile" ],
        [ "IndexSpaceImp", "classamrex_1_1EB2_1_1IndexSpaceImp.html", "classamrex_1_1EB2_1_1IndexSpaceImp" ],
        [ "IndexSpaceSTL", "classamrex_1_1EB2_1_1IndexSpaceSTL.html", "classamrex_1_1EB2_1_1IndexSpaceSTL" ],
        [ "IntersectionIF", "classamrex_1_1EB2_1_1IntersectionIF.html", "classamrex_1_1EB2_1_1IntersectionIF" ],
        [ "IsGPUable", "structamrex_1_1EB2_1_1IsGPUable.html", null ],
        [ "IsGPUable< ComplementIF< F >, std::enable_if_t< IsGPUable< F >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01ComplementIF_3_01F_01_4_00_01std_1_1enable__if__t_3_01IsGPUae5a3ecdbbe2872ad1fcb116fcced2fba.html", null ],
        [ "IsGPUable< D, std::enable_if_t< std::is_base_of_v< GPUable, D > > >", "structamrex_1_1EB2_1_1IsGPUable_3_01D_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01GPUable_00_01D_01_4_01_4_01_4.html", null ],
        [ "IsGPUable< DifferenceIF< F, G >, std::enable_if_t< IsGPUable< F >::value &&IsGPUable< G >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01DifferenceIF_3_01F_00_01G_01_4_00_01std_1_1enable__if__t_3_0b8f5d460277f1d91a5423c29613f5d25.html", null ],
        [ "IsGPUable< ExtrusionIF< F >, std::enable_if_t< IsGPUable< F >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01ExtrusionIF_3_01F_01_4_00_01std_1_1enable__if__t_3_01IsGPUabf062b6fd2701f97c86146ed02bddaa9e.html", null ],
        [ "IsGPUable< IntersectionIF< F >, std::enable_if_t< IsGPUable< F >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01IntersectionIF_3_01F_01_4_00_01std_1_1enable__if__t_3_01IsGPf9c8a061c673452f35713630afd9be10.html", null ],
        [ "IsGPUable< IntersectionIF< Head, Tail... >, std::enable_if_t< IsGPUable< Head >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01IntersectionIF_3_01Head_00_01Tail_8_8_8_01_4_00_01std_1_1ena0c37219ffe6b39871c91221e9d798d75.html", null ],
        [ "IsGPUable< LatheIF< F >, std::enable_if_t< IsGPUable< F >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01LatheIF_3_01F_01_4_00_01std_1_1enable__if__t_3_01IsGPUable_3_01F_01_4_1_1value_01_4_01_4.html", null ],
        [ "IsGPUable< RotationIF< F >, std::enable_if_t< IsGPUable< F >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01RotationIF_3_01F_01_4_00_01std_1_1enable__if__t_3_01IsGPUable_3_01F_01_4_1_1value_01_4_01_4.html", null ],
        [ "IsGPUable< ScaleIF< F >, std::enable_if_t< IsGPUable< F >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01ScaleIF_3_01F_01_4_00_01std_1_1enable__if__t_3_01IsGPUable_3_01F_01_4_1_1value_01_4_01_4.html", null ],
        [ "IsGPUable< TranslationIF< F >, std::enable_if_t< IsGPUable< F >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01TranslationIF_3_01F_01_4_00_01std_1_1enable__if__t_3_01IsGPUdd6f125157b8f676e3869d8d3fbaabf1.html", null ],
        [ "IsGPUable< UnionIF< F >, std::enable_if_t< IsGPUable< F >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01UnionIF_3_01F_01_4_00_01std_1_1enable__if__t_3_01IsGPUable_3_01F_01_4_1_1value_01_4_01_4.html", null ],
        [ "IsGPUable< UnionIF< Head, Tail... >, std::enable_if_t< IsGPUable< Head >::value > >", "structamrex_1_1EB2_1_1IsGPUable_3_01UnionIF_3_01Head_00_01Tail_8_8_8_01_4_00_01std_1_1enable__if6eb1e381bbe58b34365e2ea43c9dd797.html", null ],
        [ "LatheIF", "classamrex_1_1EB2_1_1LatheIF.html", "classamrex_1_1EB2_1_1LatheIF" ],
        [ "Level", "classamrex_1_1EB2_1_1Level.html", "classamrex_1_1EB2_1_1Level" ],
        [ "MultiGFab", "classamrex_1_1EB2_1_1MultiGFab.html", "classamrex_1_1EB2_1_1MultiGFab" ],
        [ "Neighbor", "structamrex_1_1EB2_1_1Neighbor.html", "structamrex_1_1EB2_1_1Neighbor" ],
        [ "ParserIF", "classamrex_1_1EB2_1_1ParserIF.html", "classamrex_1_1EB2_1_1ParserIF" ],
        [ "PlaneIF", "classamrex_1_1EB2_1_1PlaneIF.html", "classamrex_1_1EB2_1_1PlaneIF" ],
        [ "PolyIF", "classamrex_1_1EB2_1_1PolyIF.html", "classamrex_1_1EB2_1_1PolyIF" ],
        [ "PolynomialIF", "classamrex_1_1EB2_1_1PolynomialIF.html", "classamrex_1_1EB2_1_1PolynomialIF" ],
        [ "PolyTerm", "classamrex_1_1EB2_1_1PolyTerm.html", "classamrex_1_1EB2_1_1PolyTerm" ],
        [ "RotationIF", "classamrex_1_1EB2_1_1RotationIF.html", "classamrex_1_1EB2_1_1RotationIF" ],
        [ "ScaleIF", "classamrex_1_1EB2_1_1ScaleIF.html", "classamrex_1_1EB2_1_1ScaleIF" ],
        [ "SphereIF", "classamrex_1_1EB2_1_1SphereIF.html", "classamrex_1_1EB2_1_1SphereIF" ],
        [ "SplineIF", "classamrex_1_1EB2_1_1SplineIF.html", "classamrex_1_1EB2_1_1SplineIF" ],
        [ "STLLevel", "classamrex_1_1EB2_1_1STLLevel.html", "classamrex_1_1EB2_1_1STLLevel" ],
        [ "TorusIF", "classamrex_1_1EB2_1_1TorusIF.html", "classamrex_1_1EB2_1_1TorusIF" ],
        [ "TranslationIF", "classamrex_1_1EB2_1_1TranslationIF.html", "classamrex_1_1EB2_1_1TranslationIF" ],
        [ "UnionIF", "classamrex_1_1EB2_1_1UnionIF.html", "classamrex_1_1EB2_1_1UnionIF" ],
        [ "Vertex", "structamrex_1_1EB2_1_1Vertex.html", "structamrex_1_1EB2_1_1Vertex" ]
      ] ],
      [ "FFT", "namespaceamrex_1_1FFT.html", [
        [ "Info", "structamrex_1_1FFT_1_1Info.html", "structamrex_1_1FFT_1_1Info" ],
        [ "LocalR2C", "classamrex_1_1FFT_1_1LocalR2C.html", "classamrex_1_1FFT_1_1LocalR2C" ],
        [ "OpenBCSolver", "classamrex_1_1FFT_1_1OpenBCSolver.html", "classamrex_1_1FFT_1_1OpenBCSolver" ],
        [ "Plan", "structamrex_1_1FFT_1_1Plan.html", "structamrex_1_1FFT_1_1Plan" ],
        [ "Poisson", "classamrex_1_1FFT_1_1Poisson.html", "classamrex_1_1FFT_1_1Poisson" ],
        [ "PoissonHybrid", "classamrex_1_1FFT_1_1PoissonHybrid.html", "classamrex_1_1FFT_1_1PoissonHybrid" ],
        [ "PoissonOpenBC", "classamrex_1_1FFT_1_1PoissonOpenBC.html", "classamrex_1_1FFT_1_1PoissonOpenBC" ],
        [ "R2C", "classamrex_1_1FFT_1_1R2C.html", "classamrex_1_1FFT_1_1R2C" ],
        [ "R2X", "classamrex_1_1FFT_1_1R2X.html", "classamrex_1_1FFT_1_1R2X" ]
      ] ],
      [ "Gpu", "namespaceamrex_1_1Gpu.html", [
        [ "AsyncArray", "classamrex_1_1Gpu_1_1AsyncArray.html", "classamrex_1_1Gpu_1_1AsyncArray" ],
        [ "AtomicAdd", "structamrex_1_1Gpu_1_1AtomicAdd.html", "structamrex_1_1Gpu_1_1AtomicAdd" ],
        [ "AtomicLogicalAnd", "structamrex_1_1Gpu_1_1AtomicLogicalAnd.html", "structamrex_1_1Gpu_1_1AtomicLogicalAnd" ],
        [ "AtomicLogicalOr", "structamrex_1_1Gpu_1_1AtomicLogicalOr.html", "structamrex_1_1Gpu_1_1AtomicLogicalOr" ],
        [ "AtomicMax", "structamrex_1_1Gpu_1_1AtomicMax.html", "structamrex_1_1Gpu_1_1AtomicMax" ],
        [ "AtomicMin", "structamrex_1_1Gpu_1_1AtomicMin.html", "structamrex_1_1Gpu_1_1AtomicMin" ],
        [ "Buffer", "classamrex_1_1Gpu_1_1Buffer.html", "classamrex_1_1Gpu_1_1Buffer" ],
        [ "Deleter", "structamrex_1_1Gpu_1_1Deleter.html", "structamrex_1_1Gpu_1_1Deleter" ],
        [ "Device", "classamrex_1_1Gpu_1_1Device.html", "classamrex_1_1Gpu_1_1Device" ],
        [ "DeviceScalar", "structamrex_1_1Gpu_1_1DeviceScalar.html", "structamrex_1_1Gpu_1_1DeviceScalar" ],
        [ "DeviceToDevice", "structamrex_1_1Gpu_1_1DeviceToDevice.html", null ],
        [ "DeviceToHost", "structamrex_1_1Gpu_1_1DeviceToHost.html", null ],
        [ "Elixir", "classamrex_1_1Gpu_1_1Elixir.html", "classamrex_1_1Gpu_1_1Elixir" ],
        [ "ExecConfig", "structamrex_1_1Gpu_1_1ExecConfig.html", "structamrex_1_1Gpu_1_1ExecConfig" ],
        [ "ExecutionConfig", "structamrex_1_1Gpu_1_1ExecutionConfig.html", "structamrex_1_1Gpu_1_1ExecutionConfig" ],
        [ "GraphSafeGuard", "structamrex_1_1Gpu_1_1GraphSafeGuard.html", "structamrex_1_1Gpu_1_1GraphSafeGuard" ],
        [ "Handler", "structamrex_1_1Gpu_1_1Handler.html", "structamrex_1_1Gpu_1_1Handler" ],
        [ "HostToDevice", "structamrex_1_1Gpu_1_1HostToDevice.html", null ],
        [ "KernelInfo", "classamrex_1_1Gpu_1_1KernelInfo.html", "classamrex_1_1Gpu_1_1KernelInfo" ],
        [ "LaunchSafeGuard", "structamrex_1_1Gpu_1_1LaunchSafeGuard.html", "structamrex_1_1Gpu_1_1LaunchSafeGuard" ],
        [ "Managed", "structamrex_1_1Gpu_1_1Managed.html", "structamrex_1_1Gpu_1_1Managed" ],
        [ "NoSyncRegion", "structamrex_1_1Gpu_1_1NoSyncRegion.html", "structamrex_1_1Gpu_1_1NoSyncRegion" ],
        [ "Pinned", "structamrex_1_1Gpu_1_1Pinned.html", "structamrex_1_1Gpu_1_1Pinned" ],
        [ "SharedMemory", "structamrex_1_1Gpu_1_1SharedMemory.html", "structamrex_1_1Gpu_1_1SharedMemory" ],
        [ "SharedMemory< bool >", "structamrex_1_1Gpu_1_1SharedMemory_3_01bool_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01bool_01_4" ],
        [ "SharedMemory< char >", "structamrex_1_1Gpu_1_1SharedMemory_3_01char_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01char_01_4" ],
        [ "SharedMemory< double >", "structamrex_1_1Gpu_1_1SharedMemory_3_01double_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01double_01_4" ],
        [ "SharedMemory< float >", "structamrex_1_1Gpu_1_1SharedMemory_3_01float_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01float_01_4" ],
        [ "SharedMemory< int >", "structamrex_1_1Gpu_1_1SharedMemory_3_01int_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01int_01_4" ],
        [ "SharedMemory< long >", "structamrex_1_1Gpu_1_1SharedMemory_3_01long_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01long_01_4" ],
        [ "SharedMemory< long long >", "structamrex_1_1Gpu_1_1SharedMemory_3_01long_01long_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01long_01long_01_4" ],
        [ "SharedMemory< openbc::Moments::array_type >", "structamrex_1_1Gpu_1_1SharedMemory_3_01openbc_1_1Moments_1_1array__type_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01openbc_1_1Moments_1_1array__type_01_4" ],
        [ "SharedMemory< short >", "structamrex_1_1Gpu_1_1SharedMemory_3_01short_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01short_01_4" ],
        [ "SharedMemory< unsigned char >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01char_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01char_01_4" ],
        [ "SharedMemory< unsigned int >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01int_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01int_01_4" ],
        [ "SharedMemory< unsigned long >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01long_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01long_01_4" ],
        [ "SharedMemory< unsigned long long >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01long_01long_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01long_01long_01_4" ],
        [ "SharedMemory< unsigned short >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01short_01_4.html", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01short_01_4" ],
        [ "SingleStreamRegion", "structamrex_1_1Gpu_1_1SingleStreamRegion.html", "structamrex_1_1Gpu_1_1SingleStreamRegion" ],
        [ "StreamIter", "classamrex_1_1Gpu_1_1StreamIter.html", "classamrex_1_1Gpu_1_1StreamIter" ],
        [ "StreamItInfo", "structamrex_1_1Gpu_1_1StreamItInfo.html", "structamrex_1_1Gpu_1_1StreamItInfo" ],
        [ "StreamManager", "classamrex_1_1Gpu_1_1StreamManager.html", "classamrex_1_1Gpu_1_1StreamManager" ],
        [ "warpReduce", "structamrex_1_1Gpu_1_1warpReduce.html", "structamrex_1_1Gpu_1_1warpReduce" ]
      ] ],
      [ "Math", "namespaceamrex_1_1Math.html", [
        [ "FastDivmodU64", "structamrex_1_1Math_1_1FastDivmodU64.html", "structamrex_1_1Math_1_1FastDivmodU64" ]
      ] ],
      [ "mpidatatypes", "namespaceamrex_1_1mpidatatypes.html", [
        [ "MPI_Status", "structamrex_1_1mpidatatypes_1_1MPI__Status.html", null ]
      ] ],
      [ "MPMD", "namespaceamrex_1_1MPMD.html", [
        [ "Copier", "classamrex_1_1MPMD_1_1Copier.html", "classamrex_1_1MPMD_1_1Copier" ]
      ] ],
      [ "NonLocalBC", "namespaceamrex_1_1NonLocalBC.html", [
        [ "ApplyDtosAndProjectionOnReciever", "structamrex_1_1NonLocalBC_1_1ApplyDtosAndProjectionOnReciever.html", "structamrex_1_1NonLocalBC_1_1ApplyDtosAndProjectionOnReciever" ],
        [ "CommData", "structamrex_1_1NonLocalBC_1_1CommData.html", "structamrex_1_1NonLocalBC_1_1CommData" ],
        [ "CommHandler", "structamrex_1_1NonLocalBC_1_1CommHandler.html", "structamrex_1_1NonLocalBC_1_1CommHandler" ],
        [ "DoLocalCopy", "structamrex_1_1NonLocalBC_1_1DoLocalCopy.html", null ],
        [ "HasInverseMemFn", "structamrex_1_1NonLocalBC_1_1HasInverseMemFn.html", null ],
        [ "Identity", "structamrex_1_1NonLocalBC_1_1Identity.html", "structamrex_1_1NonLocalBC_1_1Identity" ],
        [ "IsDataPacking", "structamrex_1_1NonLocalBC_1_1IsDataPacking.html", null ],
        [ "IsFabProjection", "structamrex_1_1NonLocalBC_1_1IsFabProjection.html", null ],
        [ "IsIndexMapping", "structamrex_1_1NonLocalBC_1_1IsIndexMapping.html", null ],
        [ "MapComponents", "structamrex_1_1NonLocalBC_1_1MapComponents.html", "structamrex_1_1NonLocalBC_1_1MapComponents" ],
        [ "MultiBlockCommMetaData", "structamrex_1_1NonLocalBC_1_1MultiBlockCommMetaData.html", "structamrex_1_1NonLocalBC_1_1MultiBlockCommMetaData" ],
        [ "MultiBlockIndexMapping", "structamrex_1_1NonLocalBC_1_1MultiBlockIndexMapping.html", "structamrex_1_1NonLocalBC_1_1MultiBlockIndexMapping" ],
        [ "NoLocalCopy", "structamrex_1_1NonLocalBC_1_1NoLocalCopy.html", null ],
        [ "PackComponents", "structamrex_1_1NonLocalBC_1_1PackComponents.html", "structamrex_1_1NonLocalBC_1_1PackComponents" ],
        [ "SwapComponents", "structamrex_1_1NonLocalBC_1_1SwapComponents.html", "structamrex_1_1NonLocalBC_1_1SwapComponents" ],
        [ "SwapComponents< I, -1 >", "structamrex_1_1NonLocalBC_1_1SwapComponents_3_01I_00_01-1_01_4.html", "structamrex_1_1NonLocalBC_1_1SwapComponents_3_01I_00_01-1_01_4" ],
        [ "SwapComponents<-1, -1 >", "structamrex_1_1NonLocalBC_1_1SwapComponents_3-1_00_01-1_01_4.html", "structamrex_1_1NonLocalBC_1_1SwapComponents_3-1_00_01-1_01_4" ],
        [ "SwapComponents<-1, J >", "structamrex_1_1NonLocalBC_1_1SwapComponents_3-1_00_01J_01_4.html", "structamrex_1_1NonLocalBC_1_1SwapComponents_3-1_00_01J_01_4" ]
      ] ],
      [ "ParallelContext", "namespaceamrex_1_1ParallelContext.html", [
        [ "Frame", "classamrex_1_1ParallelContext_1_1Frame.html", "classamrex_1_1ParallelContext_1_1Frame" ]
      ] ],
      [ "ParallelDescriptor", "namespaceamrex_1_1ParallelDescriptor.html", [
        [ "Message", "classamrex_1_1ParallelDescriptor_1_1Message.html", "classamrex_1_1ParallelDescriptor_1_1Message" ],
        [ "Mpi_typemap", "structamrex_1_1ParallelDescriptor_1_1Mpi__typemap.html", "structamrex_1_1ParallelDescriptor_1_1Mpi__typemap" ],
        [ "Mpi_typemap< GpuComplex< T > >", "structamrex_1_1ParallelDescriptor_1_1Mpi__typemap_3_01GpuComplex_3_01T_01_4_01_4.html", "structamrex_1_1ParallelDescriptor_1_1Mpi__typemap_3_01GpuComplex_3_01T_01_4_01_4" ],
        [ "Mpi_typemap< ValLocPair< TV, TI > >", "structamrex_1_1ParallelDescriptor_1_1Mpi__typemap_3_01ValLocPair_3_01TV_00_01TI_01_4_01_4.html", "structamrex_1_1ParallelDescriptor_1_1Mpi__typemap_3_01ValLocPair_3_01TV_00_01TI_01_4_01_4" ],
        [ "ProcessTeam", "structamrex_1_1ParallelDescriptor_1_1ProcessTeam.html", "structamrex_1_1ParallelDescriptor_1_1ProcessTeam" ]
      ] ],
      [ "ParticleInterpolator", "namespaceamrex_1_1ParticleInterpolator.html", [
        [ "Base", "structamrex_1_1ParticleInterpolator_1_1Base.html", "structamrex_1_1ParticleInterpolator_1_1Base" ],
        [ "Linear", "structamrex_1_1ParticleInterpolator_1_1Linear.html", "structamrex_1_1ParticleInterpolator_1_1Linear" ],
        [ "Nearest", "structamrex_1_1ParticleInterpolator_1_1Nearest.html", "structamrex_1_1ParticleInterpolator_1_1Nearest" ]
      ] ],
      [ "RungeKutta", "namespaceamrex_1_1RungeKutta.html", [
        [ "PostStageNoOp", "structamrex_1_1RungeKutta_1_1PostStageNoOp.html", "structamrex_1_1RungeKutta_1_1PostStageNoOp" ]
      ] ],
      [ "Scan", "namespaceamrex_1_1Scan.html", [
        [ "Type", "namespaceamrex_1_1Scan_1_1Type.html", [
          [ "Exclusive", "structamrex_1_1Scan_1_1Type_1_1Exclusive.html", null ],
          [ "Inclusive", "structamrex_1_1Scan_1_1Type_1_1Inclusive.html", null ]
        ] ],
        [ "RetSum", "structamrex_1_1Scan_1_1RetSum.html", "structamrex_1_1Scan_1_1RetSum" ]
      ] ],
      [ "simd", "namespaceamrex_1_1simd.html", [
        [ "Vectorized", "structamrex_1_1simd_1_1Vectorized.html", "structamrex_1_1simd_1_1Vectorized" ]
      ] ],
      [ "sundials", "namespaceamrex_1_1sundials.html", [
        [ "MemoryHelper", "classamrex_1_1sundials_1_1MemoryHelper.html", "classamrex_1_1sundials_1_1MemoryHelper" ],
        [ "N_VectorContent_MultiFab_notptr", "structamrex_1_1sundials_1_1N__VectorContent__MultiFab__notptr.html", "structamrex_1_1sundials_1_1N__VectorContent__MultiFab__notptr" ]
      ] ],
      [ "AlgPartition", "classamrex_1_1AlgPartition.html", "classamrex_1_1AlgPartition" ],
      [ "AlgVector", "classamrex_1_1AlgVector.html", "classamrex_1_1AlgVector" ],
      [ "AllPrint", "classamrex_1_1AllPrint.html", "classamrex_1_1AllPrint" ],
      [ "AllPrintToFile", "classamrex_1_1AllPrintToFile.html", "classamrex_1_1AllPrintToFile" ],
      [ "Amr", "classamrex_1_1Amr.html", "classamrex_1_1Amr" ],
      [ "AmrAssignGrid", "structamrex_1_1AmrAssignGrid.html", "structamrex_1_1AmrAssignGrid" ],
      [ "AmrCore", "classamrex_1_1AmrCore.html", "classamrex_1_1AmrCore" ],
      [ "AMRErrorTag", "classamrex_1_1AMRErrorTag.html", "classamrex_1_1AMRErrorTag" ],
      [ "AMRErrorTagInfo", "structamrex_1_1AMRErrorTagInfo.html", "structamrex_1_1AMRErrorTagInfo" ],
      [ "AMReX", "classamrex_1_1AMReX.html", "classamrex_1_1AMReX" ],
      [ "AmrInfo", "structamrex_1_1AmrInfo.html", "structamrex_1_1AmrInfo" ],
      [ "AmrLevel", "classamrex_1_1AmrLevel.html", "classamrex_1_1AmrLevel" ],
      [ "AmrMesh", "classamrex_1_1AmrMesh.html", "classamrex_1_1AmrMesh" ],
      [ "AmrParGDB", "classamrex_1_1AmrParGDB.html", "classamrex_1_1AmrParGDB" ],
      [ "AmrParticleContainer_impl", "classamrex_1_1AmrParticleContainer__impl.html", "classamrex_1_1AmrParticleContainer__impl" ],
      [ "AmrParticleLocator", "classamrex_1_1AmrParticleLocator.html", "classamrex_1_1AmrParticleLocator" ],
      [ "AmrTracerParticleContainer", "classamrex_1_1AmrTracerParticleContainer.html", "classamrex_1_1AmrTracerParticleContainer" ],
      [ "Any", "classamrex_1_1Any.html", "classamrex_1_1Any" ],
      [ "Arena", "classamrex_1_1Arena.html", "classamrex_1_1Arena" ],
      [ "ArenaAllocator", "classamrex_1_1ArenaAllocator.html", null ],
      [ "ArenaAllocatorBase", "structamrex_1_1ArenaAllocatorBase.html", "structamrex_1_1ArenaAllocatorBase" ],
      [ "ArenaInfo", "structamrex_1_1ArenaInfo.html", "structamrex_1_1ArenaInfo" ],
      [ "ArenaWrapper", "structamrex_1_1ArenaWrapper.html", "structamrex_1_1ArenaWrapper" ],
      [ "Array1D", "structamrex_1_1Array1D.html", "structamrex_1_1Array1D" ],
      [ "Array2D", "structamrex_1_1Array2D.html", "structamrex_1_1Array2D" ],
      [ "Array3D", "structamrex_1_1Array3D.html", "structamrex_1_1Array3D" ],
      [ "Array4BoxOffsetTag", "structamrex_1_1Array4BoxOffsetTag.html", "structamrex_1_1Array4BoxOffsetTag" ],
      [ "Array4BoxOrientationTag", "structamrex_1_1Array4BoxOrientationTag.html", "structamrex_1_1Array4BoxOrientationTag" ],
      [ "Array4BoxTag", "structamrex_1_1Array4BoxTag.html", "structamrex_1_1Array4BoxTag" ],
      [ "Array4BoxValTag", "structamrex_1_1Array4BoxValTag.html", "structamrex_1_1Array4BoxValTag" ],
      [ "Array4CopyTag", "structamrex_1_1Array4CopyTag.html", "structamrex_1_1Array4CopyTag" ],
      [ "Array4MaskCopyTag", "structamrex_1_1Array4MaskCopyTag.html", "structamrex_1_1Array4MaskCopyTag" ],
      [ "Array4PairTag", "structamrex_1_1Array4PairTag.html", "structamrex_1_1Array4PairTag" ],
      [ "Array4Tag", "structamrex_1_1Array4Tag.html", "structamrex_1_1Array4Tag" ],
      [ "ArrayND", "structamrex_1_1ArrayND.html", "structamrex_1_1ArrayND" ],
      [ "ArrayOfStructs", "classamrex_1_1ArrayOfStructs.html", "classamrex_1_1ArrayOfStructs" ],
      [ "AssignGrid", "structamrex_1_1AssignGrid.html", "structamrex_1_1AssignGrid" ],
      [ "AssignGridFilter", "structamrex_1_1AssignGridFilter.html", "structamrex_1_1AssignGridFilter" ],
      [ "AsyncArenaAllocator", "classamrex_1_1AsyncArenaAllocator.html", null ],
      [ "AsyncArenaWrapper", "structamrex_1_1AsyncArenaWrapper.html", "structamrex_1_1AsyncArenaWrapper" ],
      [ "AuxBoundaryData", "classamrex_1_1AuxBoundaryData.html", "classamrex_1_1AuxBoundaryData" ],
      [ "BackgroundThread", "classamrex_1_1BackgroundThread.html", "classamrex_1_1BackgroundThread" ],
      [ "BArena", "classamrex_1_1BArena.html", "classamrex_1_1BArena" ],
      [ "BaseFab", "classamrex_1_1BaseFab.html", "classamrex_1_1BaseFab" ],
      [ "BCRec", "classamrex_1_1BCRec.html", "classamrex_1_1BCRec" ],
      [ "BinIterator", "structamrex_1_1BinIterator.html", "structamrex_1_1BinIterator" ],
      [ "BinMapper", "structamrex_1_1BinMapper.html", "structamrex_1_1BinMapper" ],
      [ "BLBackTrace", "structamrex_1_1BLBackTrace.html", "structamrex_1_1BLBackTrace" ],
      [ "BLBTer", "classamrex_1_1BLBTer.html", "classamrex_1_1BLBTer" ],
      [ "BlockMutex", "structamrex_1_1BlockMutex.html", "structamrex_1_1BlockMutex" ],
      [ "BLProfiler", "classamrex_1_1BLProfiler.html", "classamrex_1_1BLProfiler" ],
      [ "BndryDataT", "classamrex_1_1BndryDataT.html", "classamrex_1_1BndryDataT" ],
      [ "BndryFuncArray", "classamrex_1_1BndryFuncArray.html", "classamrex_1_1BndryFuncArray" ],
      [ "BndryRegisterT", "classamrex_1_1BndryRegisterT.html", "classamrex_1_1BndryRegisterT" ],
      [ "BoundCond", "classamrex_1_1BoundCond.html", "classamrex_1_1BoundCond" ],
      [ "BoxArray", "classamrex_1_1BoxArray.html", "classamrex_1_1BoxArray" ],
      [ "BoxConverter", "classamrex_1_1BoxConverter.html", "classamrex_1_1BoxConverter" ],
      [ "BoxDomain", "classamrex_1_1BoxDomain.html", "classamrex_1_1BoxDomain" ],
      [ "BoxIndexerND", "structamrex_1_1BoxIndexerND.html", "structamrex_1_1BoxIndexerND" ],
      [ "BoxIndexerND< 1 >", "structamrex_1_1BoxIndexerND_3_011_01_4.html", "structamrex_1_1BoxIndexerND_3_011_01_4" ],
      [ "BoxIteratorND", "classamrex_1_1BoxIteratorND.html", "classamrex_1_1BoxIteratorND" ],
      [ "BoxList", "classamrex_1_1BoxList.html", "classamrex_1_1BoxList" ],
      [ "BoxND", "classamrex_1_1BoxND.html", "classamrex_1_1BoxND" ],
      [ "CArena", "classamrex_1_1CArena.html", "classamrex_1_1CArena" ],
      [ "CellBilinear", "classamrex_1_1CellBilinear.html", "classamrex_1_1CellBilinear" ],
      [ "CellConservativeLinear", "classamrex_1_1CellConservativeLinear.html", "classamrex_1_1CellConservativeLinear" ],
      [ "CellConservativeProtected", "classamrex_1_1CellConservativeProtected.html", "classamrex_1_1CellConservativeProtected" ],
      [ "CellConservativeQuartic", "classamrex_1_1CellConservativeQuartic.html", "classamrex_1_1CellConservativeQuartic" ],
      [ "CellData", "structamrex_1_1CellData.html", "structamrex_1_1CellData" ],
      [ "CellIndexEnum", "structamrex_1_1CellIndexEnum.html", "structamrex_1_1CellIndexEnum" ],
      [ "CellQuadratic", "classamrex_1_1CellQuadratic.html", "classamrex_1_1CellQuadratic" ],
      [ "CellQuartic", "classamrex_1_1CellQuartic.html", "classamrex_1_1CellQuartic" ],
      [ "Cluster", "classamrex_1_1Cluster.html", "classamrex_1_1Cluster" ],
      [ "ClusterList", "classamrex_1_1ClusterList.html", "classamrex_1_1ClusterList" ],
      [ "CommRecvBufTag", "structamrex_1_1CommRecvBufTag.html", "structamrex_1_1CommRecvBufTag" ],
      [ "CommSendBufTag", "structamrex_1_1CommSendBufTag.html", "structamrex_1_1CommSendBufTag" ],
      [ "CompileTimeOptions", "structamrex_1_1CompileTimeOptions.html", "structamrex_1_1CompileTimeOptions" ],
      [ "Conjunction", "structamrex_1_1Conjunction.html", null ],
      [ "Conjunction< B1 >", "structamrex_1_1Conjunction_3_01B1_01_4.html", null ],
      [ "Conjunction< B1, Bn... >", "structamrex_1_1Conjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ],
      [ "ConstParticleCPUWrapper", "structamrex_1_1ConstParticleCPUWrapper.html", "structamrex_1_1ConstParticleCPUWrapper" ],
      [ "ConstParticleIDWrapper", "structamrex_1_1ConstParticleIDWrapper.html", "structamrex_1_1ConstParticleIDWrapper" ],
      [ "ConstParticleTileData", "structamrex_1_1ConstParticleTileData.html", "structamrex_1_1ConstParticleTileData" ],
      [ "ConstSoAParticle", "structamrex_1_1ConstSoAParticle.html", "structamrex_1_1ConstSoAParticle" ],
      [ "CoordSys", "classamrex_1_1CoordSys.html", "classamrex_1_1CoordSys" ],
      [ "CpuBndryFuncFab", "classamrex_1_1CpuBndryFuncFab.html", "classamrex_1_1CpuBndryFuncFab" ],
      [ "CutFab", "classamrex_1_1CutFab.html", "classamrex_1_1CutFab" ],
      [ "DataAllocator", "structamrex_1_1DataAllocator.html", "structamrex_1_1DataAllocator" ],
      [ "DataDeleter", "structamrex_1_1DataDeleter.html", "structamrex_1_1DataDeleter" ],
      [ "DataLayoutPolicy", "structamrex_1_1DataLayoutPolicy.html", null ],
      [ "DataLayoutPolicy< ContainerType, ParticleType< Types... >, DataLayout::AoS >", "structamrex_1_1DataLayoutPolicy_3_01ContainerType_00_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1AoS_01_4.html", "structamrex_1_1DataLayoutPolicy_3_01ContainerType_00_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1AoS_01_4" ],
      [ "DataLayoutPolicy< ContainerType, ParticleType< Types... >, DataLayout::SoA >", "structamrex_1_1DataLayoutPolicy_3_01ContainerType_00_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1SoA_01_4.html", "structamrex_1_1DataLayoutPolicy_3_01ContainerType_00_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1SoA_01_4" ],
      [ "DataLayoutPolicyRaw", "structamrex_1_1DataLayoutPolicyRaw.html", null ],
      [ "DataLayoutPolicyRaw< ParticleType< Types... >, DataLayout::AoS >", "structamrex_1_1DataLayoutPolicyRaw_3_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1AoS_01_4.html", "structamrex_1_1DataLayoutPolicyRaw_3_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1AoS_01_4" ],
      [ "DataLayoutPolicyRaw< ParticleType< Types... >, DataLayout::SoA >", "structamrex_1_1DataLayoutPolicyRaw_3_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1SoA_01_4.html", "structamrex_1_1DataLayoutPolicyRaw_3_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1SoA_01_4" ],
      [ "DefaultAssignor", "structamrex_1_1DefaultAssignor.html", "structamrex_1_1DefaultAssignor" ],
      [ "DefaultFabFactory", "classamrex_1_1DefaultFabFactory.html", "classamrex_1_1DefaultFabFactory" ],
      [ "DefinitelyNotHostRunnable", "structamrex_1_1DefinitelyNotHostRunnable.html", null ],
      [ "DenseBinIteratorFactory", "structamrex_1_1DenseBinIteratorFactory.html", "structamrex_1_1DenseBinIteratorFactory" ],
      [ "DenseBins", "classamrex_1_1DenseBins.html", "classamrex_1_1DenseBins" ],
      [ "DeriveList", "classamrex_1_1DeriveList.html", "classamrex_1_1DeriveList" ],
      [ "DeriveRec", "classamrex_1_1DeriveRec.html", "classamrex_1_1DeriveRec" ],
      [ "DescriptorList", "classamrex_1_1DescriptorList.html", "classamrex_1_1DescriptorList" ],
      [ "DestComp", "structamrex_1_1DestComp.html", "structamrex_1_1DestComp" ],
      [ "DeviceArenaAllocator", "classamrex_1_1DeviceArenaAllocator.html", null ],
      [ "DeviceArenaWrapper", "structamrex_1_1DeviceArenaWrapper.html", "structamrex_1_1DeviceArenaWrapper" ],
      [ "Dim3", "structamrex_1_1Dim3.html", "structamrex_1_1Dim3" ],
      [ "Disjunction", "structamrex_1_1Disjunction.html", null ],
      [ "Disjunction< B1 >", "structamrex_1_1Disjunction_3_01B1_01_4.html", null ],
      [ "Disjunction< B1, Bn... >", "structamrex_1_1Disjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ],
      [ "distFcnElement2d", "classamrex_1_1distFcnElement2d.html", "classamrex_1_1distFcnElement2d" ],
      [ "DistributionMapping", "classamrex_1_1DistributionMapping.html", "classamrex_1_1DistributionMapping" ],
      [ "Divides", "structamrex_1_1Divides.html", "structamrex_1_1Divides" ],
      [ "DynamicTiling", "structamrex_1_1DynamicTiling.html", "structamrex_1_1DynamicTiling" ],
      [ "EBCellConservativeLinear", "classamrex_1_1EBCellConservativeLinear.html", "classamrex_1_1EBCellConservativeLinear" ],
      [ "EBCellFlag", "classamrex_1_1EBCellFlag.html", "classamrex_1_1EBCellFlag" ],
      [ "EBCellFlagFab", "classamrex_1_1EBCellFlagFab.html", "classamrex_1_1EBCellFlagFab" ],
      [ "EBData", "structamrex_1_1EBData.html", "structamrex_1_1EBData" ],
      [ "EBDataCollection", "classamrex_1_1EBDataCollection.html", "classamrex_1_1EBDataCollection" ],
      [ "EBFArrayBox", "classamrex_1_1EBFArrayBox.html", "classamrex_1_1EBFArrayBox" ],
      [ "EBFArrayBoxFactory", "classamrex_1_1EBFArrayBoxFactory.html", "classamrex_1_1EBFArrayBoxFactory" ],
      [ "EBFluxRegister", "classamrex_1_1EBFluxRegister.html", "classamrex_1_1EBFluxRegister" ],
      [ "EBMFCellConsLinInterp", "classamrex_1_1EBMFCellConsLinInterp.html", "classamrex_1_1EBMFCellConsLinInterp" ],
      [ "EBToPVD", "classamrex_1_1EBToPVD.html", "classamrex_1_1EBToPVD" ],
      [ "EdgeFluxRegister", "classamrex_1_1EdgeFluxRegister.html", "classamrex_1_1EdgeFluxRegister" ],
      [ "ErrorList", "classamrex_1_1ErrorList.html", "classamrex_1_1ErrorList" ],
      [ "ErrorRec", "classamrex_1_1ErrorRec.html", "classamrex_1_1ErrorRec" ],
      [ "expect", "classamrex_1_1expect.html", "classamrex_1_1expect" ],
      [ "FabArray", "classamrex_1_1FabArray.html", "classamrex_1_1FabArray" ],
      [ "FabArrayBase", "classamrex_1_1FabArrayBase.html", "classamrex_1_1FabArrayBase" ],
      [ "FabArrayCopyDescriptor", "classamrex_1_1FabArrayCopyDescriptor.html", "classamrex_1_1FabArrayCopyDescriptor" ],
      [ "FabArrayId", "classamrex_1_1FabArrayId.html", "classamrex_1_1FabArrayId" ],
      [ "FabCopyDescriptor", "structamrex_1_1FabCopyDescriptor.html", "structamrex_1_1FabCopyDescriptor" ],
      [ "FabCopyTag", "structamrex_1_1FabCopyTag.html", "structamrex_1_1FabCopyTag" ],
      [ "FabDataType", "structamrex_1_1FabDataType.html", null ],
      [ "FabDataType< T, std::enable_if_t< IsMultiFabLike_v< T > > >", "structamrex_1_1FabDataType_3_01T_00_01std_1_1enable__if__t_3_01IsMultiFabLike__v_3_01T_01_4_01_4_01_4.html", "structamrex_1_1FabDataType_3_01T_00_01std_1_1enable__if__t_3_01IsMultiFabLike__v_3_01T_01_4_01_4_01_4" ],
      [ "FabDataType< T, std::enable_if_t< IsMultiFabLike_v< typename T::value_type > > >", "structamrex_1_1FabDataType_3_01T_00_01std_1_1enable__if__t_3_01IsMultiFabLike__v_3_01typename_01T_1_1value__type_01_4_01_4_01_4.html", "structamrex_1_1FabDataType_3_01T_00_01std_1_1enable__if__t_3_01IsMultiFabLike__v_3_01typename_01T_1_1value__type_01_4_01_4_01_4" ],
      [ "FabFactory", "classamrex_1_1FabFactory.html", "classamrex_1_1FabFactory" ],
      [ "FabFillNoOp", "structamrex_1_1FabFillNoOp.html", "structamrex_1_1FabFillNoOp" ],
      [ "FabInfo", "structamrex_1_1FabInfo.html", "structamrex_1_1FabInfo" ],
      [ "FABio", "classamrex_1_1FABio.html", "classamrex_1_1FABio" ],
      [ "FABio_8bit", "classamrex_1_1FABio__8bit.html", "classamrex_1_1FABio__8bit" ],
      [ "FABio_ascii", "classamrex_1_1FABio__ascii.html", "classamrex_1_1FABio__ascii" ],
      [ "FABio_binary", "classamrex_1_1FABio__binary.html", "classamrex_1_1FABio__binary" ],
      [ "FabSetIter", "classamrex_1_1FabSetIter.html", "classamrex_1_1FabSetIter" ],
      [ "FabSetT", "classamrex_1_1FabSetT.html", "classamrex_1_1FabSetT" ],
      [ "FaceConservativeLinear", "classamrex_1_1FaceConservativeLinear.html", "classamrex_1_1FaceConservativeLinear" ],
      [ "FaceDivFree", "classamrex_1_1FaceDivFree.html", "classamrex_1_1FaceDivFree" ],
      [ "FaceLinear", "classamrex_1_1FaceLinear.html", "classamrex_1_1FaceLinear" ],
      [ "FArrayBox", "classamrex_1_1FArrayBox.html", "classamrex_1_1FArrayBox" ],
      [ "FatPtr", "structamrex_1_1FatPtr.html", "structamrex_1_1FatPtr" ],
      [ "FBData", "structamrex_1_1FBData.html", "structamrex_1_1FBData" ],
      [ "FEIntegrator", "classamrex_1_1FEIntegrator.html", "classamrex_1_1FEIntegrator" ],
      [ "FillBoxId", "classamrex_1_1FillBoxId.html", "classamrex_1_1FillBoxId" ],
      [ "FillPatcher", "classamrex_1_1FillPatcher.html", "classamrex_1_1FillPatcher" ],
      [ "FillPatchIterator", "classamrex_1_1FillPatchIterator.html", "classamrex_1_1FillPatchIterator" ],
      [ "FillPatchIteratorHelper", "classamrex_1_1FillPatchIteratorHelper.html", "classamrex_1_1FillPatchIteratorHelper" ],
      [ "FilterPositiveID", "structamrex_1_1FilterPositiveID.html", "structamrex_1_1FilterPositiveID" ],
      [ "FilterVirt", "structamrex_1_1FilterVirt.html", "structamrex_1_1FilterVirt" ],
      [ "FluxRegister", "classamrex_1_1FluxRegister.html", "classamrex_1_1FluxRegister" ],
      [ "ForkJoin", "classamrex_1_1ForkJoin.html", "classamrex_1_1ForkJoin" ],
      [ "FPC", "classamrex_1_1FPC.html", "classamrex_1_1FPC" ],
      [ "Geometry", "classamrex_1_1Geometry.html", "classamrex_1_1Geometry" ],
      [ "GeometryData", "structamrex_1_1GeometryData.html", "structamrex_1_1GeometryData" ],
      [ "GetBucket", "structamrex_1_1GetBucket.html", "structamrex_1_1GetBucket" ],
      [ "GetParticleBin", "structamrex_1_1GetParticleBin.html", "structamrex_1_1GetParticleBin" ],
      [ "GetPID", "structamrex_1_1GetPID.html", "structamrex_1_1GetPID" ],
      [ "GetSendBufferOffset", "structamrex_1_1GetSendBufferOffset.html", "structamrex_1_1GetSendBufferOffset" ],
      [ "GMRES", "classamrex_1_1GMRES.html", "classamrex_1_1GMRES" ],
      [ "GMRES_MV", "classamrex_1_1GMRES__MV.html", "classamrex_1_1GMRES__MV" ],
      [ "GMRESMLMGT", "classamrex_1_1GMRESMLMGT.html", "classamrex_1_1GMRESMLMGT" ],
      [ "GPUable", "structamrex_1_1GPUable.html", null ],
      [ "GpuArray", "structamrex_1_1GpuArray.html", "structamrex_1_1GpuArray" ],
      [ "GpuBndryFuncFab", "classamrex_1_1GpuBndryFuncFab.html", "classamrex_1_1GpuBndryFuncFab" ],
      [ "GpuComplex", "structamrex_1_1GpuComplex.html", "structamrex_1_1GpuComplex" ],
      [ "GpuTuple", "classamrex_1_1GpuTuple.html", "classamrex_1_1GpuTuple" ],
      [ "GpuTupleElement", "structamrex_1_1GpuTupleElement.html", null ],
      [ "GpuTupleElement< 0, GpuTuple< Head, Tail... > >", "structamrex_1_1GpuTupleElement_3_010_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4.html", "structamrex_1_1GpuTupleElement_3_010_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4" ],
      [ "GpuTupleElement< I, GpuTuple< Head, Tail... > >", "structamrex_1_1GpuTupleElement_3_01I_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4.html", null ],
      [ "GpuTupleSize", "structamrex_1_1GpuTupleSize.html", null ],
      [ "GpuTupleSize< GpuTuple< Ts... > >", "structamrex_1_1GpuTupleSize_3_01GpuTuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "HasAtomicAdd", "structamrex_1_1HasAtomicAdd.html", null ],
      [ "HasAtomicAdd< double >", "structamrex_1_1HasAtomicAdd_3_01double_01_4.html", null ],
      [ "HasAtomicAdd< float >", "structamrex_1_1HasAtomicAdd_3_01float_01_4.html", null ],
      [ "HasAtomicAdd< int >", "structamrex_1_1HasAtomicAdd_3_01int_01_4.html", null ],
      [ "HasAtomicAdd< long >", "structamrex_1_1HasAtomicAdd_3_01long_01_4.html", null ],
      [ "HasAtomicAdd< unsigned int >", "structamrex_1_1HasAtomicAdd_3_01unsigned_01int_01_4.html", null ],
      [ "HasAtomicAdd< unsigned long long >", "structamrex_1_1HasAtomicAdd_3_01unsigned_01long_01long_01_4.html", null ],
      [ "HasMultiComp", "structamrex_1_1HasMultiComp.html", null ],
      [ "HasMultiComp< B, std::enable_if_t< B().size() >=1 >", "structamrex_1_1HasMultiComp_3_01B_00_01std_1_1enable__if__t_3_01B_07_08_8size_07_08_01_4_0a1_01_4.html", null ],
      [ "Hypre", "classamrex_1_1Hypre.html", "classamrex_1_1Hypre" ],
      [ "HypreABecLap", "classamrex_1_1HypreABecLap.html", "classamrex_1_1HypreABecLap" ],
      [ "HypreABecLap2", "classamrex_1_1HypreABecLap2.html", "classamrex_1_1HypreABecLap2" ],
      [ "HypreABecLap3", "classamrex_1_1HypreABecLap3.html", "classamrex_1_1HypreABecLap3" ],
      [ "HypreIJIface", "classamrex_1_1HypreIJIface.html", "classamrex_1_1HypreIJIface" ],
      [ "HypreMLABecLap", "classamrex_1_1HypreMLABecLap.html", "classamrex_1_1HypreMLABecLap" ],
      [ "HypreNodeLap", "classamrex_1_1HypreNodeLap.html", "classamrex_1_1HypreNodeLap" ],
      [ "HypreSolver", "classamrex_1_1HypreSolver.html", "classamrex_1_1HypreSolver" ],
      [ "IArrayBox", "classamrex_1_1IArrayBox.html", "classamrex_1_1IArrayBox" ],
      [ "IFABio", "classamrex_1_1IFABio.html", "classamrex_1_1IFABio" ],
      [ "iMultiFab", "classamrex_1_1iMultiFab.html", "classamrex_1_1iMultiFab" ],
      [ "IndexTypeND", "classamrex_1_1IndexTypeND.html", "classamrex_1_1IndexTypeND" ],
      [ "IntDescriptor", "classamrex_1_1IntDescriptor.html", "classamrex_1_1IntDescriptor" ],
      [ "IntegratorBase", "classamrex_1_1IntegratorBase.html", "classamrex_1_1IntegratorBase" ],
      [ "IntegratorOps", "structamrex_1_1IntegratorOps.html", null ],
      [ "IntegratorOps< T, std::enable_if_t< std::is_base_of_v< amrex::ParticleContainerBase, T > > >", "structamrex_1_1IntegratorOps_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01amre4a8b722c501826628c0ce0b931e91134.html", "structamrex_1_1IntegratorOps_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01amre4a8b722c501826628c0ce0b931e91134" ],
      [ "IntegratorOps< T, std::enable_if_t< std::is_same_v< amrex::MultiFab, T > > >", "structamrex_1_1IntegratorOps_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__same__v_3_01amrex_1_1MultiFab_00_01T_01_4_01_4_01_4.html", "structamrex_1_1IntegratorOps_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__same__v_3_01amrex_1_1MultiFab_00_01T_01_4_01_4_01_4" ],
      [ "IntegratorOps< T, std::enable_if_t< std::is_same_v< amrex::Vector< amrex::MultiFab >, T > > >", "structamrex_1_1IntegratorOps_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__same__v_3_01amrex_1_ad28940895bb617a00768ed755461047.html", "structamrex_1_1IntegratorOps_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__same__v_3_01amrex_1_ad28940895bb617a00768ed755461047" ],
      [ "InterpBase", "classamrex_1_1InterpBase.html", "classamrex_1_1InterpBase" ],
      [ "InterpBndryDataT", "classamrex_1_1InterpBndryDataT.html", "classamrex_1_1InterpBndryDataT" ],
      [ "InterpFaceRegister", "classamrex_1_1InterpFaceRegister.html", "classamrex_1_1InterpFaceRegister" ],
      [ "Interpolater", "classamrex_1_1Interpolater.html", "classamrex_1_1Interpolater" ],
      [ "InterpolaterBoxCoarsener", "classamrex_1_1InterpolaterBoxCoarsener.html", "classamrex_1_1InterpolaterBoxCoarsener" ],
      [ "IntVectND", "classamrex_1_1IntVectND.html", "classamrex_1_1IntVectND" ],
      [ "IOFormatSaver", "classamrex_1_1IOFormatSaver.html", "classamrex_1_1IOFormatSaver" ],
      [ "IParser", "classamrex_1_1IParser.html", "classamrex_1_1IParser" ],
      [ "IParserExecutor", "structamrex_1_1IParserExecutor.html", "structamrex_1_1IParserExecutor" ],
      [ "is_soa_particle", "structamrex_1_1is__soa__particle.html", null ],
      [ "IsAddAssignable", "structamrex_1_1IsAddAssignable.html", null ],
      [ "IsAddAssignable< T, std::void_t< decltype(std::declval< T & >()+=std::declval< T >())> >", "structamrex_1_1IsAddAssignable_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01T_01_7db52e59378635f71f087c923eca3035.html", null ],
      [ "IsAlgVector", "structamrex_1_1IsAlgVector.html", null ],
      [ "IsAlgVector< V, std::enable_if_t< std::is_same_v< AlgVector< typename V::value_type, typename V::allocator_type >, V > > >", "structamrex_1_1IsAlgVector_3_01V_00_01std_1_1enable__if__t_3_01std_1_1is__same__v_3_01AlgVector_b40b2816d789aedc6f50e789de689e7c.html", null ],
      [ "IsArenaAllocator", "structamrex_1_1IsArenaAllocator.html", null ],
      [ "IsArenaAllocator< T, std::enable_if_t< std::is_base_of_v< ArenaAllocatorBase< typename T::value_type, typename T::arena_wrapper_type >, T > > >", "structamrex_1_1IsArenaAllocator_3_01T_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01A3a0553dd1fe92c460e3e2edf71ec41f7.html", null ],
      [ "IsBaseFab", "structamrex_1_1IsBaseFab.html", null ],
      [ "IsBaseFab< D, std::enable_if_t< std::is_base_of_v< BaseFab< typename D::value_type >, D > > >", "structamrex_1_1IsBaseFab_3_01D_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01BaseFab_e919207a96f4ea216943219981685bdd.html", null ],
      [ "IsCallable", "structamrex_1_1IsCallable.html", null ],
      [ "IsCallableR", "structamrex_1_1IsCallableR.html", null ],
      [ "IsConvertible", "structamrex_1_1IsConvertible.html", "structamrex_1_1IsConvertible" ],
      [ "IsFabArray", "structamrex_1_1IsFabArray.html", null ],
      [ "IsFabArray< D, std::enable_if_t< std::is_base_of_v< FabArray< typename D::FABType::value_type >, D > > >", "structamrex_1_1IsFabArray_3_01D_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01FabArrae7a3c5405f8dbf92bbb678a85384720d.html", null ],
      [ "IsMultiFabIterator", "structamrex_1_1IsMultiFabIterator.html", null ],
      [ "IsMultiFabLike", "structamrex_1_1IsMultiFabLike.html", null ],
      [ "IsMultiFabLike< M, std::enable_if_t< IsFabArray_v< M > &&IsBaseFab_v< typename M::fab_type > > >", "structamrex_1_1IsMultiFabLike_3_01M_00_01std_1_1enable__if__t_3_01IsFabArray__v_3_01M_01_4_01_6_1b79f12933d87e47a77b2c36839b7d8d.html", null ],
      [ "IsNarrowingConversion", "structamrex_1_1IsNarrowingConversion.html", null ],
      [ "IsParticleContainer", "structamrex_1_1IsParticleContainer.html", null ],
      [ "IsParticleIterator", "structamrex_1_1IsParticleIterator.html", null ],
      [ "IsPolymorphicArenaAllocator", "structamrex_1_1IsPolymorphicArenaAllocator.html", null ],
      [ "IsPolymorphicArenaAllocator< PolymorphicArenaAllocator< T > >", "structamrex_1_1IsPolymorphicArenaAllocator_3_01PolymorphicArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "IsStoreAtomic", "structamrex_1_1IsStoreAtomic.html", null ],
      [ "IsStoreAtomic< EBCellFlag >", "structamrex_1_1IsStoreAtomic_3_01EBCellFlag_01_4.html", null ],
      [ "JacobiSmoother", "classamrex_1_1JacobiSmoother.html", "classamrex_1_1JacobiSmoother" ],
      [ "KeepValidFilter", "structamrex_1_1KeepValidFilter.html", "structamrex_1_1KeepValidFilter" ],
      [ "LayoutData", "classamrex_1_1LayoutData.html", "classamrex_1_1LayoutData" ],
      [ "LevelBld", "classamrex_1_1LevelBld.html", "classamrex_1_1LevelBld" ],
      [ "LineDistFcnElement2d", "classamrex_1_1LineDistFcnElement2d.html", "classamrex_1_1LineDistFcnElement2d" ],
      [ "LinOpEnumType", "structamrex_1_1LinOpEnumType.html", "structamrex_1_1LinOpEnumType" ],
      [ "LogicalAnd", "structamrex_1_1LogicalAnd.html", "structamrex_1_1LogicalAnd" ],
      [ "LogicalOr", "structamrex_1_1LogicalOr.html", "structamrex_1_1LogicalOr" ],
      [ "LPInfo", "structamrex_1_1LPInfo.html", "structamrex_1_1LPInfo" ],
      [ "LUSolver", "classamrex_1_1LUSolver.html", "classamrex_1_1LUSolver" ],
      [ "make_particle", "structamrex_1_1make__particle.html", "structamrex_1_1make__particle" ],
      [ "make_particle< T_ParticleType, std::enable_if_t< is_soa_particle< T_ParticleType >::value > >", "structamrex_1_1make__particle_3_01T__ParticleType_00_01std_1_1enable__if__t_3_01is__soa__particlc68a74db21db66e00f623afe9a792145.html", "structamrex_1_1make__particle_3_01T__ParticleType_00_01std_1_1enable__if__t_3_01is__soa__particlc68a74db21db66e00f623afe9a792145" ],
      [ "ManagedArenaAllocator", "classamrex_1_1ManagedArenaAllocator.html", null ],
      [ "ManagedArenaWrapper", "structamrex_1_1ManagedArenaWrapper.html", "structamrex_1_1ManagedArenaWrapper" ],
      [ "Mask", "classamrex_1_1Mask.html", "classamrex_1_1Mask" ],
      [ "Maximum", "structamrex_1_1Maximum.html", "structamrex_1_1Maximum" ],
      [ "MaybeDeviceRunnable", "structamrex_1_1MaybeDeviceRunnable.html", null ],
      [ "MaybeHostDeviceRunnable", "structamrex_1_1MaybeHostDeviceRunnable.html", null ],
      [ "MemProfiler", "classamrex_1_1MemProfiler.html", "classamrex_1_1MemProfiler" ],
      [ "MemStat", "structamrex_1_1MemStat.html", "structamrex_1_1MemStat" ],
      [ "MFCellBilinear", "classamrex_1_1MFCellBilinear.html", "classamrex_1_1MFCellBilinear" ],
      [ "MFCellConsLinInterp", "classamrex_1_1MFCellConsLinInterp.html", "classamrex_1_1MFCellConsLinInterp" ],
      [ "MFCellConsLinMinmaxLimitInterp", "classamrex_1_1MFCellConsLinMinmaxLimitInterp.html", "classamrex_1_1MFCellConsLinMinmaxLimitInterp" ],
      [ "MFInfo", "structamrex_1_1MFInfo.html", "structamrex_1_1MFInfo" ],
      [ "MFInterpolater", "classamrex_1_1MFInterpolater.html", "classamrex_1_1MFInterpolater" ],
      [ "MFIter", "classamrex_1_1MFIter.html", "classamrex_1_1MFIter" ],
      [ "MFItInfo", "structamrex_1_1MFItInfo.html", "structamrex_1_1MFItInfo" ],
      [ "MFNodeBilinear", "classamrex_1_1MFNodeBilinear.html", "classamrex_1_1MFNodeBilinear" ],
      [ "MFPCInterp", "classamrex_1_1MFPCInterp.html", "classamrex_1_1MFPCInterp" ],
      [ "Minimum", "structamrex_1_1Minimum.html", "structamrex_1_1Minimum" ],
      [ "Minus", "structamrex_1_1Minus.html", "structamrex_1_1Minus" ],
      [ "MLABecLaplacianT", "classamrex_1_1MLABecLaplacianT.html", "classamrex_1_1MLABecLaplacianT" ],
      [ "MLALaplacianT", "classamrex_1_1MLALaplacianT.html", "classamrex_1_1MLALaplacianT" ],
      [ "MLCellABecLapT", "classamrex_1_1MLCellABecLapT.html", "classamrex_1_1MLCellABecLapT" ],
      [ "MLCellLinOpT", "classamrex_1_1MLCellLinOpT.html", "classamrex_1_1MLCellLinOpT" ],
      [ "MLCGSolverT", "classamrex_1_1MLCGSolverT.html", "classamrex_1_1MLCGSolverT" ],
      [ "MLCurlCurl", "classamrex_1_1MLCurlCurl.html", "classamrex_1_1MLCurlCurl" ],
      [ "MLEBABecLap", "classamrex_1_1MLEBABecLap.html", "classamrex_1_1MLEBABecLap" ],
      [ "MLEBNodeFDLaplacian", "classamrex_1_1MLEBNodeFDLaplacian.html", "classamrex_1_1MLEBNodeFDLaplacian" ],
      [ "MLEBTensorOp", "classamrex_1_1MLEBTensorOp.html", "classamrex_1_1MLEBTensorOp" ],
      [ "MLLinOpT", "classamrex_1_1MLLinOpT.html", "classamrex_1_1MLLinOpT" ],
      [ "MLMGABCEBTag", "structamrex_1_1MLMGABCEBTag.html", null ],
      [ "MLMGBndryT", "classamrex_1_1MLMGBndryT.html", "classamrex_1_1MLMGBndryT" ],
      [ "MLMGT", "classamrex_1_1MLMGT.html", "classamrex_1_1MLMGT" ],
      [ "MLNodeABecLaplacian", "classamrex_1_1MLNodeABecLaplacian.html", "classamrex_1_1MLNodeABecLaplacian" ],
      [ "MLNodeLaplacian", "classamrex_1_1MLNodeLaplacian.html", "classamrex_1_1MLNodeLaplacian" ],
      [ "MLNodeLinOp", "classamrex_1_1MLNodeLinOp.html", "classamrex_1_1MLNodeLinOp" ],
      [ "MLNodeTensorLaplacian", "classamrex_1_1MLNodeTensorLaplacian.html", "classamrex_1_1MLNodeTensorLaplacian" ],
      [ "MLPoissonT", "classamrex_1_1MLPoissonT.html", "classamrex_1_1MLPoissonT" ],
      [ "MLTensorOp", "classamrex_1_1MLTensorOp.html", "classamrex_1_1MLTensorOp" ],
      [ "MultiArray4", "structamrex_1_1MultiArray4.html", "structamrex_1_1MultiArray4" ],
      [ "MultiCutFab", "classamrex_1_1MultiCutFab.html", "classamrex_1_1MultiCutFab" ],
      [ "MultiFab", "classamrex_1_1MultiFab.html", "classamrex_1_1MultiFab" ],
      [ "MultiFabCopyDescriptor", "classamrex_1_1MultiFabCopyDescriptor.html", "classamrex_1_1MultiFabCopyDescriptor" ],
      [ "MultiMask", "classamrex_1_1MultiMask.html", "classamrex_1_1MultiMask" ],
      [ "MultiMaskIter", "classamrex_1_1MultiMaskIter.html", "classamrex_1_1MultiMaskIter" ],
      [ "Multiplies", "structamrex_1_1Multiplies.html", "structamrex_1_1Multiplies" ],
      [ "NeighborCode", "structamrex_1_1NeighborCode.html", "structamrex_1_1NeighborCode" ],
      [ "NeighborData", "structamrex_1_1NeighborData.html", "structamrex_1_1NeighborData" ],
      [ "NeighborList", "classamrex_1_1NeighborList.html", "classamrex_1_1NeighborList" ],
      [ "NeighborParticleContainer", "classamrex_1_1NeighborParticleContainer.html", "classamrex_1_1NeighborParticleContainer" ],
      [ "Neighbors", "structamrex_1_1Neighbors.html", "structamrex_1_1Neighbors" ],
      [ "NeighborUnpackPolicy", "structamrex_1_1NeighborUnpackPolicy.html", "structamrex_1_1NeighborUnpackPolicy" ],
      [ "NFilesIter", "classamrex_1_1NFilesIter.html", "classamrex_1_1NFilesIter" ],
      [ "NodeBilinear", "classamrex_1_1NodeBilinear.html", "classamrex_1_1NodeBilinear" ],
      [ "NullInterpHook", "structamrex_1_1NullInterpHook.html", "structamrex_1_1NullInterpHook" ],
      [ "NumComps", "structamrex_1_1NumComps.html", "structamrex_1_1NumComps" ],
      [ "OpenBCSolver", "classamrex_1_1OpenBCSolver.html", "classamrex_1_1OpenBCSolver" ],
      [ "Orientation", "classamrex_1_1Orientation.html", "classamrex_1_1Orientation" ],
      [ "OrientationIter", "classamrex_1_1OrientationIter.html", "classamrex_1_1OrientationIter" ],
      [ "ParConstIter_impl", "classamrex_1_1ParConstIter__impl.html", "classamrex_1_1ParConstIter__impl" ],
      [ "PArena", "classamrex_1_1PArena.html", "classamrex_1_1PArena" ],
      [ "ParGDB", "classamrex_1_1ParGDB.html", "classamrex_1_1ParGDB" ],
      [ "ParGDBBase", "classamrex_1_1ParGDBBase.html", "classamrex_1_1ParGDBBase" ],
      [ "ParIter_impl", "classamrex_1_1ParIter__impl.html", "classamrex_1_1ParIter__impl" ],
      [ "ParIterBase_impl", "classamrex_1_1ParIterBase__impl.html", "classamrex_1_1ParIterBase__impl" ],
      [ "ParmParse", "classamrex_1_1ParmParse.html", "classamrex_1_1ParmParse" ],
      [ "Parser", "classamrex_1_1Parser.html", "classamrex_1_1Parser" ],
      [ "ParserExecutor", "structamrex_1_1ParserExecutor.html", "structamrex_1_1ParserExecutor" ],
      [ "Particle", "structamrex_1_1Particle.html", "structamrex_1_1Particle" ],
      [ "ParticleArray", "structamrex_1_1ParticleArray.html", "structamrex_1_1ParticleArray" ],
      [ "ParticleArrayAccessor", "structamrex_1_1ParticleArrayAccessor.html", "structamrex_1_1ParticleArrayAccessor" ],
      [ "ParticleBase", "structamrex_1_1ParticleBase.html", "structamrex_1_1ParticleBase" ],
      [ "ParticleBase< T, 0, 0 >", "structamrex_1_1ParticleBase_3_01T_00_010_00_010_01_4.html", "structamrex_1_1ParticleBase_3_01T_00_010_00_010_01_4" ],
      [ "ParticleBase< T, 0, NInt >", "structamrex_1_1ParticleBase_3_01T_00_010_00_01NInt_01_4.html", "structamrex_1_1ParticleBase_3_01T_00_010_00_01NInt_01_4" ],
      [ "ParticleBase< T, NReal, 0 >", "structamrex_1_1ParticleBase_3_01T_00_01NReal_00_010_01_4.html", "structamrex_1_1ParticleBase_3_01T_00_01NReal_00_010_01_4" ],
      [ "ParticleBufferMap", "classamrex_1_1ParticleBufferMap.html", "classamrex_1_1ParticleBufferMap" ],
      [ "ParticleCommData", "structamrex_1_1ParticleCommData.html", "structamrex_1_1ParticleCommData" ],
      [ "ParticleContainer_impl", "classamrex_1_1ParticleContainer__impl.html", "classamrex_1_1ParticleContainer__impl" ],
      [ "ParticleContainerBase", "classamrex_1_1ParticleContainerBase.html", "classamrex_1_1ParticleContainerBase" ],
      [ "ParticleCopyOp", "structamrex_1_1ParticleCopyOp.html", "structamrex_1_1ParticleCopyOp" ],
      [ "ParticleCopyPlan", "structamrex_1_1ParticleCopyPlan.html", "structamrex_1_1ParticleCopyPlan" ],
      [ "ParticleCPUWrapper", "structamrex_1_1ParticleCPUWrapper.html", "structamrex_1_1ParticleCPUWrapper" ],
      [ "ParticleIDWrapper", "structamrex_1_1ParticleIDWrapper.html", "structamrex_1_1ParticleIDWrapper" ],
      [ "ParticleInitType", "structamrex_1_1ParticleInitType.html", "structamrex_1_1ParticleInitType" ],
      [ "ParticleLocator", "classamrex_1_1ParticleLocator.html", "classamrex_1_1ParticleLocator" ],
      [ "ParticleLocData", "structamrex_1_1ParticleLocData.html", "structamrex_1_1ParticleLocData" ],
      [ "ParticleTile", "structamrex_1_1ParticleTile.html", "structamrex_1_1ParticleTile" ],
      [ "ParticleTileData", "structamrex_1_1ParticleTileData.html", "structamrex_1_1ParticleTileData" ],
      [ "PCData", "structamrex_1_1PCData.html", "structamrex_1_1PCData" ],
      [ "PCInterp", "classamrex_1_1PCInterp.html", "classamrex_1_1PCInterp" ],
      [ "Periodicity", "classamrex_1_1Periodicity.html", "classamrex_1_1Periodicity" ],
      [ "PETScABecLap", "classamrex_1_1PETScABecLap.html", "classamrex_1_1PETScABecLap" ],
      [ "PhysBCFunct", "classamrex_1_1PhysBCFunct.html", "classamrex_1_1PhysBCFunct" ],
      [ "PhysBCFunctNoOp", "classamrex_1_1PhysBCFunctNoOp.html", "classamrex_1_1PhysBCFunctNoOp" ],
      [ "PhysBCFunctUseCoarseGhost", "classamrex_1_1PhysBCFunctUseCoarseGhost.html", "classamrex_1_1PhysBCFunctUseCoarseGhost" ],
      [ "PinnedArenaAllocator", "classamrex_1_1PinnedArenaAllocator.html", null ],
      [ "PinnedArenaWrapper", "structamrex_1_1PinnedArenaWrapper.html", "structamrex_1_1PinnedArenaWrapper" ],
      [ "PlotFileData", "classamrex_1_1PlotFileData.html", "classamrex_1_1PlotFileData" ],
      [ "PlotFileDataImpl", "classamrex_1_1PlotFileDataImpl.html", "classamrex_1_1PlotFileDataImpl" ],
      [ "Plus", "structamrex_1_1Plus.html", "structamrex_1_1Plus" ],
      [ "PODVector", "classamrex_1_1PODVector.html", "classamrex_1_1PODVector" ],
      [ "PolymorphicArenaAllocator", "classamrex_1_1PolymorphicArenaAllocator.html", "classamrex_1_1PolymorphicArenaAllocator" ],
      [ "PolymorphicArenaWrapper", "structamrex_1_1PolymorphicArenaWrapper.html", "structamrex_1_1PolymorphicArenaWrapper" ],
      [ "PolymorphicArray4", "structamrex_1_1PolymorphicArray4.html", "structamrex_1_1PolymorphicArray4" ],
      [ "Print", "classamrex_1_1Print.html", "classamrex_1_1Print" ],
      [ "PrintToFile", "classamrex_1_1PrintToFile.html", "classamrex_1_1PrintToFile" ],
      [ "RandomEngine", "structamrex_1_1RandomEngine.html", "structamrex_1_1RandomEngine" ],
      [ "RealBox", "classamrex_1_1RealBox.html", "classamrex_1_1RealBox" ],
      [ "RealDescriptor", "classamrex_1_1RealDescriptor.html", "classamrex_1_1RealDescriptor" ],
      [ "RealVectND", "classamrex_1_1RealVectND.html", "classamrex_1_1RealVectND" ],
      [ "RedistributeUnpackPolicy", "structamrex_1_1RedistributeUnpackPolicy.html", "structamrex_1_1RedistributeUnpackPolicy" ],
      [ "ReduceData", "classamrex_1_1ReduceData.html", "classamrex_1_1ReduceData" ],
      [ "ReduceOpLogicalAnd", "structamrex_1_1ReduceOpLogicalAnd.html", "structamrex_1_1ReduceOpLogicalAnd" ],
      [ "ReduceOpLogicalOr", "structamrex_1_1ReduceOpLogicalOr.html", "structamrex_1_1ReduceOpLogicalOr" ],
      [ "ReduceOpMax", "structamrex_1_1ReduceOpMax.html", "structamrex_1_1ReduceOpMax" ],
      [ "ReduceOpMin", "structamrex_1_1ReduceOpMin.html", "structamrex_1_1ReduceOpMin" ],
      [ "ReduceOps", "classamrex_1_1ReduceOps.html", "classamrex_1_1ReduceOps" ],
      [ "ReduceOpSum", "structamrex_1_1ReduceOpSum.html", "structamrex_1_1ReduceOpSum" ],
      [ "ref_wrapper", "classamrex_1_1ref__wrapper.html", "classamrex_1_1ref__wrapper" ],
      [ "RKIntegrator", "classamrex_1_1RKIntegrator.html", "classamrex_1_1RKIntegrator" ],
      [ "RunOnGpu", "structamrex_1_1RunOnGpu.html", null ],
      [ "RunOnGpu< ArenaAllocator< T > >", "structamrex_1_1RunOnGpu_3_01ArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "RunOnGpu< AsyncArenaAllocator< T > >", "structamrex_1_1RunOnGpu_3_01AsyncArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "RunOnGpu< DeviceArenaAllocator< T > >", "structamrex_1_1RunOnGpu_3_01DeviceArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "RunOnGpu< ManagedArenaAllocator< T > >", "structamrex_1_1RunOnGpu_3_01ManagedArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "Same", "structamrex_1_1Same.html", "structamrex_1_1Same" ],
      [ "Same< T, U >", "structamrex_1_1Same_3_01T_00_01U_01_4.html", "structamrex_1_1Same_3_01T_00_01U_01_4" ],
      [ "SArena", "classamrex_1_1SArena.html", "classamrex_1_1SArena" ],
      [ "SIMDindex", "structamrex_1_1SIMDindex.html", "structamrex_1_1SIMDindex" ],
      [ "SmallMatrix", "structamrex_1_1SmallMatrix.html", "structamrex_1_1SmallMatrix" ],
      [ "SoAParticle", "structamrex_1_1SoAParticle.html", "structamrex_1_1SoAParticle" ],
      [ "SoAParticleBase", "structamrex_1_1SoAParticleBase.html", "structamrex_1_1SoAParticleBase" ],
      [ "SparseBinIteratorFactory", "structamrex_1_1SparseBinIteratorFactory.html", "structamrex_1_1SparseBinIteratorFactory" ],
      [ "SparseBins", "classamrex_1_1SparseBins.html", "classamrex_1_1SparseBins" ],
      [ "SplineDistFcnElement2d", "classamrex_1_1SplineDistFcnElement2d.html", "classamrex_1_1SplineDistFcnElement2d" ],
      [ "SpMatrix", "classamrex_1_1SpMatrix.html", "classamrex_1_1SpMatrix" ],
      [ "SrcComp", "structamrex_1_1SrcComp.html", "structamrex_1_1SrcComp" ],
      [ "Stack", "structamrex_1_1Stack.html", "structamrex_1_1Stack" ],
      [ "StateData", "classamrex_1_1StateData.html", "classamrex_1_1StateData" ],
      [ "StateDataPhysBCFunct", "classamrex_1_1StateDataPhysBCFunct.html", "classamrex_1_1StateDataPhysBCFunct" ],
      [ "StateDescriptor", "classamrex_1_1StateDescriptor.html", "classamrex_1_1StateDescriptor" ],
      [ "STLtools", "classamrex_1_1STLtools.html", "classamrex_1_1STLtools" ],
      [ "StreamRetry", "classamrex_1_1StreamRetry.html", "classamrex_1_1StreamRetry" ],
      [ "StructOfArrays", "structamrex_1_1StructOfArrays.html", "structamrex_1_1StructOfArrays" ],
      [ "SundialsIntegrator", "classamrex_1_1SundialsIntegrator.html", "classamrex_1_1SundialsIntegrator" ],
      [ "SundialsUserData", "structamrex_1_1SundialsUserData.html", "structamrex_1_1SundialsUserData" ],
      [ "Table1D", "structamrex_1_1Table1D.html", "structamrex_1_1Table1D" ],
      [ "Table2D", "structamrex_1_1Table2D.html", "structamrex_1_1Table2D" ],
      [ "Table3D", "structamrex_1_1Table3D.html", "structamrex_1_1Table3D" ],
      [ "Table4D", "structamrex_1_1Table4D.html", "structamrex_1_1Table4D" ],
      [ "TableData", "classamrex_1_1TableData.html", "classamrex_1_1TableData" ],
      [ "TagBox", "classamrex_1_1TagBox.html", "classamrex_1_1TagBox" ],
      [ "TagBoxArray", "classamrex_1_1TagBoxArray.html", "classamrex_1_1TagBoxArray" ],
      [ "TagVector", "structamrex_1_1TagVector.html", "structamrex_1_1TagVector" ],
      [ "TheFaArenaDeleter", "structamrex_1_1TheFaArenaDeleter.html", "structamrex_1_1TheFaArenaDeleter" ],
      [ "ThisParticleTileHasNoAoS", "structamrex_1_1ThisParticleTileHasNoAoS.html", "structamrex_1_1ThisParticleTileHasNoAoS" ],
      [ "ThisParticleTileHasNoParticleVector", "structamrex_1_1ThisParticleTileHasNoParticleVector.html", null ],
      [ "TileSize", "structamrex_1_1TileSize.html", "structamrex_1_1TileSize" ],
      [ "TimeIntegrator", "classamrex_1_1TimeIntegrator.html", "classamrex_1_1TimeIntegrator" ],
      [ "TinyProfiler", "classamrex_1_1TinyProfiler.html", "classamrex_1_1TinyProfiler" ],
      [ "TinyProfileRegion", "classamrex_1_1TinyProfileRegion.html", "classamrex_1_1TinyProfileRegion" ],
      [ "TracerParticleContainer", "classamrex_1_1TracerParticleContainer.html", "classamrex_1_1TracerParticleContainer" ],
      [ "TransformerGhost", "structamrex_1_1TransformerGhost.html", "structamrex_1_1TransformerGhost" ],
      [ "TransformerVirt", "structamrex_1_1TransformerVirt.html", "structamrex_1_1TransformerVirt" ],
      [ "TypeArray", "structamrex_1_1TypeArray.html", "structamrex_1_1TypeArray" ],
      [ "TypeList", "structamrex_1_1TypeList.html", "structamrex_1_1TypeList" ],
      [ "ValLocPair", "structamrex_1_1ValLocPair.html", "structamrex_1_1ValLocPair" ],
      [ "Vector", "classamrex_1_1Vector.html", "classamrex_1_1Vector" ],
      [ "VectorTag", "structamrex_1_1VectorTag.html", "structamrex_1_1VectorTag" ],
      [ "VisMF", "classamrex_1_1VisMF.html", "classamrex_1_1VisMF" ],
      [ "VisMFBuffer", "classamrex_1_1VisMFBuffer.html", "classamrex_1_1VisMFBuffer" ],
      [ "VoidCopyTag", "structamrex_1_1VoidCopyTag.html", "structamrex_1_1VoidCopyTag" ],
      [ "XDim3", "structamrex_1_1XDim3.html", "structamrex_1_1XDim3" ],
      [ "YAFluxRegisterT", "classamrex_1_1YAFluxRegisterT.html", "classamrex_1_1YAFluxRegisterT" ]
    ] ],
    [ "std", null, [
      [ "tuple_element< N, amrex::SmallMatrix< T, NRows, NCols, ORDER, StartIndex > >", "structstd_1_1tuple__element_3_01N_00_01amrex_1_1SmallMatrix_3_01T_00_01NRows_00_01NCols_00_01ORDER_00_01StartIndex_01_4_01_4.html", "structstd_1_1tuple__element_3_01N_00_01amrex_1_1SmallMatrix_3_01T_00_01NRows_00_01NCols_00_01ORDER_00_01StartIndex_01_4_01_4" ],
      [ "tuple_element< s, amrex::GpuTuple< T, Ts... > >", "structstd_1_1tuple__element_3_01s_00_01amrex_1_1GpuTuple_3_01T_00_01Ts_8_8_8_01_4_01_4.html", "structstd_1_1tuple__element_3_01s_00_01amrex_1_1GpuTuple_3_01T_00_01Ts_8_8_8_01_4_01_4" ],
      [ "tuple_element< s, amrex::IndexTypeND< dim > >", "structstd_1_1tuple__element_3_01s_00_01amrex_1_1IndexTypeND_3_01dim_01_4_01_4.html", "structstd_1_1tuple__element_3_01s_00_01amrex_1_1IndexTypeND_3_01dim_01_4_01_4" ],
      [ "tuple_element< s, amrex::IntVectND< dim > >", "structstd_1_1tuple__element_3_01s_00_01amrex_1_1IntVectND_3_01dim_01_4_01_4.html", "structstd_1_1tuple__element_3_01s_00_01amrex_1_1IntVectND_3_01dim_01_4_01_4" ],
      [ "tuple_element< s, amrex::RealVectND< dim > >", "structstd_1_1tuple__element_3_01s_00_01amrex_1_1RealVectND_3_01dim_01_4_01_4.html", "structstd_1_1tuple__element_3_01s_00_01amrex_1_1RealVectND_3_01dim_01_4_01_4" ],
      [ "tuple_element< std::size_t{0}, amrex::GpuTuple< T, Ts... > >", "structstd_1_1tuple__element_3_01std_1_1size__t_020_03_00_01amrex_1_1GpuTuple_3_01T_00_01Ts_8_8_8_01_4_01_4.html", "structstd_1_1tuple__element_3_01std_1_1size__t_020_03_00_01amrex_1_1GpuTuple_3_01T_00_01Ts_8_8_8_01_4_01_4" ],
      [ "tuple_size< amrex::GpuTuple< Ts... > >", "structstd_1_1tuple__size_3_01amrex_1_1GpuTuple_3_01Ts_8_8_8_01_4_01_4.html", "structstd_1_1tuple__size_3_01amrex_1_1GpuTuple_3_01Ts_8_8_8_01_4_01_4" ],
      [ "tuple_size< amrex::IndexTypeND< dim > >", "structstd_1_1tuple__size_3_01amrex_1_1IndexTypeND_3_01dim_01_4_01_4.html", "structstd_1_1tuple__size_3_01amrex_1_1IndexTypeND_3_01dim_01_4_01_4" ],
      [ "tuple_size< amrex::IntVectND< dim > >", "structstd_1_1tuple__size_3_01amrex_1_1IntVectND_3_01dim_01_4_01_4.html", "structstd_1_1tuple__size_3_01amrex_1_1IntVectND_3_01dim_01_4_01_4" ],
      [ "tuple_size< amrex::RealVectND< dim > >", "structstd_1_1tuple__size_3_01amrex_1_1RealVectND_3_01dim_01_4_01_4.html", "structstd_1_1tuple__size_3_01amrex_1_1RealVectND_3_01dim_01_4_01_4" ],
      [ "tuple_size< amrex::SmallMatrix< T, NRows, NCols, ORDER, StartIndex > >", "structstd_1_1tuple__size_3_01amrex_1_1SmallMatrix_3_01T_00_01NRows_00_01NCols_00_01ORDER_00_01StartIndex_01_4_01_4.html", null ]
    ] ]
];