var hierarchy =
[
    [ "hacc::AlignedAllocator< T, N >", "classhacc_1_1AlignedAllocator.html", null ],
    [ "allocator", null, [
      [ "amrex::PODVector< T, Allocator >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< amrex::AssignGrid< BinIteratorFactory > >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< amrex::Box >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< amrex::GpuArray< amrex::MLCellLinOp::BCTL, 2 *AMREX_SPACEDIM > >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< amrex::Real >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< char >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< index_type >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< int >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< Real >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< std::size_t >", "classamrex_1_1PODVector.html", null ],
      [ "amrex::PODVector< unsigned int >", "classamrex_1_1PODVector.html", null ]
    ] ],
    [ "amrex::AmrAssignGrid< BinIteratorFactory >", "structamrex_1_1AmrAssignGrid.html", null ],
    [ "amrex::AmrAssignGrid< amrex::DenseBinIteratorFactory< amrex::Box > >", "structamrex_1_1AmrAssignGrid.html", null ],
    [ "amrex::AmrData", "classamrex_1_1AmrData.html", null ],
    [ "amrex::AMRErrorTag", "classamrex_1_1AMRErrorTag.html", null ],
    [ "amrex::AMRErrorTagInfo", "structamrex_1_1AMRErrorTagInfo.html", null ],
    [ "amrex::AMReX", "classamrex_1_1AMReX.html", null ],
    [ "amrex_mempool_module::amrex_allocate", "interfaceamrex__mempool__module_1_1amrex__allocate.html", null ],
    [ "amrex_mempool_module::amrex_deallocate", "interfaceamrex__mempool__module_1_1amrex__deallocate.html", null ],
    [ "amrex_parmparse_module::amrex_delete_parmparse", "interfaceamrex__parmparse__module_1_1amrex__delete__parmparse.html", null ],
    [ "amrex_error_module::amrex_error", "interfaceamrex__error__module_1_1amrex__error.html", null ],
    [ "amrex_error_module::amrex_fi_abort", "interfaceamrex__error__module_1_1amrex__fi__abort.html", null ],
    [ "amrex_error_module::amrex_fi_error", "interfaceamrex__error__module_1_1amrex__fi__error.html", null ],
    [ "amrex_paralleldescriptor_module::amrex_fi_pd_bcast_r", "interfaceamrex__paralleldescriptor__module_1_1amrex__fi__pd__bcast__r.html", null ],
    [ "amrex_paralleldescriptor_module::amrex_fi_pd_ioprocessor", "interfaceamrex__paralleldescriptor__module_1_1amrex__fi__pd__ioprocessor.html", null ],
    [ "amrex_paralleldescriptor_module::amrex_fi_pd_ioprocessor_number", "interfaceamrex__paralleldescriptor__module_1_1amrex__fi__pd__ioprocessor__number.html", null ],
    [ "amrex_paralleldescriptor_module::amrex_fi_pd_myproc", "interfaceamrex__paralleldescriptor__module_1_1amrex__fi__pd__myproc.html", null ],
    [ "amrex_paralleldescriptor_module::amrex_fi_pd_nprocs", "interfaceamrex__paralleldescriptor__module_1_1amrex__fi__pd__nprocs.html", null ],
    [ "amrex_paralleldescriptor_module::amrex_fi_pd_wtime", "interfaceamrex__paralleldescriptor__module_1_1amrex__fi__pd__wtime.html", null ],
    [ "amrex_error_module::amrex_fi_warning", "interfaceamrex__error__module_1_1amrex__fi__warning.html", null ],
    [ "amrex_filcc_module::amrex_filcc", "interfaceamrex__filcc__module_1_1amrex__filcc.html", null ],
    [ "amrex_fort_module::amrex_free", "interfaceamrex__fort__module_1_1amrex__free.html", null ],
    [ "amrex::amrex_iparser", "structamrex_1_1amrex__iparser.html", null ],
    [ "AMREX_IPARSERSTYPE", "unionAMREX__IPARSERSTYPE.html", null ],
    [ "amrex_fort_module::amrex_malloc", "interfaceamrex__fort__module_1_1amrex__malloc.html", null ],
    [ "amrex_mempool_module::amrex_mempool_alloc", "interfaceamrex__mempool__module_1_1amrex__mempool__alloc.html", null ],
    [ "amrex_mempool_module::amrex_mempool_free", "interfaceamrex__mempool__module_1_1amrex__mempool__free.html", null ],
    [ "amrex_parmparse_module::amrex_new_parmparse", "interfaceamrex__parmparse__module_1_1amrex__new__parmparse.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse", "structamrex__parmparse__module_1_1amrex__parmparse.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_add_bool", "interfaceamrex__parmparse__module_1_1amrex__parmparse__add__bool.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_add_int", "interfaceamrex__parmparse__module_1_1amrex__parmparse__add__int.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_add_intarr", "interfaceamrex__parmparse__module_1_1amrex__parmparse__add__intarr.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_add_real", "interfaceamrex__parmparse__module_1_1amrex__parmparse__add__real.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_add_realarr", "interfaceamrex__parmparse__module_1_1amrex__parmparse__add__realarr.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_add_string", "interfaceamrex__parmparse__module_1_1amrex__parmparse__add__string.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_add_stringarr", "interfaceamrex__parmparse__module_1_1amrex__parmparse__add__stringarr.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_delete_cp_char", "interfaceamrex__parmparse__module_1_1amrex__parmparse__delete__cp__char.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_get_bool", "interfaceamrex__parmparse__module_1_1amrex__parmparse__get__bool.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_get_counts", "interfaceamrex__parmparse__module_1_1amrex__parmparse__get__counts.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_get_int", "interfaceamrex__parmparse__module_1_1amrex__parmparse__get__int.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_get_intarr", "interfaceamrex__parmparse__module_1_1amrex__parmparse__get__intarr.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_get_real", "interfaceamrex__parmparse__module_1_1amrex__parmparse__get__real.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_get_realarr", "interfaceamrex__parmparse__module_1_1amrex__parmparse__get__realarr.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_get_string", "interfaceamrex__parmparse__module_1_1amrex__parmparse__get__string.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_get_stringarr", "interfaceamrex__parmparse__module_1_1amrex__parmparse__get__stringarr.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_query_bool", "interfaceamrex__parmparse__module_1_1amrex__parmparse__query__bool.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_query_int", "interfaceamrex__parmparse__module_1_1amrex__parmparse__query__int.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_query_real", "interfaceamrex__parmparse__module_1_1amrex__parmparse__query__real.html", null ],
    [ "amrex_parmparse_module::amrex_parmparse_query_string", "interfaceamrex__parmparse__module_1_1amrex__parmparse__query__string.html", null ],
    [ "amrex::amrex_parser", "structamrex_1_1amrex__parser.html", null ],
    [ "AMREX_PARSERSTYPE", "unionAMREX__PARSERSTYPE.html", null ],
    [ "amrex_paralleldescriptor_module::amrex_pd_bcast", "interfaceamrex__paralleldescriptor__module_1_1amrex__pd__bcast.html", null ],
    [ "amrex_fort_module::amrex_random", "interfaceamrex__fort__module_1_1amrex__random.html", null ],
    [ "amrex_fort_module::amrex_random_int", "interfaceamrex__fort__module_1_1amrex__random__int.html", null ],
    [ "amrex_mempool_module::amrex_real_array_init", "interfaceamrex__mempool__module_1_1amrex__real__array__init.html", null ],
    [ "amrex_string_module::amrex_string", "structamrex__string__module_1_1amrex__string.html", null ],
    [ "amrex::InSituUtils::amrex_tt< cpp_t >", "structamrex_1_1InSituUtils_1_1amrex__tt.html", null ],
    [ "amrex::AmrInfo", "structamrex_1_1AmrInfo.html", [
      [ "amrex::AmrMesh", "classamrex_1_1AmrMesh.html", [
        [ "amrex::AmrCore", "classamrex_1_1AmrCore.html", [
          [ "amrex::Amr", "classamrex_1_1Amr.html", null ]
        ] ]
      ] ]
    ] ],
    [ "amrex::AmrLevel", "classamrex_1_1AmrLevel.html", null ],
    [ "amrex::AmrParticleLocator< Bins >", "classamrex_1_1AmrParticleLocator.html", null ],
    [ "amrex::AmrParticleLocator< amrex::DenseBins< amrex::Box > >", "classamrex_1_1AmrParticleLocator.html", null ],
    [ "amrex::detail::apply_result< F,... >", "structamrex_1_1detail_1_1apply__result.html", null ],
    [ "amrex::detail::apply_result< F, GpuTuple< Ts... > >", "structamrex_1_1detail_1_1apply__result_3_01F_00_01GpuTuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "amrex::Arena", "classamrex_1_1Arena.html", [
      [ "amrex::BArena", "classamrex_1_1BArena.html", null ],
      [ "amrex::CArena", "classamrex_1_1CArena.html", null ],
      [ "amrex::DArena", "classamrex_1_1DArena.html", null ],
      [ "amrex::EArena", "classamrex_1_1EArena.html", null ],
      [ "amrex::PArena", "classamrex_1_1PArena.html", null ]
    ] ],
    [ "amrex::ArenaAllocatorTraits", "structamrex_1_1ArenaAllocatorTraits.html", [
      [ "amrex::ArenaAllocator< T >", "classamrex_1_1ArenaAllocator.html", [
        [ "amrex::PODVector< const int *, DefaultAllocator< const int * > >", "classamrex_1_1PODVector.html", null ],
        [ "amrex::PODVector< const ParticleReal *, DefaultAllocator< const ParticleReal * > >", "classamrex_1_1PODVector.html", null ],
        [ "amrex::PODVector< int *, DefaultAllocator< int * > >", "classamrex_1_1PODVector.html", null ],
        [ "amrex::PODVector< ParticleReal *, DefaultAllocator< ParticleReal * > >", "classamrex_1_1PODVector.html", null ],
        [ "amrex::PODVector< ParticleType, DefaultAllocator< ParticleType > >", "classamrex_1_1PODVector.html", null ]
      ] ],
      [ "amrex::AsyncArenaAllocator< T >", "classamrex_1_1AsyncArenaAllocator.html", null ],
      [ "amrex::DeviceArenaAllocator< T >", "classamrex_1_1DeviceArenaAllocator.html", null ],
      [ "amrex::ManagedArenaAllocator< T >", "classamrex_1_1ManagedArenaAllocator.html", null ],
      [ "amrex::PinnedArenaAllocator< T >", "classamrex_1_1PinnedArenaAllocator.html", null ]
    ] ],
    [ "amrex::ArenaInfo", "structamrex_1_1ArenaInfo.html", null ],
    [ "amrex::Array1D< T, XLO, XHI >", "structamrex_1_1Array1D.html", null ],
    [ "amrex::Array2D< T, XLO, XHI, YLO, YHI, ORDER >", "structamrex_1_1Array2D.html", null ],
    [ "amrex::Array3D< T, XLO, XHI, YLO, YHI, ZLO, ZHI, ORDER >", "structamrex_1_1Array3D.html", null ],
    [ "amrex::Array4< T >", "structamrex_1_1Array4.html", [
      [ "amrex::PolymorphicArray4< T >", "structamrex_1_1PolymorphicArray4.html", null ]
    ] ],
    [ "amrex::Array4< int >", "structamrex_1_1Array4.html", null ],
    [ "amrex::Array4< T const >", "structamrex_1_1Array4.html", null ],
    [ "amrex::Array4< value_type >", "structamrex_1_1Array4.html", null ],
    [ "amrex::Array4< value_type const >", "structamrex_1_1Array4.html", null ],
    [ "amrex::NonLocalBC::Array4Array4Box< T >", "structamrex_1_1NonLocalBC_1_1Array4Array4Box.html", null ],
    [ "amrex::Array4BoxTag< T >", "structamrex_1_1Array4BoxTag.html", null ],
    [ "amrex::Array4BoxValTag< T >", "structamrex_1_1Array4BoxValTag.html", null ],
    [ "amrex::Array4CopyTag< T >", "structamrex_1_1Array4CopyTag.html", null ],
    [ "amrex::Array4MaskCopyTag< T >", "structamrex_1_1Array4MaskCopyTag.html", null ],
    [ "amrex::Array4Tag< T >", "structamrex_1_1Array4Tag.html", null ],
    [ "amrex::ArrayOfStructs< NReal, NInt, Allocator >", "classamrex_1_1ArrayOfStructs.html", null ],
    [ "amrex::ArrayOfStructs< NStructReal, NStructInt, DefaultAllocator >", "classamrex_1_1ArrayOfStructs.html", null ],
    [ "amrex::AssignGrid< BinIteratorFactory >", "structamrex_1_1AssignGrid.html", null ],
    [ "amrex::AssignGrid< amrex::DenseBinIteratorFactory< amrex::Box > >", "structamrex_1_1AssignGrid.html", null ],
    [ "AssignGridFilter", "structAssignGridFilter.html", null ],
    [ "amrex::InSituUtils::assignOp< n_t >", "structamrex_1_1InSituUtils_1_1assignOp.html", null ],
    [ "amrex::MFUtil::AsymmetricGhost< T >", "structamrex_1_1MFUtil_1_1AsymmetricGhost.html", null ],
    [ "amrex::Gpu::AsyncArray< T, >", "classamrex_1_1Gpu_1_1AsyncArray.html", null ],
    [ "amrex::Gpu::AtomicAdd< T >", "structamrex_1_1Gpu_1_1AtomicAdd.html", null ],
    [ "amrex::Gpu::AtomicLogicalAnd< T >", "structamrex_1_1Gpu_1_1AtomicLogicalAnd.html", null ],
    [ "amrex::Gpu::AtomicLogicalOr< T >", "structamrex_1_1Gpu_1_1AtomicLogicalOr.html", null ],
    [ "amrex::Gpu::AtomicMax< T >", "structamrex_1_1Gpu_1_1AtomicMax.html", null ],
    [ "amrex::Gpu::AtomicMin< T >", "structamrex_1_1Gpu_1_1AtomicMin.html", null ],
    [ "B1", null, [
      [ "amrex::Conjunction< B1 >", "structamrex_1_1Conjunction_3_01B1_01_4.html", null ],
      [ "amrex::Disjunction< B1 >", "structamrex_1_1Disjunction_3_01B1_01_4.html", null ]
    ] ],
    [ "amrex::BackgroundThread", "classamrex_1_1BackgroundThread.html", null ],
    [ "amrex::BARef", "structamrex_1_1BARef.html", null ],
    [ "CommProfStats::BarrierEntry", "structCommProfStats_1_1BarrierEntry.html", null ],
    [ "amrex::BaseUmap< T >", "classamrex_1_1BaseUmap.html", null ],
    [ "amrex::BATbndryReg", "structamrex_1_1BATbndryReg.html", null ],
    [ "amrex::BATcoarsenRatio", "structamrex_1_1BATcoarsenRatio.html", null ],
    [ "amrex::BATindexType", "structamrex_1_1BATindexType.html", null ],
    [ "amrex::BATindexType_coarsenRatio", "structamrex_1_1BATindexType__coarsenRatio.html", null ],
    [ "amrex::BATnull", "structamrex_1_1BATnull.html", null ],
    [ "amrex::BATransformer::BATOp", "unionamrex_1_1BATransformer_1_1BATOp.html", null ],
    [ "amrex::BATransformer", "structamrex_1_1BATransformer.html", null ],
    [ "amrex::BCRec", "classamrex_1_1BCRec.html", null ],
    [ "amrex::MLCellLinOp::BCTL", "structamrex_1_1MLCellLinOp_1_1BCTL.html", null ],
    [ "amrex::FabArrayBase::BDKey", "structamrex_1_1FabArrayBase_1_1BDKey.html", null ],
    [ "amrex::BinIterator< T >", "structamrex_1_1BinIterator.html", null ],
    [ "amrex_mempool_module::bl_allocate", "interfaceamrex__mempool__module_1_1bl__allocate.html", null ],
    [ "amrex_mempool_module::bl_deallocate", "interfaceamrex__mempool__module_1_1bl__deallocate.html", null ],
    [ "amrex::BLBackTrace", "structamrex_1_1BLBackTrace.html", null ],
    [ "amrex::BLBTer", "classamrex_1_1BLBTer.html", null ],
    [ "amrex::BlockMutex", "structamrex_1_1BlockMutex.html", null ],
    [ "amrex::Scan::detail::BlockStatus< T, SINGLE_WORD >", "structamrex_1_1Scan_1_1detail_1_1BlockStatus.html", null ],
    [ "amrex::Scan::detail::BlockStatus< T, false >", "structamrex_1_1Scan_1_1detail_1_1BlockStatus_3_01T_00_01false_01_4.html", null ],
    [ "amrex::Scan::detail::BlockStatus< T, true >", "structamrex_1_1Scan_1_1detail_1_1BlockStatus_3_01T_00_01true_01_4.html", null ],
    [ "BLProfStats::BLPDataBlock", "structBLProfStats_1_1BLPDataBlock.html", null ],
    [ "amrex::BLProfiler", "classamrex_1_1BLProfiler.html", null ],
    [ "BLProfStats", "classBLProfStats.html", [
      [ "CommProfStats", "classCommProfStats.html", null ],
      [ "RegionsProfStats", "classRegionsProfStats.html", null ]
    ] ],
    [ "amrex::MLCellLinOp::BndryCondLoc", "classamrex_1_1MLCellLinOp_1_1BndryCondLoc.html", null ],
    [ "amrex::StateDescriptor::BndryFunc", "classamrex_1_1StateDescriptor_1_1BndryFunc.html", null ],
    [ "amrex::BndryFuncArray", "classamrex_1_1BndryFuncArray.html", null ],
    [ "amrex::BndryRegister", "classamrex_1_1BndryRegister.html", [
      [ "amrex::BndryData", "classamrex_1_1BndryData.html", [
        [ "amrex::InterpBndryData", "classamrex_1_1InterpBndryData.html", [
          [ "amrex::MacBndry", "classamrex_1_1MacBndry.html", null ],
          [ "amrex::MLMGBndry", "classamrex_1_1MLMGBndry.html", null ]
        ] ]
      ] ],
      [ "amrex::FluxRegister", "classamrex_1_1FluxRegister.html", null ]
    ] ],
    [ "amrex::BoundCond", "classamrex_1_1BoundCond.html", null ],
    [ "amrex::algoim::BoundingBox< N >", "structamrex_1_1algoim_1_1BoundingBox.html", null ],
    [ "amrex::Box", "classamrex_1_1Box.html", null ],
    [ "amrex::BoxArray", "classamrex_1_1BoxArray.html", null ],
    [ "amrex::BoxCommHelper", "classamrex_1_1BoxCommHelper.html", null ],
    [ "amrex::BoxConverter", "classamrex_1_1BoxConverter.html", [
      [ "amrex::InterpolaterBoxCoarsener", "classamrex_1_1InterpolaterBoxCoarsener.html", null ]
    ] ],
    [ "amrex::BoxIterator", "classamrex_1_1BoxIterator.html", null ],
    [ "amrex::BoxList", "classamrex_1_1BoxList.html", [
      [ "amrex::BoxDomain", "classamrex_1_1BoxDomain.html", null ]
    ] ],
    [ "amrex::Gpu::Buffer< T, >", "classamrex_1_1Gpu_1_1Buffer.html", null ],
    [ "amrex::MemProfiler::Builds", "structamrex_1_1MemProfiler_1_1Builds.html", null ],
    [ "amrex::MemProfiler::Bytes", "structamrex_1_1MemProfiler_1_1Bytes.html", null ],
    [ "amrex::Order::C", "structamrex_1_1Order_1_1C.html", null ],
    [ "amrex::FabArrayBase::CacheStats", "structamrex_1_1FabArrayBase_1_1CacheStats.html", null ],
    [ "BLProfStats::CallTreeNode", "structBLProfStats_1_1CallTreeNode.html", null ],
    [ "amrex::EB2::Cell", "structamrex_1_1EB2_1_1Cell.html", null ],
    [ "detail::CellAdd< T >", "structdetail_1_1CellAdd.html", null ],
    [ "detail::CellAtomicAdd< T >", "structdetail_1_1CellAtomicAdd.html", null ],
    [ "detail::CellStore< T >", "structdetail_1_1CellStore.html", null ],
    [ "amrex::FabArrayBase::CFinfo", "structamrex_1_1FabArrayBase_1_1CFinfo.html", null ],
    [ "amrex::Cluster", "classamrex_1_1Cluster.html", null ],
    [ "amrex::ClusterList", "classamrex_1_1ClusterList.html", null ],
    [ "amrex::detail::clzll_tag", "structamrex_1_1detail_1_1clzll__tag.html", [
      [ "amrex::detail::clzl_tag", "structamrex_1_1detail_1_1clzl__tag.html", [
        [ "amrex::detail::clz_tag", "structamrex_1_1detail_1_1clz__tag.html", null ]
      ] ]
    ] ],
    [ "amrex::MLLinOp::CommContainer", "structamrex_1_1MLLinOp_1_1CommContainer.html", null ],
    [ "amrex::NonLocalBC::CommData", "structamrex_1_1NonLocalBC_1_1CommData.html", null ],
    [ "amrex::NonLocalBC::CommHandler", "structamrex_1_1NonLocalBC_1_1CommHandler.html", null ],
    [ "amrex::FabArrayBase::CommMetaData", "structamrex_1_1FabArrayBase_1_1CommMetaData.html", [
      [ "amrex::FabArrayBase::CPC", "structamrex_1_1FabArrayBase_1_1CPC.html", null ],
      [ "amrex::FabArrayBase::FB", "structamrex_1_1FabArrayBase_1_1FB.html", null ],
      [ "amrex::FabArrayBase::PolarB", "structamrex_1_1FabArrayBase_1_1PolarB.html", null ],
      [ "amrex::FabArrayBase::RB180", "structamrex_1_1FabArrayBase_1_1RB180.html", null ],
      [ "amrex::FabArrayBase::RB90", "structamrex_1_1FabArrayBase_1_1RB90.html", null ],
      [ "amrex::NonLocalBC::MultiBlockCommMetaData", "structamrex_1_1NonLocalBC_1_1MultiBlockCommMetaData.html", null ]
    ] ],
    [ "amrex::EArena::Node::CompareAddr", "structamrex_1_1EArena_1_1Node_1_1CompareAddr.html", null ],
    [ "amrex::EArena::Node::CompareSize", "structamrex_1_1EArena_1_1Node_1_1CompareSize.html", null ],
    [ "amrex::EB2::ComplementIF< F >", "classamrex_1_1EB2_1_1ComplementIF.html", null ],
    [ "amrex::Gpu::ComponentBox", "structamrex_1_1Gpu_1_1ComponentBox.html", null ],
    [ "amrex::ForkJoin::ComponentSet", "structamrex_1_1ForkJoin_1_1ComponentSet.html", null ],
    [ "conditional_t", null, [
      [ "amrex::Conjunction< B1, Bn... >", "structamrex_1_1Conjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ],
      [ "amrex::Disjunction< B1, Bn... >", "structamrex_1_1Disjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ]
    ] ],
    [ "amrex::BaseUmap< T >::const_iterator", "structamrex_1_1BaseUmap_1_1const__iterator.html", null ],
    [ "amrex::Neighbors< ParticleType >::const_iterator", "structamrex_1_1Neighbors_1_1const__iterator.html", null ],
    [ "amrex::ConstParticleCPUWrapper", "structamrex_1_1ConstParticleCPUWrapper.html", null ],
    [ "amrex::ConstParticleIDWrapper", "structamrex_1_1ConstParticleIDWrapper.html", null ],
    [ "amrex::ConstParticleTileData< NStructReal, NStructInt, NArrayReal, NArrayInt >", "structamrex_1_1ConstParticleTileData.html", null ],
    [ "amrex::CoordSys", "classamrex_1_1CoordSys.html", [
      [ "amrex::Geometry", "classamrex_1_1Geometry.html", null ]
    ] ],
    [ "amrex::FabArrayBase::CopyComTag", "structamrex_1_1FabArrayBase_1_1CopyComTag.html", null ],
    [ "amrex::CpuBndryFuncFab", "classamrex_1_1CpuBndryFuncFab.html", null ],
    [ "amrex::Scan::detail::BlockStatus< T, true >::Data< U >", "unionamrex_1_1Scan_1_1detail_1_1BlockStatus_3_01T_00_01true_01_4_1_1Data.html", null ],
    [ "amrex::IParser::Data", "structamrex_1_1IParser_1_1Data.html", null ],
    [ "amrex::Parser::Data", "structamrex_1_1Parser_1_1Data.html", null ],
    [ "DataAdaptor", null, [
      [ "amrex::AmrDataAdaptor", "classamrex_1_1AmrDataAdaptor.html", null ],
      [ "amrex::AmrMeshDataAdaptor", "classamrex_1_1AmrMeshDataAdaptor.html", null ]
    ] ],
    [ "amrex::DataAllocator", "structamrex_1_1DataAllocator.html", [
      [ "amrex::BaseFab< T >", "classamrex_1_1BaseFab.html", null ],
      [ "amrex::BaseFab< char >", "classamrex_1_1BaseFab.html", [
        [ "amrex::TagBox", "classamrex_1_1TagBox.html", null ]
      ] ],
      [ "amrex::BaseFab< EBCellFlag >", "classamrex_1_1BaseFab.html", [
        [ "amrex::EBCellFlagFab", "classamrex_1_1EBCellFlagFab.html", null ]
      ] ],
      [ "amrex::BaseFab< int >", "classamrex_1_1BaseFab.html", [
        [ "amrex::IArrayBox", "classamrex_1_1IArrayBox.html", null ],
        [ "amrex::Mask", "classamrex_1_1Mask.html", null ]
      ] ],
      [ "amrex::BaseFab< Real >", "classamrex_1_1BaseFab.html", [
        [ "amrex::FArrayBox", "classamrex_1_1FArrayBox.html", [
          [ "amrex::CutFab", "classamrex_1_1CutFab.html", null ],
          [ "amrex::EBFArrayBox", "classamrex_1_1EBFArrayBox.html", null ]
        ] ]
      ] ]
    ] ],
    [ "CommProfStats::DataBlock", "structCommProfStats_1_1DataBlock.html", null ],
    [ "RegionsProfStats::DataBlock", "structRegionsProfStats_1_1DataBlock.html", null ],
    [ "amrex::DataDeleter", "structamrex_1_1DataDeleter.html", null ],
    [ "amrex::DataLayoutPolicy< ContainerType, ParticleType, DataLayoutTag >", "structamrex_1_1DataLayoutPolicy.html", null ],
    [ "amrex::DataLayoutPolicy< ContainerType, ParticleType< Types... >, DataLayout::AoS >", "structamrex_1_1DataLayoutPolicy_3_01ContainerType_00_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1AoS_01_4.html", null ],
    [ "amrex::DataLayoutPolicy< ContainerType, ParticleType< Types... >, DataLayout::SoA >", "structamrex_1_1DataLayoutPolicy_3_01ContainerType_00_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1SoA_01_4.html", null ],
    [ "amrex::DataLayoutPolicyRaw< ParticleType, DataLayoutTag >", "structamrex_1_1DataLayoutPolicyRaw.html", null ],
    [ "amrex::DataLayoutPolicyRaw< ParticleType< Types... >, DataLayout::AoS >", "structamrex_1_1DataLayoutPolicyRaw_3_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1AoS_01_4.html", null ],
    [ "amrex::DataLayoutPolicyRaw< ParticleType< Types... >, DataLayout::SoA >", "structamrex_1_1DataLayoutPolicyRaw_3_01ParticleType_3_01Types_8_8_8_01_4_00_01DataLayout_1_1SoA_01_4.html", null ],
    [ "amrex::DataServices", "classamrex_1_1DataServices.html", null ],
    [ "amrex::Gpu::Deleter", "structamrex_1_1Gpu_1_1Deleter.html", null ],
    [ "amrex::DenseBinIteratorFactory< T >", "structamrex_1_1DenseBinIteratorFactory.html", null ],
    [ "amrex::DenseBinIteratorFactory< amrex::Box >", "structamrex_1_1DenseBinIteratorFactory.html", null ],
    [ "amrex::DenseBins< T >", "classamrex_1_1DenseBins.html", null ],
    [ "amrex::DenseBins< amrex::Particle >", "classamrex_1_1DenseBins.html", null ],
    [ "amrex::DenseBins< ParticleType >", "classamrex_1_1DenseBins.html", null ],
    [ "amrex::DeriveList", "classamrex_1_1DeriveList.html", null ],
    [ "amrex::DeriveRec", "classamrex_1_1DeriveRec.html", null ],
    [ "amrex::DescriptorList", "classamrex_1_1DescriptorList.html", null ],
    [ "amrex::DestComp", "structamrex_1_1DestComp.html", null ],
    [ "amrex::detail::Detector< Default, AlwaysVoid, Op, Args >", "structamrex_1_1detail_1_1Detector.html", null ],
    [ "amrex::detail::Detector< Default, Void_t< Op< Args... > >, Op, Args... >", "structamrex_1_1detail_1_1Detector_3_01Default_00_01Void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html", null ],
    [ "amrex::Gpu::Device", "classamrex_1_1Gpu_1_1Device.html", null ],
    [ "amrex::Gpu::DeviceScalar< T, >", "structamrex_1_1Gpu_1_1DeviceScalar.html", null ],
    [ "amrex::MFIter::DeviceSync", "structamrex_1_1MFIter_1_1DeviceSync.html", null ],
    [ "amrex::Gpu::DeviceToDevice", "structamrex_1_1Gpu_1_1DeviceToDevice.html", null ],
    [ "amrex::Gpu::DeviceToHost", "structamrex_1_1Gpu_1_1DeviceToHost.html", null ],
    [ "hacc::Dfft", "classhacc_1_1Dfft.html", null ],
    [ "amrex::EB2::DifferenceIF< F, G >", "classamrex_1_1EB2_1_1DifferenceIF.html", null ],
    [ "amrex::Dim3", "structamrex_1_1Dim3.html", null ],
    [ "amrex::distFcnElement2d", "classamrex_1_1distFcnElement2d.html", [
      [ "amrex::LineDistFcnElement2d", "classamrex_1_1LineDistFcnElement2d.html", null ],
      [ "amrex::SplineDistFcnElement2d", "classamrex_1_1SplineDistFcnElement2d.html", null ]
    ] ],
    [ "hacc::Distribution", "classhacc_1_1Distribution.html", null ],
    [ "distribution_t", "structdistribution__t.html", null ],
    [ "amrex::DistributionMapping", "classamrex_1_1DistributionMapping.html", null ],
    [ "amrex::NonLocalBC::DoLocalCopy", "structamrex_1_1NonLocalBC_1_1DoLocalCopy.html", null ],
    [ "amrex::DynamicTiling", "structamrex_1_1DynamicTiling.html", null ],
    [ "amrex::EBCellFlag", "classamrex_1_1EBCellFlag.html", null ],
    [ "amrex::EBDataCollection", "classamrex_1_1EBDataCollection.html", null ],
    [ "amrex::algoim::EBPlane", "structamrex_1_1algoim_1_1EBPlane.html", null ],
    [ "amrex::EBToPVD", "classamrex_1_1EBToPVD.html", null ],
    [ "amrex::EB2::Edge", "structamrex_1_1EB2_1_1Edge.html", null ],
    [ "amrex::Gpu::Elixir", "classamrex_1_1Gpu_1_1Elixir.html", null ],
    [ "amrex::EArena::Node::equal", "structamrex_1_1EArena_1_1Node_1_1equal.html", null ],
    [ "hacc::Error", "classhacc_1_1Error.html", null ],
    [ "amrex::ErrorRec::ErrorFunc", "classamrex_1_1ErrorRec_1_1ErrorFunc.html", null ],
    [ "amrex::ErrorRec::ErrorFunc2", "classamrex_1_1ErrorRec_1_1ErrorFunc2.html", null ],
    [ "amrex::ErrorList", "classamrex_1_1ErrorList.html", null ],
    [ "amrex::ErrorRec", "classamrex_1_1ErrorRec.html", null ],
    [ "amrex::Scan::Type::Exclusive", "structamrex_1_1Scan_1_1Type_1_1Exclusive.html", null ],
    [ "amrex::Gpu::ExecutionConfig", "structamrex_1_1Gpu_1_1ExecutionConfig.html", null ],
    [ "amrex::expect", "classamrex_1_1expect.html", null ],
    [ "amrex::EB2::ExtrusionIF< F >", "classamrex_1_1EB2_1_1ExtrusionIF.html", null ],
    [ "amrex::Order::F", "structamrex_1_1Order_1_1F.html", null ],
    [ "amrex::FabArray< FAB >", "classamrex_1_1FabArray.html", null ],
    [ "amrex::FabArray< amrex::BaseFab< AtomicInt > >", "classamrex_1_1FabArray.html", null ],
    [ "amrex::FabArray< amrex::BaseFab< HYPRE_Int > >", "classamrex_1_1FabArray.html", null ],
    [ "amrex::FabArray< amrex::BaseFab< PetscInt > >", "classamrex_1_1FabArray.html", null ],
    [ "amrex::FabArray< amrex::CutFab >", "classamrex_1_1FabArray.html", null ],
    [ "amrex::FabArray< amrex::EBCellFlagFab >", "classamrex_1_1FabArray.html", null ],
    [ "amrex::FabArray< amrex::Mask >", "classamrex_1_1FabArray.html", null ],
    [ "amrex::FabArray< FArrayBox >", "classamrex_1_1FabArray.html", [
      [ "amrex::MultiFab", "classamrex_1_1MultiFab.html", null ]
    ] ],
    [ "amrex::FabArray< IArrayBox >", "classamrex_1_1FabArray.html", [
      [ "amrex::iMultiFab", "classamrex_1_1iMultiFab.html", null ]
    ] ],
    [ "amrex::FabArray< TagBox >", "classamrex_1_1FabArray.html", [
      [ "amrex::TagBoxArray", "classamrex_1_1TagBoxArray.html", null ]
    ] ],
    [ "amrex::FabArrayBase", "classamrex_1_1FabArrayBase.html", null ],
    [ "amrex::FabArrayCopyDescriptor< FAB >", "classamrex_1_1FabArrayCopyDescriptor.html", null ],
    [ "amrex::FabArrayCopyDescriptor< FArrayBox >", "classamrex_1_1FabArrayCopyDescriptor.html", [
      [ "amrex::MultiFabCopyDescriptor", "classamrex_1_1MultiFabCopyDescriptor.html", null ]
    ] ],
    [ "amrex::FabArrayId", "classamrex_1_1FabArrayId.html", null ],
    [ "amrex::FabArrayBase::FabArrayStats", "structamrex_1_1FabArrayBase_1_1FabArrayStats.html", null ],
    [ "amrex::FabArrayBase::FabComTag", "structamrex_1_1FabArrayBase_1_1FabComTag.html", null ],
    [ "amrex::FabCopyDescriptor< FAB >", "structamrex_1_1FabCopyDescriptor.html", null ],
    [ "FabCopyTag< FAB >", "structFabCopyTag.html", null ],
    [ "amrex::FabFactory< FAB >", "classamrex_1_1FabFactory.html", [
      [ "amrex::DefaultFabFactory< FAB >", "classamrex_1_1DefaultFabFactory.html", null ]
    ] ],
    [ "amrex::FabFactory< amrex::FArrayBox >", "classamrex_1_1FabFactory.html", null ],
    [ "amrex::FabFactory< FArrayBox >", "classamrex_1_1FabFactory.html", [
      [ "amrex::EBFArrayBoxFactory", "classamrex_1_1EBFArrayBoxFactory.html", null ]
    ] ],
    [ "amrex::FabInfo", "structamrex_1_1FabInfo.html", null ],
    [ "amrex::FABio", "classamrex_1_1FABio.html", [
      [ "amrex::FABio_8bit", "classamrex_1_1FABio__8bit.html", null ],
      [ "amrex::FABio_ascii", "classamrex_1_1FABio__ascii.html", null ],
      [ "amrex::FABio_binary", "classamrex_1_1FABio__binary.html", null ]
    ] ],
    [ "amrex::VisMF::FabOnDisk", "structamrex_1_1VisMF_1_1FabOnDisk.html", null ],
    [ "amrex::VisMF::FabReadLink", "structamrex_1_1VisMF_1_1FabReadLink.html", null ],
    [ "amrex::FabSet", "classamrex_1_1FabSet.html", null ],
    [ "amrex::FabArray< FAB >::FABType", "structamrex_1_1FabArray_1_1FABType.html", null ],
    [ "amrex::EB2::Face", "structamrex_1_1EB2_1_1Face.html", null ],
    [ "false_type", null, [
      [ "amrex::DefinitelyNotHostRunnable< T, Enable >", "structamrex_1_1DefinitelyNotHostRunnable.html", null ],
      [ "amrex::Disjunction<... >", "structamrex_1_1Disjunction.html", null ],
      [ "amrex::EB2::IsGPUable< D, Enable >", "structamrex_1_1EB2_1_1IsGPUable.html", null ],
      [ "amrex::HasAtomicAdd< T, Enable >", "structamrex_1_1HasAtomicAdd.html", null ],
      [ "amrex::HasMultiComp< A, Enable >", "structamrex_1_1HasMultiComp.html", null ],
      [ "amrex::IsBaseFab< A, Enable >", "structamrex_1_1IsBaseFab.html", null ],
      [ "amrex::IsFabArray< A, Enable >", "structamrex_1_1IsFabArray.html", null ],
      [ "amrex::IsStoreAtomic< T, Enable >", "structamrex_1_1IsStoreAtomic.html", null ],
      [ "amrex::MaybeHostDeviceRunnable< T, std::enable_if_t< __nv_is_extended_device_lambda_closure_type(T)> >", "structamrex_1_1MaybeHostDeviceRunnable_3_01T_00_01std_1_1enable__if__t_3_01____nv__is__extended_ac548a468bcc64242955fc23b2d496e6.html", null ],
      [ "amrex::RunOnGpu< T >", "structamrex_1_1RunOnGpu.html", null ],
      [ "amrex::EB2::IsGPUable< IntersectionIF< Tail... > >", "structamrex_1_1EB2_1_1IsGPUable.html", [
        [ "amrex::EB2::IsGPUable< IntersectionIF< Head, Tail... >, typename std::enable_if< IsGPUable< Head >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01IntersectionIF_3_01Head_00_01Tail_8_8_8_01_4_00_01typename_0aa6c0e2bc9cf84a2cc942d5a159f7839.html", null ]
      ] ],
      [ "amrex::EB2::IsGPUable< UnionIF< Tail... > >", "structamrex_1_1EB2_1_1IsGPUable.html", [
        [ "amrex::EB2::IsGPUable< UnionIF< Head, Tail... >, typename std::enable_if< IsGPUable< Head >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01UnionIF_3_01Head_00_01Tail_8_8_8_01_4_00_01typename_01std_1_0106a99ebe3263da4342cdd68c621473.html", null ]
      ] ]
    ] ],
    [ "amrex::FBData< FAB >", "structamrex_1_1FBData.html", null ],
    [ "amrex::FilccCell", "structamrex_1_1FilccCell.html", null ],
    [ "amrex::FilfcFace", "structamrex_1_1FilfcFace.html", null ],
    [ "amrex::FillBoxId", "classamrex_1_1FillBoxId.html", null ],
    [ "amrex::FillPatchIteratorHelper", "classamrex_1_1FillPatchIteratorHelper.html", null ],
    [ "FilterVirt", "structFilterVirt.html", null ],
    [ "amrex::ForkJoin", "classamrex_1_1ForkJoin.html", null ],
    [ "amrex::FPC", "classamrex_1_1FPC.html", null ],
    [ "amrex::FabArrayBase::FPinfo", "structamrex_1_1FabArrayBase_1_1FPinfo.html", null ],
    [ "amrex::ParallelContext::Frame", "classamrex_1_1ParallelContext_1_1Frame.html", null ],
    [ "amrex::ParmParse::Frame", "classamrex_1_1ParmParse_1_1Frame.html", null ],
    [ "BLProfStats::FuncStat", "structBLProfStats_1_1FuncStat.html", null ],
    [ "amrex::GeometryData", "structamrex_1_1GeometryData.html", null ],
    [ "amrex::EB2::GeometryShop< F, R >", "classamrex_1_1EB2_1_1GeometryShop.html", null ],
    [ "amrex_ebcellflag_module::get_neighbor_cells", "interfaceamrex__ebcellflag__module_1_1get__neighbor__cells.html", null ],
    [ "amrex::GetBucket", "structamrex_1_1GetBucket.html", null ],
    [ "amrex::GetParticleBin", "structamrex_1_1GetParticleBin.html", null ],
    [ "amrex::GetPID", "structamrex_1_1GetPID.html", null ],
    [ "amrex::GetSendBufferOffset", "structamrex_1_1GetSendBufferOffset.html", null ],
    [ "amrex::EB2::GFab", "classamrex_1_1EB2_1_1GFab.html", null ],
    [ "amrex::detail::gpu_tuple_element< I, T >", "structamrex_1_1detail_1_1gpu__tuple__element.html", null ],
    [ "amrex::detail::gpu_tuple_element< I, Head >", "structamrex_1_1detail_1_1gpu__tuple__element.html", [
      [ "amrex::detail::gpu_tuple_impl< I, Head >", "structamrex_1_1detail_1_1gpu__tuple__impl_3_01I_00_01Head_01_4.html", null ],
      [ "amrex::detail::gpu_tuple_impl< I, Head, Tail... >", "structamrex_1_1detail_1_1gpu__tuple__impl_3_01I_00_01Head_00_01Tail_8_8_8_01_4.html", null ]
    ] ],
    [ "amrex::detail::gpu_tuple_impl< I, Ts >", "structamrex_1_1detail_1_1gpu__tuple__impl.html", null ],
    [ "amrex::detail::gpu_tuple_impl< 0, Ts... >", "structamrex_1_1detail_1_1gpu__tuple__impl.html", [
      [ "amrex::GpuTuple< Ts >", "classamrex_1_1GpuTuple.html", null ],
      [ "amrex::GpuTuple< Fs... >", "classamrex_1_1GpuTuple.html", [
        [ "amrex::EB2::IntersectionIF< Fs >", "classamrex_1_1EB2_1_1IntersectionIF.html", null ],
        [ "amrex::EB2::UnionIF< Fs >", "classamrex_1_1EB2_1_1UnionIF.html", null ]
      ] ]
    ] ],
    [ "amrex::detail::gpu_tuple_impl< I+1, Tail... >", "structamrex_1_1detail_1_1gpu__tuple__impl.html", [
      [ "amrex::detail::gpu_tuple_impl< I, Head, Tail... >", "structamrex_1_1detail_1_1gpu__tuple__impl_3_01I_00_01Head_00_01Tail_8_8_8_01_4.html", null ]
    ] ],
    [ "amrex::GPUable", "structamrex_1_1GPUable.html", [
      [ "amrex::EB2::AllRegularIF", "classamrex_1_1EB2_1_1AllRegularIF.html", null ],
      [ "amrex::EB2::BoxIF", "classamrex_1_1EB2_1_1BoxIF.html", null ],
      [ "amrex::EB2::CylinderIF", "classamrex_1_1EB2_1_1CylinderIF.html", null ],
      [ "amrex::EB2::EllipsoidIF", "classamrex_1_1EB2_1_1EllipsoidIF.html", null ],
      [ "amrex::EB2::ParserIF", "classamrex_1_1EB2_1_1ParserIF.html", null ],
      [ "amrex::EB2::PlaneIF", "classamrex_1_1EB2_1_1PlaneIF.html", null ],
      [ "amrex::EB2::PolyIF< N >", "classamrex_1_1EB2_1_1PolyIF.html", null ],
      [ "amrex::EB2::SphereIF", "classamrex_1_1EB2_1_1SphereIF.html", null ],
      [ "amrex::EB2::TorusIF", "classamrex_1_1EB2_1_1TorusIF.html", null ]
    ] ],
    [ "amrex::GpuArray< T, N >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< amrex::algoim::Interval, N >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< amrex::algoim::QuadratureRule::Node, 256 >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< amrex::EB2::PolyTerm, N >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< amrex::MLCellLinOp::BCTL, 2 *AMREX_SPACEDIM >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< bool, N >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< const int *AMREX_RESTRICT, NArrayInt >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< const ParticleReal *AMREX_RESTRICT, NArrayReal >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< int *AMREX_RESTRICT, NArrayInt >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< int, AMREX_GPU_MAX_STREAMS+1 >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< ParticleReal *AMREX_RESTRICT, NArrayReal >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< Real, 3 >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< Real, AMREX_SPACEDIM >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::GpuArray< Real, nelems >", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::BinPolicy::GPUBinPolicy", "structamrex_1_1BinPolicy_1_1GPUBinPolicy.html", null ],
    [ "amrex::GpuBndryFuncFab< F >", "classamrex_1_1GpuBndryFuncFab.html", null ],
    [ "amrex::GpuComplex< T >", "structamrex_1_1GpuComplex.html", null ],
    [ "amrex::GpuTupleElement< I, T >", "structamrex_1_1GpuTupleElement.html", null ],
    [ "amrex::GpuTupleElement< 0, GpuTuple< Head, Tail... > >", "structamrex_1_1GpuTupleElement_3_010_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4.html", null ],
    [ "amrex::GpuTupleElement< I-1, GpuTuple< Tail... > >", "structamrex_1_1GpuTupleElement.html", [
      [ "amrex::GpuTupleElement< I, GpuTuple< Head, Tail... > >", "structamrex_1_1GpuTupleElement_3_01I_00_01GpuTuple_3_01Head_00_01Tail_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "amrex::GpuTupleSize< T >", "structamrex_1_1GpuTupleSize.html", null ],
    [ "amrex::Gpu::GraphSafeGuard", "structamrex_1_1Gpu_1_1GraphSafeGuard.html", null ],
    [ "amrex::Greater< T >", "structamrex_1_1Greater.html", null ],
    [ "amrex::Gpu::GridSize", "structamrex_1_1Gpu_1_1GridSize.html", null ],
    [ "amrex::Gpu::Handler", "structamrex_1_1Gpu_1_1Handler.html", null ],
    [ "amrex::EArena::Node::hash", "structamrex_1_1EArena_1_1Node_1_1hash.html", null ],
    [ "amrex::CArena::Node::hash", "structamrex_1_1CArena_1_1Node_1_1hash.html", null ],
    [ "amrex::VisMF::Header", "structamrex_1_1VisMF_1_1Header.html", null ],
    [ "amrex::Gpu::HostToDevice", "structamrex_1_1Gpu_1_1HostToDevice.html", null ],
    [ "amrex::Hypre", "classamrex_1_1Hypre.html", [
      [ "amrex::HypreABecLap", "classamrex_1_1HypreABecLap.html", null ],
      [ "amrex::HypreABecLap2", "classamrex_1_1HypreABecLap2.html", null ],
      [ "amrex::HypreABecLap3", "classamrex_1_1HypreABecLap3.html", null ]
    ] ],
    [ "amrex::HypreIJIface", "classamrex_1_1HypreIJIface.html", null ],
    [ "amrex::HypreNodeLap", "classamrex_1_1HypreNodeLap.html", null ],
    [ "amrex::NonLocalBC::Identity", "structamrex_1_1NonLocalBC_1_1Identity.html", null ],
    [ "amrex::BlockMutex::state_t::II", "structamrex_1_1BlockMutex_1_1state__t_1_1II.html", null ],
    [ "amrex::algoim::ImplicitIntegral< M, N, Phi, F >", "structamrex_1_1algoim_1_1ImplicitIntegral.html", null ],
    [ "amrex::algoim::ImplicitIntegral< 0, N, Phi, F >", "structamrex_1_1algoim_1_1ImplicitIntegral_3_010_00_01N_00_01Phi_00_01F_01_4.html", null ],
    [ "amrex::Scan::Type::Inclusive", "structamrex_1_1Scan_1_1Type_1_1Inclusive.html", null ],
    [ "amrex::EB2::IndexSpace", "classamrex_1_1EB2_1_1IndexSpace.html", [
      [ "amrex::EB2::IndexSpaceImp< G >", "classamrex_1_1EB2_1_1IndexSpaceImp.html", null ]
    ] ],
    [ "amrex::IndexType", "classamrex_1_1IndexType.html", null ],
    [ "amrex::InSituBridge", "classamrex_1_1InSituBridge.html", [
      [ "amrex::AmrInSituBridge", "classamrex_1_1AmrInSituBridge.html", null ],
      [ "amrex::AmrMeshInSituBridge", "classamrex_1_1AmrMeshInSituBridge.html", null ]
    ] ],
    [ "amrex::IntDescriptor", "classamrex_1_1IntDescriptor.html", null ],
    [ "integral_constant", null, [
      [ "amrex::GpuTupleSize< GpuTuple< Ts... > >", "structamrex_1_1GpuTupleSize_3_01GpuTuple_3_01Ts_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "amrex::AmrDataAdaptor::InternalsType", "structamrex_1_1AmrDataAdaptor_1_1InternalsType.html", null ],
    [ "amrex::AmrMeshDataAdaptor::InternalsType", "structamrex_1_1AmrMeshDataAdaptor_1_1InternalsType.html", null ],
    [ "amrex::InterpBase", "classamrex_1_1InterpBase.html", [
      [ "amrex::Interpolater", "classamrex_1_1Interpolater.html", [
        [ "amrex::CellBilinear", "classamrex_1_1CellBilinear.html", null ],
        [ "amrex::CellConservativeLinear", "classamrex_1_1CellConservativeLinear.html", [
          [ "amrex::CellConservativeProtected", "classamrex_1_1CellConservativeProtected.html", null ],
          [ "amrex::EBCellConservativeLinear", "classamrex_1_1EBCellConservativeLinear.html", null ]
        ] ],
        [ "amrex::CellConservativeQuartic", "classamrex_1_1CellConservativeQuartic.html", null ],
        [ "amrex::CellQuadratic", "classamrex_1_1CellQuadratic.html", null ],
        [ "amrex::FaceDivFree", "classamrex_1_1FaceDivFree.html", null ],
        [ "amrex::FaceLinear", "classamrex_1_1FaceLinear.html", null ],
        [ "amrex::NodeBilinear", "classamrex_1_1NodeBilinear.html", null ],
        [ "amrex::PCInterp", "classamrex_1_1PCInterp.html", null ]
      ] ],
      [ "amrex::MFInterpolater", "classamrex_1_1MFInterpolater.html", [
        [ "amrex::MFCellBilinear", "classamrex_1_1MFCellBilinear.html", null ],
        [ "amrex::MFCellConsLinInterp", "classamrex_1_1MFCellConsLinInterp.html", [
          [ "amrex::EBMFCellConsLinInterp", "classamrex_1_1EBMFCellConsLinInterp.html", null ]
        ] ],
        [ "amrex::MFNodeBilinear", "classamrex_1_1MFNodeBilinear.html", null ],
        [ "amrex::MFPCInterp", "classamrex_1_1MFPCInterp.html", null ]
      ] ]
    ] ],
    [ "amrex::algoim::Interval", "structamrex_1_1algoim_1_1Interval.html", null ],
    [ "amrex::IntVect", "classamrex_1_1IntVect.html", null ],
    [ "amrex::NeighborParticleContainer< NStructReal, NStructInt, NArrayReal, NArrayInt >::InverseCopyTag", "structamrex_1_1NeighborParticleContainer_1_1InverseCopyTag.html", null ],
    [ "amrex::detail::invoke_result< V, F, Args >", "structamrex_1_1detail_1_1invoke__result.html", null ],
    [ "amrex::detail::invoke_result< decltype(void(INVOKE(std::declval< F >(), std::declval< Args >()...))), F, Args... >", "structamrex_1_1detail_1_1invoke__result_3_01decltype_07void_07INVOKE_07std_1_1declval_3_01F_01_49dd63e63d8c4c4c6d40ab44a59ce8a5b.html", null ],
    [ "amrex::IParser", "classamrex_1_1IParser.html", null ],
    [ "amrex::iparser_assign", "structamrex_1_1iparser__assign.html", null ],
    [ "amrex::iparser_f1", "structamrex_1_1iparser__f1.html", null ],
    [ "amrex::iparser_f2", "structamrex_1_1iparser__f2.html", null ],
    [ "amrex::iparser_f3", "structamrex_1_1iparser__f3.html", null ],
    [ "amrex::iparser_node", "structamrex_1_1iparser__node.html", null ],
    [ "amrex::iparser_number", "structamrex_1_1iparser__number.html", null ],
    [ "amrex::iparser_nvp", "unionamrex_1_1iparser__nvp.html", null ],
    [ "amrex::iparser_symbol", "structamrex_1_1iparser__symbol.html", null ],
    [ "amrex::IParserExeADD", "structamrex_1_1IParserExeADD.html", null ],
    [ "amrex::IParserExeADD_PN", "structamrex_1_1IParserExeADD__PN.html", null ],
    [ "amrex::IParserExeADD_PP", "structamrex_1_1IParserExeADD__PP.html", null ],
    [ "amrex::IParserExeADD_VN", "structamrex_1_1IParserExeADD__VN.html", null ],
    [ "amrex::IParserExeADD_VP", "structamrex_1_1IParserExeADD__VP.html", null ],
    [ "amrex::IParserExecutor< N >", "structamrex_1_1IParserExecutor.html", null ],
    [ "amrex::IParserExeDIV_B", "structamrex_1_1IParserExeDIV__B.html", null ],
    [ "amrex::IParserExeDIV_F", "structamrex_1_1IParserExeDIV__F.html", null ],
    [ "amrex::IParserExeDIV_NV", "structamrex_1_1IParserExeDIV__NV.html", null ],
    [ "amrex::IParserExeDIV_PN", "structamrex_1_1IParserExeDIV__PN.html", null ],
    [ "amrex::IParserExeDIV_PP", "structamrex_1_1IParserExeDIV__PP.html", null ],
    [ "amrex::IParserExeDIV_PV", "structamrex_1_1IParserExeDIV__PV.html", null ],
    [ "amrex::IParserExeDIV_VN", "structamrex_1_1IParserExeDIV__VN.html", null ],
    [ "amrex::IParserExeDIV_VP", "structamrex_1_1IParserExeDIV__VP.html", null ],
    [ "amrex::IParserExeF1", "structamrex_1_1IParserExeF1.html", null ],
    [ "amrex::IParserExeF2_B", "structamrex_1_1IParserExeF2__B.html", null ],
    [ "amrex::IParserExeF2_F", "structamrex_1_1IParserExeF2__F.html", null ],
    [ "amrex::IParserExeIF", "structamrex_1_1IParserExeIF.html", null ],
    [ "amrex::IParserExeJUMP", "structamrex_1_1IParserExeJUMP.html", null ],
    [ "amrex::IParserExeMUL", "structamrex_1_1IParserExeMUL.html", null ],
    [ "amrex::IParserExeMUL_PN", "structamrex_1_1IParserExeMUL__PN.html", null ],
    [ "amrex::IParserExeMUL_PP", "structamrex_1_1IParserExeMUL__PP.html", null ],
    [ "amrex::IParserExeMUL_VN", "structamrex_1_1IParserExeMUL__VN.html", null ],
    [ "amrex::IParserExeMUL_VP", "structamrex_1_1IParserExeMUL__VP.html", null ],
    [ "amrex::IParserExeNEG", "structamrex_1_1IParserExeNEG.html", null ],
    [ "amrex::IParserExeNEG_P", "structamrex_1_1IParserExeNEG__P.html", null ],
    [ "amrex::IParserExeNull", "structamrex_1_1IParserExeNull.html", null ],
    [ "amrex::IParserExeNumber", "structamrex_1_1IParserExeNumber.html", null ],
    [ "amrex::IParserExeSUB", "structamrex_1_1IParserExeSUB.html", null ],
    [ "amrex::IParserExeSUB_PN", "structamrex_1_1IParserExeSUB__PN.html", null ],
    [ "amrex::IParserExeSUB_PP", "structamrex_1_1IParserExeSUB__PP.html", null ],
    [ "amrex::IParserExeSUB_VN", "structamrex_1_1IParserExeSUB__VN.html", null ],
    [ "amrex::IParserExeSUB_VP", "structamrex_1_1IParserExeSUB__VP.html", null ],
    [ "amrex::IParserExeSymbol", "structamrex_1_1IParserExeSymbol.html", null ],
    [ "amrex::IParserStack< N >", "structamrex_1_1IParserStack.html", null ],
    [ "IsDetected", null, [
      [ "amrex::IsCallable< T, Args >", "structamrex_1_1IsCallable.html", null ]
    ] ],
    [ "IsDetectedExact", null, [
      [ "amrex::IsCallableR< R, T, Args >", "structamrex_1_1IsCallableR.html", null ],
      [ "amrex::NonLocalBC::HasInverseMemFn< T >", "structamrex_1_1NonLocalBC_1_1HasInverseMemFn.html", null ],
      [ "amrex::IsCallableR< FAB::value_type, P, Array4< const FAB::value_type >, Dim3, int >", "structamrex_1_1IsCallableR.html", [
        [ "amrex::NonLocalBC::IsFabProjection< P, FAB >", "structamrex_1_1NonLocalBC_1_1IsFabProjection.html", null ]
      ] ]
    ] ],
    [ "amrex::BinIterator< T >::iterator", "structamrex_1_1BinIterator_1_1iterator.html", null ],
    [ "amrex::Neighbors< ParticleType >::iterator", "structamrex_1_1Neighbors_1_1iterator.html", null ],
    [ "amrex::Gpu::range_detail::range_impl< T >::iterator", "structamrex_1_1Gpu_1_1range__detail_1_1range__impl_1_1iterator.html", null ],
    [ "KeepValidFilter", "structKeepValidFilter.html", null ],
    [ "amrex::Gpu::KernelInfo", "classamrex_1_1Gpu_1_1KernelInfo.html", null ],
    [ "amrex::EB2::LatheIF< F >", "classamrex_1_1EB2_1_1LatheIF.html", null ],
    [ "amrex::Gpu::LaunchSafeGuard", "structamrex_1_1Gpu_1_1LaunchSafeGuard.html", null ],
    [ "amrex::LayoutData< T >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< amrex::GpuArray< amrex::MLCellLinOp::BCTL, 2 *AMREX_SPACEDIM > * >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< amrex::PODVector< Int > >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< amrex::Vector< amrex::Vector< amrex::BoundCond > > >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< amrex::Vector< BCTuple > >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< amrex::Vector< RealTuple > >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< GFab >", "classamrex_1_1LayoutData.html", [
      [ "amrex::EB2::MultiGFab", "classamrex_1_1EB2_1_1MultiGFab.html", null ]
    ] ],
    [ "amrex::LayoutData< HYPRE_Int >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< Int >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< PetscInt >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::LayoutData< RealTuple >", "classamrex_1_1LayoutData.html", null ],
    [ "amrex::Less< T >", "structamrex_1_1Less.html", null ],
    [ "amrex::EB2::Level", "classamrex_1_1EB2_1_1Level.html", [
      [ "amrex::EB2::GShopLevel< G >", "classamrex_1_1EB2_1_1GShopLevel.html", null ]
    ] ],
    [ "amrex::LevelBld", "classamrex_1_1LevelBld.html", null ],
    [ "amrex::DistributionMapping::LIpairGT", "structamrex_1_1DistributionMapping_1_1LIpairGT.html", null ],
    [ "amrex::DistributionMapping::LIpairLT", "structamrex_1_1DistributionMapping_1_1LIpairLT.html", null ],
    [ "amrex::LogicalAnd< T >", "structamrex_1_1LogicalAnd.html", null ],
    [ "amrex::LogicalOr< T >", "structamrex_1_1LogicalOr.html", null ],
    [ "amrex::LPInfo", "structamrex_1_1LPInfo.html", null ],
    [ "amrex::MacProjector", "classamrex_1_1MacProjector.html", null ],
    [ "amrex::Gpu::Managed", "structamrex_1_1Gpu_1_1Managed.html", null ],
    [ "amrex::NonLocalBC::MapComponents< Base, Map >", "structamrex_1_1NonLocalBC_1_1MapComponents.html", null ],
    [ "amrex::NeighborParticleContainer< NStructReal, NStructInt, NArrayReal, NArrayInt >::MaskComps", "structamrex_1_1NeighborParticleContainer_1_1MaskComps.html", null ],
    [ "amrex::MemProfiler::MemInfo", "structamrex_1_1MemProfiler_1_1MemInfo.html", null ],
    [ "amrex::FabArrayBase::meminfo", "structamrex_1_1FabArrayBase_1_1meminfo.html", null ],
    [ "amrex::sundials::MemoryHelper", "classamrex_1_1sundials_1_1MemoryHelper.html", null ],
    [ "amrex::MemProfiler", "classamrex_1_1MemProfiler.html", null ],
    [ "amrex::ParallelDescriptor::Message", "classamrex_1_1ParallelDescriptor_1_1Message.html", null ],
    [ "amrex::ForkJoin::MFFork", "structamrex_1_1ForkJoin_1_1MFFork.html", null ],
    [ "amrex::MFInfo", "structamrex_1_1MFInfo.html", null ],
    [ "amrex::MFIter", "classamrex_1_1MFIter.html", [
      [ "amrex::FabSetIter", "classamrex_1_1FabSetIter.html", null ],
      [ "amrex::FillPatchIterator", "classamrex_1_1FillPatchIterator.html", null ],
      [ "amrex::MultiMaskIter", "classamrex_1_1MultiMaskIter.html", null ],
      [ "amrex::ParIterBase< is_const, NStructReal, NStructInt, NArrayReal, NArrayInt, Allocator >", "classamrex_1_1ParIterBase.html", null ],
      [ "amrex::ParIterBase< false, NStructReal, 0, 0, 0, DefaultAllocator >", "classamrex_1_1ParIterBase.html", [
        [ "amrex::ParIter< NStructReal, NStructInt, NArrayReal, NArrayInt, Allocator >", "classamrex_1_1ParIter.html", null ]
      ] ],
      [ "amrex::ParIterBase< true, NStructReal, 0, 0, 0, DefaultAllocator >", "classamrex_1_1ParIterBase.html", [
        [ "amrex::ParConstIter< NStructReal, NStructInt, NArrayReal, NArrayInt, Allocator >", "classamrex_1_1ParConstIter.html", null ]
      ] ]
    ] ],
    [ "amrex::MFItInfo", "structamrex_1_1MFItInfo.html", null ],
    [ "amrex::Minus< T >", "structamrex_1_1Minus.html", null ],
    [ "amrex::MLCGSolver", "classamrex_1_1MLCGSolver.html", null ],
    [ "amrex::MLLinOp", "classamrex_1_1MLLinOp.html", [
      [ "amrex::MLCellLinOp", "classamrex_1_1MLCellLinOp.html", [
        [ "amrex::MLCellABecLap", "classamrex_1_1MLCellABecLap.html", [
          [ "amrex::MLABecLaplacian", "classamrex_1_1MLABecLaplacian.html", [
            [ "amrex::MLTensorOp", "classamrex_1_1MLTensorOp.html", null ]
          ] ],
          [ "amrex::MLALaplacian", "classamrex_1_1MLALaplacian.html", null ],
          [ "amrex::MLEBABecLap", "classamrex_1_1MLEBABecLap.html", [
            [ "amrex::MLEBTensorOp", "classamrex_1_1MLEBTensorOp.html", null ]
          ] ],
          [ "amrex::MLPoisson", "classamrex_1_1MLPoisson.html", null ]
        ] ]
      ] ],
      [ "amrex::MLNodeLinOp", "classamrex_1_1MLNodeLinOp.html", [
        [ "amrex::MLEBNodeFDLaplacian", "classamrex_1_1MLEBNodeFDLaplacian.html", null ],
        [ "amrex::MLNodeLaplacian", "classamrex_1_1MLNodeLaplacian.html", null ],
        [ "amrex::MLNodeTensorLaplacian", "classamrex_1_1MLNodeTensorLaplacian.html", null ]
      ] ]
    ] ],
    [ "amrex::MLMG", "classamrex_1_1MLMG.html", null ],
    [ "MPI_Status", "structMPI__Status.html", null ],
    [ "amrex::ParallelDescriptor::Mpi_typemap< T >", "structamrex_1_1ParallelDescriptor_1_1Mpi__typemap.html", null ],
    [ "amrex::MultiArray4< T >", "structamrex_1_1MultiArray4.html", null ],
    [ "amrex::MultiArray4< value_type >", "structamrex_1_1MultiArray4.html", null ],
    [ "amrex::MultiArray4< value_type const >", "structamrex_1_1MultiArray4.html", null ],
    [ "amrex::NonLocalBC::MultiBlockIndexMapping", "structamrex_1_1NonLocalBC_1_1MultiBlockIndexMapping.html", null ],
    [ "amrex::MultiCutFab", "classamrex_1_1MultiCutFab.html", null ],
    [ "amrex::MultiMask", "classamrex_1_1MultiMask.html", null ],
    [ "CommProfStats::NameTagEntry", "structCommProfStats_1_1NameTagEntry.html", null ],
    [ "amrex::MemProfiler::NBuildsInfo", "structamrex_1_1MemProfiler_1_1NBuildsInfo.html", null ],
    [ "amrex::EB2::Neighbor", "structamrex_1_1EB2_1_1Neighbor.html", null ],
    [ "amrex::NeighborCode", "structamrex_1_1NeighborCode.html", null ],
    [ "amrex::NeighborParticleContainer< NStructReal, NStructInt, NArrayReal, NArrayInt >::NeighborCommTag", "structamrex_1_1NeighborParticleContainer_1_1NeighborCommTag.html", null ],
    [ "amrex::NeighborParticleContainer< NStructReal, NStructInt, NArrayReal, NArrayInt >::NeighborCopyTag", "structamrex_1_1NeighborParticleContainer_1_1NeighborCopyTag.html", null ],
    [ "amrex::NeighborData< ParticleType >", "structamrex_1_1NeighborData.html", null ],
    [ "amrex::NeighborParticleContainer< NStructReal, NStructInt, NArrayReal, NArrayInt >::NeighborIndexMap", "structamrex_1_1NeighborParticleContainer_1_1NeighborIndexMap.html", null ],
    [ "amrex::NeighborList< ParticleType >", "classamrex_1_1NeighborList.html", null ],
    [ "amrex::Neighbors< ParticleType >", "structamrex_1_1Neighbors.html", null ],
    [ "amrex::NeighborParticleContainer< NStructReal, NStructInt, NArrayReal, NArrayInt >::NeighborTask", "structamrex_1_1NeighborParticleContainer_1_1NeighborTask.html", null ],
    [ "amrex::NeighborUnpackPolicy", "structamrex_1_1NeighborUnpackPolicy.html", null ],
    [ "amrex::NFilesIter", "classamrex_1_1NFilesIter.html", null ],
    [ "amrex::NodalProjector", "classamrex_1_1NodalProjector.html", null ],
    [ "amrex::EArena::Node", "structamrex_1_1EArena_1_1Node.html", null ],
    [ "amrex::algoim::QuadratureRule::Node", "structamrex_1_1algoim_1_1QuadratureRule_1_1Node.html", null ],
    [ "amrex::CArena::Node", "classamrex_1_1CArena_1_1Node.html", null ],
    [ "amrex::NonLocalBC::NoLocalCopy", "structamrex_1_1NonLocalBC_1_1NoLocalCopy.html", null ],
    [ "amrex::detail::Nonesuch", "structamrex_1_1detail_1_1Nonesuch.html", null ],
    [ "amrex::NullInterpHook< FAB >", "structamrex_1_1NullInterpHook.html", null ],
    [ "amrex::NumComps", "structamrex_1_1NumComps.html", null ],
    [ "amrex::BinPolicy::OpenMPBinPolicy", "structamrex_1_1BinPolicy_1_1OpenMPBinPolicy.html", null ],
    [ "amrex::OrderedBoxes", "classamrex_1_1OrderedBoxes.html", null ],
    [ "amrex::Orientation", "classamrex_1_1Orientation.html", null ],
    [ "amrex::OrientationIter", "classamrex_1_1OrientationIter.html", null ],
    [ "amrex::InSituUtils::orOp< n_t >", "structamrex_1_1InSituUtils_1_1orOp.html", null ],
    [ "amrex::NonLocalBC::PackComponents", "structamrex_1_1NonLocalBC_1_1PackComponents.html", [
      [ "amrex::NonLocalBC::ApplyDtosAndProjectionOnReciever< DTOS, FabProj >", "structamrex_1_1NonLocalBC_1_1ApplyDtosAndProjectionOnReciever.html", null ]
    ] ],
    [ "amrex::FabArrayBase::ParForInfo", "structamrex_1_1FabArrayBase_1_1ParForInfo.html", null ],
    [ "amrex::ParGDBBase", "classamrex_1_1ParGDBBase.html", [
      [ "amrex::AmrParGDB", "classamrex_1_1AmrParGDB.html", null ],
      [ "amrex::ParGDB", "classamrex_1_1ParGDB.html", null ]
    ] ],
    [ "amrex::ParmParse", "classamrex_1_1ParmParse.html", null ],
    [ "amrex::Parser", "classamrex_1_1Parser.html", null ],
    [ "amrex::parser_assign", "structamrex_1_1parser__assign.html", null ],
    [ "amrex::parser_f1", "structamrex_1_1parser__f1.html", null ],
    [ "amrex::parser_f2", "structamrex_1_1parser__f2.html", null ],
    [ "amrex::parser_f3", "structamrex_1_1parser__f3.html", null ],
    [ "amrex::parser_node", "structamrex_1_1parser__node.html", null ],
    [ "amrex::parser_number", "structamrex_1_1parser__number.html", null ],
    [ "amrex::parser_nvp", "unionamrex_1_1parser__nvp.html", null ],
    [ "amrex::parser_symbol", "structamrex_1_1parser__symbol.html", null ],
    [ "amrex::ParserExeADD", "structamrex_1_1ParserExeADD.html", null ],
    [ "amrex::ParserExeADD_PN", "structamrex_1_1ParserExeADD__PN.html", null ],
    [ "amrex::ParserExeADD_PP", "structamrex_1_1ParserExeADD__PP.html", null ],
    [ "amrex::ParserExeADD_VN", "structamrex_1_1ParserExeADD__VN.html", null ],
    [ "amrex::ParserExeADD_VP", "structamrex_1_1ParserExeADD__VP.html", null ],
    [ "amrex::ParserExecutor< N >", "structamrex_1_1ParserExecutor.html", null ],
    [ "amrex::ParserExecutor< 3 >", "structamrex_1_1ParserExecutor.html", null ],
    [ "amrex::ParserExeDIV_B", "structamrex_1_1ParserExeDIV__B.html", null ],
    [ "amrex::ParserExeDIV_F", "structamrex_1_1ParserExeDIV__F.html", null ],
    [ "amrex::ParserExeDIV_PN", "structamrex_1_1ParserExeDIV__PN.html", null ],
    [ "amrex::ParserExeDIV_PP", "structamrex_1_1ParserExeDIV__PP.html", null ],
    [ "amrex::ParserExeDIV_VN", "structamrex_1_1ParserExeDIV__VN.html", null ],
    [ "amrex::ParserExeDIV_VP", "structamrex_1_1ParserExeDIV__VP.html", null ],
    [ "amrex::ParserExeF1", "structamrex_1_1ParserExeF1.html", null ],
    [ "amrex::ParserExeF2_B", "structamrex_1_1ParserExeF2__B.html", null ],
    [ "amrex::ParserExeF2_F", "structamrex_1_1ParserExeF2__F.html", null ],
    [ "amrex::ParserExeIF", "structamrex_1_1ParserExeIF.html", null ],
    [ "amrex::ParserExeJUMP", "structamrex_1_1ParserExeJUMP.html", null ],
    [ "amrex::ParserExeMUL", "structamrex_1_1ParserExeMUL.html", null ],
    [ "amrex::ParserExeMUL_PN", "structamrex_1_1ParserExeMUL__PN.html", null ],
    [ "amrex::ParserExeMUL_PP", "structamrex_1_1ParserExeMUL__PP.html", null ],
    [ "amrex::ParserExeMUL_VN", "structamrex_1_1ParserExeMUL__VN.html", null ],
    [ "amrex::ParserExeMUL_VP", "structamrex_1_1ParserExeMUL__VP.html", null ],
    [ "amrex::ParserExeNEG", "structamrex_1_1ParserExeNEG.html", null ],
    [ "amrex::ParserExeNEG_P", "structamrex_1_1ParserExeNEG__P.html", null ],
    [ "amrex::ParserExeNull", "structamrex_1_1ParserExeNull.html", null ],
    [ "amrex::ParserExeNumber", "structamrex_1_1ParserExeNumber.html", null ],
    [ "amrex::ParserExeSUB", "structamrex_1_1ParserExeSUB.html", null ],
    [ "amrex::ParserExeSUB_PN", "structamrex_1_1ParserExeSUB__PN.html", null ],
    [ "amrex::ParserExeSUB_PP", "structamrex_1_1ParserExeSUB__PP.html", null ],
    [ "amrex::ParserExeSUB_VN", "structamrex_1_1ParserExeSUB__VN.html", null ],
    [ "amrex::ParserExeSUB_VP", "structamrex_1_1ParserExeSUB__VP.html", null ],
    [ "amrex::ParserExeSymbol", "structamrex_1_1ParserExeSymbol.html", null ],
    [ "amrex::ParserStack< N >", "structamrex_1_1ParserStack.html", null ],
    [ "amrex::ParticleArray< ContainerType, ParticleType, DataLayoutTag >", "structamrex_1_1ParticleArray.html", null ],
    [ "amrex::ParticleArrayAccessor< ParticleType, DataLayoutTag >", "structamrex_1_1ParticleArrayAccessor.html", null ],
    [ "amrex::ParticleBase< T, NReal, NInt >", "structamrex_1_1ParticleBase.html", null ],
    [ "amrex::ParticleBase< ParticleReal, T_NReal, 0 >", "structamrex_1_1ParticleBase.html", [
      [ "amrex::Particle< T_NReal, T_NInt >", "structamrex_1_1Particle.html", null ]
    ] ],
    [ "amrex::ParticleBase< T, 0, 0 >", "structamrex_1_1ParticleBase_3_01T_00_010_00_010_01_4.html", null ],
    [ "amrex::ParticleBase< T, 0, NInt >", "structamrex_1_1ParticleBase_3_01T_00_010_00_01NInt_01_4.html", null ],
    [ "amrex::ParticleBase< T, NReal, 0 >", "structamrex_1_1ParticleBase_3_01T_00_01NReal_00_010_01_4.html", null ],
    [ "amrex::ParticleBufferMap", "classamrex_1_1ParticleBufferMap.html", null ],
    [ "amrex::ParticleCommData", "structamrex_1_1ParticleCommData.html", null ],
    [ "amrex::ParticleContainer< T_NStructReal, T_NStructInt, T_NArrayReal, T_NArrayInt, Allocator >", "classamrex_1_1ParticleContainer.html", null ],
    [ "amrex::ParticleContainer< AMREX_SPACEDIM >", "classamrex_1_1ParticleContainer.html", [
      [ "amrex::TracerParticleContainer", "classamrex_1_1TracerParticleContainer.html", [
        [ "amrex::AmrTracerParticleContainer", "classamrex_1_1AmrTracerParticleContainer.html", null ]
      ] ]
    ] ],
    [ "amrex::ParticleContainer< NStructReal, 0, 0, 0, DefaultAllocator >", "classamrex_1_1ParticleContainer.html", [
      [ "amrex::AmrParticleContainer< NStructReal, NStructInt, NArrayReal, NArrayInt, Allocator >", "classamrex_1_1AmrParticleContainer.html", null ]
    ] ],
    [ "amrex::ParticleContainer< NStructReal, NStructInt, 0, 0 >", "classamrex_1_1ParticleContainer.html", [
      [ "amrex::NeighborParticleContainer< NStructReal, NStructInt, NArrayReal, NArrayInt >", "classamrex_1_1NeighborParticleContainer.html", null ]
    ] ],
    [ "amrex::ParticleContainerBase", "classamrex_1_1ParticleContainerBase.html", null ],
    [ "amrex::ParticleCopyOp", "structamrex_1_1ParticleCopyOp.html", null ],
    [ "amrex::ParticleCopyPlan", "structamrex_1_1ParticleCopyPlan.html", null ],
    [ "amrex::ParticleCPUWrapper", "structamrex_1_1ParticleCPUWrapper.html", null ],
    [ "amrex::ParticleIDWrapper", "structamrex_1_1ParticleIDWrapper.html", null ],
    [ "amrex::ParticleInitType< NStructReal, NStructInt, NArrayReal, NArrayInt >", "structamrex_1_1ParticleInitType.html", null ],
    [ "amrex::ParticleLocator< Bins >", "classamrex_1_1ParticleLocator.html", null ],
    [ "amrex::ParticleLocData", "structamrex_1_1ParticleLocData.html", null ],
    [ "amrex::ParticleTile< NStructReal, NStructInt, NArrayReal, NArrayInt, Allocator >", "structamrex_1_1ParticleTile.html", null ],
    [ "amrex::ParticleTileData< NStructReal, NStructInt, NArrayReal, NArrayInt >", "structamrex_1_1ParticleTileData.html", null ],
    [ "amrex::PCData< FAB >", "structamrex_1_1PCData.html", null ],
    [ "amrex::Periodicity", "classamrex_1_1Periodicity.html", null ],
    [ "amrex::VisMF::PersistentIFStream", "structamrex_1_1VisMF_1_1PersistentIFStream.html", null ],
    [ "amrex::PETScABecLap", "classamrex_1_1PETScABecLap.html", null ],
    [ "amrex::PhysBCFunct< F >", "classamrex_1_1PhysBCFunct.html", null ],
    [ "amrex::PhysBCFunctNoOp", "classamrex_1_1PhysBCFunctNoOp.html", null ],
    [ "amrex::Gpu::Pinned", "structamrex_1_1Gpu_1_1Pinned.html", null ],
    [ "amrex::PlotFileData", "classamrex_1_1PlotFileData.html", null ],
    [ "amrex::PlotFileDataImpl", "classamrex_1_1PlotFileDataImpl.html", null ],
    [ "amrex::Plus< T >", "structamrex_1_1Plus.html", null ],
    [ "amrex::NonLocalBC::PolarFn", "structamrex_1_1NonLocalBC_1_1PolarFn.html", null ],
    [ "amrex::NonLocalBC::PolarFn2", "structamrex_1_1NonLocalBC_1_1PolarFn2.html", null ],
    [ "sdcquadrature_mod::poly_eval", "interfacesdcquadrature__mod_1_1poly__eval.html", null ],
    [ "amrex::PolymorphicAllocator< T >", "classamrex_1_1PolymorphicAllocator.html", null ],
    [ "amrex::EB2::PolynomialIF", "classamrex_1_1EB2_1_1PolynomialIF.html", null ],
    [ "amrex::EB2::PolyTerm", "classamrex_1_1EB2_1_1PolyTerm.html", null ],
    [ "amrex::ParmParse::PP_entry", "structamrex_1_1ParmParse_1_1PP__entry.html", null ],
    [ "amrex::Print", "classamrex_1_1Print.html", [
      [ "amrex::AllPrint", "classamrex_1_1AllPrint.html", null ]
    ] ],
    [ "amrex::PrintToFile", "classamrex_1_1PrintToFile.html", [
      [ "amrex::AllPrintToFile", "classamrex_1_1AllPrintToFile.html", null ]
    ] ],
    [ "process_topology_t", "structprocess__topology__t.html", null ],
    [ "amrex::ParallelDescriptor::ProcessTeam", "structamrex_1_1ParallelDescriptor_1_1ProcessTeam.html", null ],
    [ "amrex::TinyProfiler::ProcStats", "structamrex_1_1TinyProfiler_1_1ProcStats.html", null ],
    [ "amrex::algoim::PsiCode< N >", "structamrex_1_1algoim_1_1PsiCode.html", null ],
    [ "amrex::PsiCode< N >, 1<<(N - 1)>", "structamrex_1_1GpuArray.html", null ],
    [ "amrex::algoim::QuadratureRule", "structamrex_1_1algoim_1_1QuadratureRule.html", null ],
    [ "amrex::RandomEngine", "structamrex_1_1RandomEngine.html", null ],
    [ "amrex::Gpu::range_detail::range_impl< T >", "structamrex_1_1Gpu_1_1range__detail_1_1range__impl.html", null ],
    [ "amrex::RealBox", "classamrex_1_1RealBox.html", null ],
    [ "amrex::RealDescriptor", "classamrex_1_1RealDescriptor.html", null ],
    [ "amrex::RealVect", "classamrex_1_1RealVect.html", null ],
    [ "hacc::AlignedAllocator< T, N >::rebind< U >", "structhacc_1_1AlignedAllocator_1_1rebind.html", null ],
    [ "amrex::ParmParse::Record", "classamrex_1_1ParmParse_1_1Record.html", null ],
    [ "amrex::RedistributeUnpackPolicy", "structamrex_1_1RedistributeUnpackPolicy.html", null ],
    [ "amrex::ReduceData< Ts >", "classamrex_1_1ReduceData.html", null ],
    [ "amrex::ReduceOpLogicalAnd", "structamrex_1_1ReduceOpLogicalAnd.html", null ],
    [ "amrex::ReduceOpLogicalOr", "structamrex_1_1ReduceOpLogicalOr.html", null ],
    [ "amrex::ReduceOpMax", "structamrex_1_1ReduceOpMax.html", null ],
    [ "amrex::ReduceOpMin", "structamrex_1_1ReduceOpMin.html", null ],
    [ "amrex::ReduceOps< Ps >", "classamrex_1_1ReduceOps.html", null ],
    [ "amrex::ReduceOpSum", "structamrex_1_1ReduceOpSum.html", null ],
    [ "CommProfStats::ReductionEntry", "structCommProfStats_1_1ReductionEntry.html", null ],
    [ "amrex::DistributionMapping::Ref", "structamrex_1_1DistributionMapping_1_1Ref.html", null ],
    [ "amrex::ref_wrapper< T >", "classamrex_1_1ref__wrapper.html", null ],
    [ "amrex::DistributionMapping::RefID", "structamrex_1_1DistributionMapping_1_1RefID.html", null ],
    [ "amrex::BoxArray::RefID", "structamrex_1_1BoxArray_1_1RefID.html", null ],
    [ "amrex::FabArrayBase::RegionTag", "structamrex_1_1FabArrayBase_1_1RegionTag.html", null ],
    [ "amrex::Scan::RetSum", "structamrex_1_1Scan_1_1RetSum.html", null ],
    [ "amrex::NonLocalBC::Rotate180Fn", "structamrex_1_1NonLocalBC_1_1Rotate180Fn.html", null ],
    [ "amrex::NonLocalBC::Rotate90ClockWise", "structamrex_1_1NonLocalBC_1_1Rotate90ClockWise.html", null ],
    [ "amrex::NonLocalBC::Rotate90CounterClockWise", "structamrex_1_1NonLocalBC_1_1Rotate90CounterClockWise.html", null ],
    [ "amrex::NonLocalBC::Rotate90DstToSrc", "structamrex_1_1NonLocalBC_1_1Rotate90DstToSrc.html", null ],
    [ "amrex::EB2::RotationIF< F >", "classamrex_1_1EB2_1_1RotationIF.html", null ],
    [ "amrex::Same< T, U1, Us >", "structamrex_1_1Same.html", null ],
    [ "amrex::Same< T, U >", "structamrex_1_1Same_3_01T_00_01U_01_4.html", null ],
    [ "amrex::EB2::ScaleIF< F >", "classamrex_1_1EB2_1_1ScaleIF.html", null ],
    [ "amrex::Gpu::ScopedDefaultStream", "structamrex_1_1Gpu_1_1ScopedDefaultStream.html", null ],
    [ "SDCstruct", "classSDCstruct.html", null ],
    [ "CommProfStats::SendRecvPair", "structCommProfStats_1_1SendRecvPair.html", [
      [ "CommProfStats::SendRecvPairUnpaired", "structCommProfStats_1_1SendRecvPairUnpaired.html", null ]
    ] ],
    [ "amrex::BinPolicy::SerialBinPolicy", "structamrex_1_1BinPolicy_1_1SerialBinPolicy.html", null ],
    [ "amrex::Gpu::SharedMemory< T >", "structamrex_1_1Gpu_1_1SharedMemory.html", null ],
    [ "amrex::Gpu::SharedMemory< bool >", "structamrex_1_1Gpu_1_1SharedMemory_3_01bool_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< char >", "structamrex_1_1Gpu_1_1SharedMemory_3_01char_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< double >", "structamrex_1_1Gpu_1_1SharedMemory_3_01double_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< float >", "structamrex_1_1Gpu_1_1SharedMemory_3_01float_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< int >", "structamrex_1_1Gpu_1_1SharedMemory_3_01int_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< long >", "structamrex_1_1Gpu_1_1SharedMemory_3_01long_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< long long >", "structamrex_1_1Gpu_1_1SharedMemory_3_01long_01long_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< short >", "structamrex_1_1Gpu_1_1SharedMemory_3_01short_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< unsigned char >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01char_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< unsigned int >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01int_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< unsigned long >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01long_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< unsigned long long >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01long_01long_01_4.html", null ],
    [ "amrex::Gpu::SharedMemory< unsigned short >", "structamrex_1_1Gpu_1_1SharedMemory_3_01unsigned_01short_01_4.html", null ],
    [ "amrex::IntVect::shift_hasher", "classamrex_1_1IntVect_1_1shift__hasher.html", null ],
    [ "amrex::FabArray< FAB >::ShMem", "structamrex_1_1FabArray_1_1ShMem.html", null ],
    [ "amrex::SparseBinIteratorFactory< T >", "structamrex_1_1SparseBinIteratorFactory.html", null ],
    [ "amrex::SparseBins< T >", "classamrex_1_1SparseBins.html", null ],
    [ "amrex::EB2::SplineIF", "classamrex_1_1EB2_1_1SplineIF.html", null ],
    [ "amrex::SrcComp", "structamrex_1_1SrcComp.html", null ],
    [ "amrex::BlockMutex::state_t", "unionamrex_1_1BlockMutex_1_1state__t.html", null ],
    [ "amrex::StateData", "classamrex_1_1StateData.html", null ],
    [ "amrex::StateDataPhysBCFunct", "classamrex_1_1StateDataPhysBCFunct.html", null ],
    [ "amrex::StateDescriptor", "classamrex_1_1StateDescriptor.html", null ],
    [ "amrex::InSituUtils::StateMap", "classamrex_1_1InSituUtils_1_1StateMap.html", [
      [ "amrex::InSituUtils::DescriptorMap", "classamrex_1_1InSituUtils_1_1DescriptorMap.html", null ],
      [ "amrex::InSituUtils::MeshStateMap", "classamrex_1_1InSituUtils_1_1MeshStateMap.html", null ]
    ] ],
    [ "amrex::DeriveRec::StateRange", "structamrex_1_1DeriveRec_1_1StateRange.html", null ],
    [ "amrex::TinyProfiler::Stats", "structamrex_1_1TinyProfiler_1_1Stats.html", null ],
    [ "amrex::STLtools", "classamrex_1_1STLtools.html", null ],
    [ "amrex::Gpu::StreamIter", "classamrex_1_1Gpu_1_1StreamIter.html", null ],
    [ "amrex::Gpu::StreamItInfo", "structamrex_1_1Gpu_1_1StreamItInfo.html", null ],
    [ "amrex::StreamRetry", "classamrex_1_1StreamRetry.html", null ],
    [ "amrex::StructOfArrays< NReal, NInt, Allocator >", "structamrex_1_1StructOfArrays.html", null ],
    [ "amrex::StructOfArrays< NArrayReal, NArrayInt, DefaultAllocator >", "structamrex_1_1StructOfArrays.html", null ],
    [ "amrex::Scan::detail::STVA< T >", "structamrex_1_1Scan_1_1detail_1_1STVA.html", null ],
    [ "amrex::Scan::detail::STVA< U >", "structamrex_1_1Scan_1_1detail_1_1STVA.html", null ],
    [ "amrex::NonLocalBC::SwapComponents< I, J >", "structamrex_1_1NonLocalBC_1_1SwapComponents.html", null ],
    [ "amrex::NonLocalBC::SwapComponents< I, -1 >", "structamrex_1_1NonLocalBC_1_1SwapComponents_3_01I_00_01-1_01_4.html", null ],
    [ "amrex::NonLocalBC::SwapComponents<-1, -1 >", "structamrex_1_1NonLocalBC_1_1SwapComponents_3-1_00_01-1_01_4.html", null ],
    [ "amrex::NonLocalBC::SwapComponents<-1, J >", "structamrex_1_1NonLocalBC_1_1SwapComponents_3-1_00_01J_01_4.html", null ],
    [ "amrex::MFUtil::SymmetricGhost< T >", "structamrex_1_1MFUtil_1_1SymmetricGhost.html", null ],
    [ "amrex::TheFaArenaDeleter", "structamrex_1_1TheFaArenaDeleter.html", null ],
    [ "amrex::FabArrayBase::TileArray", "structamrex_1_1FabArrayBase_1_1TileArray.html", null ],
    [ "amrex::TileSize", "structamrex_1_1TileSize.html", null ],
    [ "amrex::StateData::TimeInterval", "structamrex_1_1StateData_1_1TimeInterval.html", null ],
    [ "BLProfStats::TimeRange", "structBLProfStats_1_1TimeRange.html", null ],
    [ "BLProfStats::TimeRangeCompare", "structBLProfStats_1_1TimeRangeCompare.html", null ],
    [ "amrex::TinyProfiler", "classamrex_1_1TinyProfiler.html", null ],
    [ "amrex::TinyProfileRegion", "classamrex_1_1TinyProfileRegion.html", null ],
    [ "TransformerGhost", "structTransformerGhost.html", null ],
    [ "TransformerVirt", "structTransformerVirt.html", null ],
    [ "amrex::EB2::TranslationIF< F >", "classamrex_1_1EB2_1_1TranslationIF.html", null ],
    [ "true_type", null, [
      [ "amrex::Conjunction<... >", "structamrex_1_1Conjunction.html", null ],
      [ "amrex::DefinitelyNotHostRunnable< T, std::enable_if_t< __nv_is_extended_device_lambda_closure_type(T)> >", "structamrex_1_1DefinitelyNotHostRunnable_3_01T_00_01std_1_1enable__if__t_3_01____nv__is__extendecedf017524586c3f34ab1174adfd1f3d.html", null ],
      [ "amrex::EB2::IsGPUable< ComplementIF< F >, typename std::enable_if< IsGPUable< F >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01ComplementIF_3_01F_01_4_00_01typename_01std_1_1enable__if_3_439214b16f92fe663637b42c0a5a5552.html", null ],
      [ "amrex::EB2::IsGPUable< D, typename std::enable_if< std::is_base_of< GPUable, D >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01D_00_01typename_01std_1_1enable__if_3_01std_1_1is__base__of_e7975428109c6f3d89c9f8ba8c25626f.html", null ],
      [ "amrex::EB2::IsGPUable< DifferenceIF< F, G >, typename std::enable_if< IsGPUable< F >::value &&IsGPUable< G >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01DifferenceIF_3_01F_00_01G_01_4_00_01typename_01std_1_1enableac26215ba9e0277ee7231118dc9a8a74.html", null ],
      [ "amrex::EB2::IsGPUable< ExtrusionIF< F >, typename std::enable_if< IsGPUable< F >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01ExtrusionIF_3_01F_01_4_00_01typename_01std_1_1enable__if_3_09ce565cdabb0194a6744226a21d9e2e3.html", null ],
      [ "amrex::EB2::IsGPUable< IntersectionIF< F >, typename std::enable_if< IsGPUable< F >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01IntersectionIF_3_01F_01_4_00_01typename_01std_1_1enable__if_f70fe5a0af601f73704d1e7de99c14ec.html", null ],
      [ "amrex::EB2::IsGPUable< LatheIF< F >, typename std::enable_if< IsGPUable< F >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01LatheIF_3_01F_01_4_00_01typename_01std_1_1enable__if_3_01IsG870c79fcc93b5ecb25be1ee2def9f2cf.html", null ],
      [ "amrex::EB2::IsGPUable< RotationIF< F >, typename std::enable_if< IsGPUable< F >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01RotationIF_3_01F_01_4_00_01typename_01std_1_1enable__if_3_01b6ccedc39c7ac77911bc5f24c7580486.html", null ],
      [ "amrex::EB2::IsGPUable< ScaleIF< F >, typename std::enable_if< IsGPUable< F >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01ScaleIF_3_01F_01_4_00_01typename_01std_1_1enable__if_3_01IsGb66e057f4b07510742d8ce2847c0a0a3.html", null ],
      [ "amrex::EB2::IsGPUable< TranslationIF< F >, typename std::enable_if< IsGPUable< F >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01TranslationIF_3_01F_01_4_00_01typename_01std_1_1enable__if_399859b540a9f6f2c562d54bd4e0f45b9.html", null ],
      [ "amrex::EB2::IsGPUable< UnionIF< F >, typename std::enable_if< IsGPUable< F >::value >::type >", "structamrex_1_1EB2_1_1IsGPUable_3_01UnionIF_3_01F_01_4_00_01typename_01std_1_1enable__if_3_01IsG689753bc6f6f97a7132aea5fbd359250.html", null ],
      [ "amrex::HasAtomicAdd< double >", "structamrex_1_1HasAtomicAdd_3_01double_01_4.html", null ],
      [ "amrex::HasAtomicAdd< float >", "structamrex_1_1HasAtomicAdd_3_01float_01_4.html", null ],
      [ "amrex::HasAtomicAdd< int >", "structamrex_1_1HasAtomicAdd_3_01int_01_4.html", null ],
      [ "amrex::HasAtomicAdd< long >", "structamrex_1_1HasAtomicAdd_3_01long_01_4.html", null ],
      [ "amrex::HasAtomicAdd< unsigned int >", "structamrex_1_1HasAtomicAdd_3_01unsigned_01int_01_4.html", null ],
      [ "amrex::HasAtomicAdd< unsigned long long >", "structamrex_1_1HasAtomicAdd_3_01unsigned_01long_01long_01_4.html", null ],
      [ "amrex::HasMultiComp< A, Enable >::type", "structamrex_1_1HasMultiComp_1_1type.html", null ],
      [ "amrex::IsBaseFab< D, typename std::enable_if< std::is_base_of< BaseFab< typename D::value_type >, D >::value >::type >", "structamrex_1_1IsBaseFab_3_01D_00_01typename_01std_1_1enable__if_3_01std_1_1is__base__of_3_01Basc4401839a878456c6d47850080d07e31.html", null ],
      [ "amrex::IsFabArray< D, typename std::enable_if< std::is_base_of< FabArray< typename D::FABType::value_type >, D >::value >::type >", "structamrex_1_1IsFabArray_3_01D_00_01typename_01std_1_1enable__if_3_01std_1_1is__base__of_3_01Fa50eb808c2316c63b70b55cab20dbec23.html", null ],
      [ "amrex::IsStoreAtomic< EBCellFlag >", "structamrex_1_1IsStoreAtomic_3_01EBCellFlag_01_4.html", null ],
      [ "amrex::MaybeDeviceRunnable< T, Enable >", "structamrex_1_1MaybeDeviceRunnable.html", null ],
      [ "amrex::MaybeHostDeviceRunnable< T, Enable >", "structamrex_1_1MaybeHostDeviceRunnable.html", null ],
      [ "amrex::RunOnGpu< ArenaAllocator< T > >", "structamrex_1_1RunOnGpu_3_01ArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "amrex::RunOnGpu< AsyncArenaAllocator< T > >", "structamrex_1_1RunOnGpu_3_01AsyncArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "amrex::RunOnGpu< DeviceArenaAllocator< T > >", "structamrex_1_1RunOnGpu_3_01DeviceArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "amrex::RunOnGpu< ManagedArenaAllocator< T > >", "structamrex_1_1RunOnGpu_3_01ManagedArenaAllocator_3_01T_01_4_01_4.html", null ],
      [ "amrex::Conjunction< IsCallableR< Dim3, IndexMap &, const Dim3 & >, HasInverseMemFn< const IndexMap & > >", "structamrex_1_1Conjunction.html", [
        [ "amrex::NonLocalBC::IsIndexMapping< IndexMap >", "structamrex_1_1NonLocalBC_1_1IsIndexMapping.html", null ]
      ] ],
      [ "amrex::Conjunction< IsDetected< LocalCopy_t, DP &, FabArray< FAB > &, const FabArray< FAB > &, const FabArrayBase::CopyComTagsContainer & >, IsDetected< PrepareSendBuffers_t, DP &, FabArray< FAB > &, const FabArray< FAB > &, CommData &, const FabArrayBase::MapOfCopyComTagContainers & >, IsDetected< PrepareRecvBuffers_t, DP &, FabArray< FAB > &, const FabArray< FAB > &, CommData &, const FabArrayBase::MapOfCopyComTagContainers & >, IsDetected< PackSendBuffers_t, DP &, const FabArray< FAB > &, CommData & >, IsDetected< UnpackRecvBuffers_t, DP &, FabArray< FAB > &, CommData & > >", "structamrex_1_1Conjunction.html", [
        [ "amrex::NonLocalBC::IsDataPacking< DP, FAB >", "structamrex_1_1NonLocalBC_1_1IsDataPacking.html", null ]
      ] ]
    ] ],
    [ "amrex::BaseUmap< T >::Tuple", "structamrex_1_1BaseUmap_1_1Tuple.html", null ],
    [ "amrex::detail::tuple_cat_result<... >", "structamrex_1_1detail_1_1tuple__cat__result.html", null ],
    [ "amrex::detail::tuple_cat_result< GpuTuple< T1s... >, GpuTuple< T2s... >, TPs... >", "structamrex_1_1detail_1_1tuple__cat__result_3_01GpuTuple_3_01T1s_8_8_8_01_4_00_01GpuTuple_3_01T2e7f956a9a5fbb5ccc01506013b6ed802.html", null ],
    [ "amrex::detail::tuple_cat_result< GpuTuple< Ts... > >", "structamrex_1_1detail_1_1tuple__cat__result_3_01GpuTuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "type", null, [
      [ "amrex::IsMultiFabIterator< T >", "structamrex_1_1IsMultiFabIterator.html", null ]
    ] ],
    [ "amrex::detail::unwrap< T >", "structamrex_1_1detail_1_1unwrap.html", null ],
    [ "amrex::detail::unwrap< std::reference_wrapper< T > >", "structamrex_1_1detail_1_1unwrap_3_01std_1_1reference__wrapper_3_01T_01_4_01_4.html", null ],
    [ "amrex::AMRErrorTag::UserFunc", "structamrex_1_1AMRErrorTag_1_1UserFunc.html", null ],
    [ "vector", null, [
      [ "amrex::Vector< T, Allocator >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::BCRec >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::BLProfiler::CallStats >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::BLProfiler::CommStats >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::BLProfiler::RStartStop >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Box >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::BoxArray >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::BoxList >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::DataServices * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::distFcnElement2d * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::DistributionMapping >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::EB2::Edge >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::EB2::GShopLevel< G > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::EB2::PolyTerm >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::ForkJoin::ComponentSet >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Geometry >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::GpuArray< amrex::MLCellLinOp::BCTL, 2 *AMREX_SPACEDIM > * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::InterpBase * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::IntVect >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::MultiFab * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::MultiFab >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::MultiMask >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::NeighborParticleContainer::NeighborCommTag >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::ParticleLocator< amrex::DenseBins< amrex::Box > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::ParticleLocator< Bins > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::PODVector< Int > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::StateData >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::BndryRegister > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::BoxArray > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::DistributionMapping > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::FabArrayId > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::FArrayBox * > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::Geometry > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::iMultiFab > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::MultiFab * > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::MultiFab > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::Vector< amrex::BoundCond > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::Vector< BLProfStats::TimeRange > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::Vector< int > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::Vector< Real > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< amrex::VisMF * > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< Array< amrex::MultiFab, AMREX_SPACEDIM > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< Array< amrex::MultiMask, 2 *AMREX_SPACEDIM > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< Array< std::unique_ptr< amrex::MultiFab >, AMREX_SPACEDIM > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< BCTuple > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< double > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< int > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< Long > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< Real > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< RealTuple > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< std::unique_ptr< amrex::FabFactory< amrex::FArrayBox > > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< std::unique_ptr< amrex::iMultiFab > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< std::unique_ptr< amrex::MLCellLinOp::BndryCondLoc > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::Vector< std::unique_ptr< amrex::MultiFab > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::VisMF::FabOnDisk >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::WeightedBox >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< amrex::YAFluxRegister >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Array< amrex::MultiFab *, AMREX_SPACEDIM > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Array< amrex::MultiFab, AMREX_SPACEDIM > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Array< BCType, AMREX_SPACEDIM > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Array< Real, AMREX_SPACEDIM > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< BLProfStats::BLPDataBlock >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< char * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< CommProfStats::BarrierEntry >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< CommProfStats::DataBlock >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< CommProfStats::NameTagEntry >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< CommProfStats::ReductionEntry >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< const amrex::MultiFab * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< const FabArrayBase::CopyComTagsContainer * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< double >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< GFab >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< gpuStream_t >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< HYPRE_Int >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Int >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< int >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< list< amrex::XYPlotDataListLink * > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Long >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< long >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< MPI_Request >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< MPI_Status >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< MultiFab >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< ParticleLevel >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< ParticleTilePtr >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< PetscInt >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Real >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< RealTuple >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< RegionsProfStats::DataBlock >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Setbuf_Char_Type >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::ifstream * >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::list< BLProfStats::TimeRange > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< int, amrex::IntVect > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< int, amrex::PODVector< amrex::IntVect > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< int, amrex::PODVector< int > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< PairIndex, amrex::Vector< amrex::NeighborParticleContainer::InverseCopyTag > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< PairIndex, amrex::Vector< amrex::Vector< amrex::NeighborParticleContainer::NeighborCopyTag > > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< PairIndex, int > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< PairIndex, IntVector > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< PairIndex, ParticleTile > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< std::pair< int, int >, amrex::NeighborList< ParticleType > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::map< std::string, int > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::pair< int, int > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::pair< void *, amrex::Arena * > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::size_t >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::string >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::AmrLevel > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::BndryRegister > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::EB2::IndexSpace > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::ErrorRec > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::iMultiFab > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::LayoutData< int > > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::MLMGBndry > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::MultiFab > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::StateDescriptor > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::StateDescriptor::BndryFunc > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< amrex::VisMF > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< std::unique_ptr< std::fstream > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< string >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< T >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Vector< MultiFab > >", "classamrex_1_1Vector.html", null ],
      [ "amrex::Vector< Vector< Real > >", "classamrex_1_1Vector.html", null ]
    ] ],
    [ "amrex::VectorTag< T >", "structamrex_1_1VectorTag.html", null ],
    [ "amrex::EB2::Vertex", "structamrex_1_1EB2_1_1Vertex.html", null ],
    [ "amrex::VisMF", "classamrex_1_1VisMF.html", null ],
    [ "VoidCopyTag", "structVoidCopyTag.html", null ],
    [ "amrex::Gpu::warpReduce< warpSize, T, F >", "structamrex_1_1Gpu_1_1warpReduce.html", null ],
    [ "amrex::WeightedBox", "classamrex_1_1WeightedBox.html", null ],
    [ "amrex::WeightedBoxList", "classamrex_1_1WeightedBoxList.html", null ],
    [ "amrex::AsyncOut::WriteInfo", "structamrex_1_1AsyncOut_1_1WriteInfo.html", null ],
    [ "amrex::XDim3", "structamrex_1_1XDim3.html", null ],
    [ "amrex::XYPlotDataList", "classamrex_1_1XYPlotDataList.html", null ],
    [ "amrex::XYPlotDataListLink", "classamrex_1_1XYPlotDataListLink.html", null ],
    [ "amrex::YAFluxRegister", "classamrex_1_1YAFluxRegister.html", [
      [ "amrex::EBFluxRegister", "classamrex_1_1EBFluxRegister.html", null ]
    ] ],
    [ "yy_buffer_state", "structyy__buffer__state.html", null ],
    [ "yy_trans_info", "structyy__trans__info.html", null ],
    [ "yyalloc", "unionyyalloc.html", null ]
];